import type { ExamId, ExamMetric, ExamModel } from '@/lib/exam-models';
import { getExamSkillCatalog, topicKey, type DifficultySelection } from '@/lib/exam-skill-catalog';

export type RoadmapQuestion = { id:number; exam_id:string; area:string; skill_name:string; prompt:string; difficulty:number };
export type RoadmapPriority = { metric: ExamMetric; current:number; goal:number; missing:number; score:number; accuracy?:number|null };
export type ExamMilestone = { label:string; date:string; note:string };
export type RoadmapSession = { label:string; minutes:number; task:string; proof:string };
export type RoadmapWeek = {
  week:number; start:string; end:string; phase:string; focusKey:string; focusLabel:string; topic:string;
  target:string; hours:number; questionTarget:number; questionIds:number[]; questionSkills:string[]; studyChecklist:string[];
  videoTitle:string; videoChannel:string; videoUrl:string; videoEmbedUrl:string|null;
  checkpoint:string; activities:string[]; mockExam:string; mockQuestions:number; hourBreakdown:{content:number;questions:number;review:number;mock:number};
  rationale:string; evidenceLabel:string; sessionPlan:RoadmapSession[]; successCriteria:string[]; totalPlannedMinutes:number;
};

const TZ='T12:00:00-03:00';
const day=86400000;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const date=(iso:string)=>new Date(`${iso}${TZ}`);
const isoDate=(d:Date)=>d.toISOString().slice(0,10);
const fmt=(iso:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(date(iso));
const round1=(n:number)=>Math.round(n*10)/10;
const min10=(n:number)=>Math.max(10,Math.round(n/10)*10);

export function getMilestones(examId:ExamId,course:string):ExamMilestone[]{
  if(examId==='insper')return[{label:'Vestibular Insper 2027.1',date:'2026-10-11',note:'prova presencial + redação'}];
  if(examId==='cmmg')return course==='Medicina'?[{label:'CMMG Medicina 2027.1',date:'2026-10-18',note:'prova presencial'}]:[{label:`CMMG ${course} 2027.1`,date:'2026-10-17',note:'prova do processo seletivo 2027.1'}];
  if(examId==='fuvest')return[{label:'FUVEST 1ª fase',date:'2026-11-01',note:'80 questões'},{label:'FUVEST 2ª fase — dia 1',date:'2026-12-06',note:'Português + redação'},{label:'FUVEST 2ª fase — dia 2',date:'2026-12-07',note:'disciplinas específicas da carreira'}];
  if(examId==='enem')return[{label:'ENEM — 1º dia',date:'2026-11-08',note:'Linguagens + Humanas + Redação'},{label:'ENEM — 2º dia',date:'2026-11-15',note:'Natureza + Matemática'}];
  return[{label:'PREP — prazo final',date:'2026-10-16',note:'vídeo + portfólio + documentação'},{label:'Link Sprint',date:'2026-10-23',note:'Matemática + Business Case'},{label:'Entrevistas — fim da janela',date:'2026-11-07',note:'etapa de entrevistas'}];
}

const fallbackTopicPools:Record<string,string[]>={
  linguagens:['Interpretação, inferência e finalidade do texto','Argumentação, tese e estratégias persuasivas','Coesão, coerência e progressão temática'],
  humanas:['Geopolítica e relações internacionais','República, Era Vargas e ditadura','Poder, Estado e cidadania'],
  natureza:['Genética e biologia molecular','Ecologia e ciclos biogeoquímicos','Estequiometria','Circuitos elétricos e eletrodinâmica'],
  matematica:['Razão, proporção, porcentagem e regra de três','Funções afim, quadrática, exponencial e logarítmica','Estatística e leitura de gráficos','Probabilidade'],
  redacao:['Tese e projeto de texto','Desenvolvimento de argumentos','Coesão e articulação entre parágrafos','Proposta de intervenção completa e detalhada'],
  portugues:['Interpretação e análise de textos','Gramática aplicada ao texto','Semântica e efeitos de sentido'],
  '1ª fase':['Interpretação interdisciplinar','Gestão de tempo e estratégia de prova'],
  'business case':['Estruturação do problema','Análise de dados','Recomendação baseada em evidências'],
  escrita:['Síntese','Clareza e estrutura','Argumentação'],
  oral:['Estrutura da resposta','Clareza e objetividade','Storytelling'],
  portfolio:['Seleção de experiências','Contexto, ação e resultado','Demonstração de impacto'],
  entrevista:['Motivação e fit','Perguntas comportamentais','Exemplos concretos'],
};

const channelFor=(key:string)=>{const k=norm(key);if(k.includes('matemat'))return'Professor Ferretto / Khan Academy Brasil';if(['fisica','quimica','biologia','natureza'].some(x=>k.includes(x)))return'Professor Ferretto / Brasil Escola';if(['historia','geografia','filosofia','sociologia','humanas'].some(x=>k.includes(x)))return'Brasil Escola / Curso Enem Gratuito';if(['redacao','portugues','linguagens','literatura','ingles'].some(x=>k.includes(x)))return'Professor Noslen / Brasil Escola';if(k.includes('business')||k.includes('escrita')||k.includes('portfolio')||k.includes('entrevista')||k.includes('oral'))return'Link School of Business / Sebrae';return'Khan Academy Brasil / Brasil Escola'};
function ytUrl(key:string,topic:string,examId:ExamId,course:string){const channel=channelFor(key).split(' / ')[0];const context=examId==='fuvest'?'FUVEST 2027':examId==='cmmg'?'vestibular Ciências Médicas 2027.1':examId==='insper'?'vestibular Insper 2027.1':examId==='link'?'Jornada Link':'ENEM 2026';return`https://www.youtube.com/results?search_query=${encodeURIComponent(`${topic} ${context} ${course} ${channel}`)}`}
function curatedEmbed(key:string,topic:string){const k=norm(`${key} ${topic}`);if(k.includes('interpretacao'))return'https://www.youtube-nocookie.com/embed/X6g5caxEAvE';if(k.includes('func')||k.includes('grafico'))return'https://www.youtube-nocookie.com/embed/SPZqQ5qn3P0';if(k.includes('genet'))return'https://www.youtube-nocookie.com/embed/FZK4MJbafTU';if(k.includes('ecolog'))return'https://www.youtube-nocookie.com/embed/pgVVimiPR1o';return null}
function matchArea(area:string,key:string){const a=norm(area),k=norm(key.replace('2ª fase — ','').replace('2a fase — ',''));if(a===k||a.includes(k)||k.includes(a))return true;if(k==='natureza')return['natureza','biologia','fisica','quimica'].some(x=>a.includes(x));if(k==='humanas'||k==='conhecimentos gerais')return['humanas','historia','geografia','filosofia','sociologia','conhecimentos gerais'].some(x=>a.includes(x));if(k==='linguagens')return['linguagens','portugues','literatura','ingles'].some(x=>a.includes(x));if(k==='1ª fase')return true;if(k==='oral')return a.includes('comunicacao')||a.includes('entrevista');if(k==='portfolio')return a.includes('prep')||a.includes('portfolio');if(k==='escrita')return a.includes('business case')||a.includes('sprint')||a.includes('escrita');if(k==='matematica'&&(a.includes('sprint')||a.includes('matematica')))return true;return false}
function phaseFor(examId:ExamId,start:Date){const t=start.getTime();if(examId==='fuvest')return t<date('2026-11-02').getTime()?'FUVEST · 1ª fase':'FUVEST · 2ª fase';if(examId==='enem')return t<date('2026-11-09').getTime()?'ENEM · 1º dia':'ENEM · 2º dia';if(examId==='link'){if(t<date('2026-10-17').getTime())return'Link · PREP';if(t<date('2026-10-24').getTime())return'Link · Sprint';return'Link · Entrevista'}return'Reta de preparação'}
function eligible(priority:RoadmapPriority,examId:ExamId,phase:string){const k=norm(priority.metric.key);if(examId==='fuvest'){if(phase.includes('1ª'))return k==='1ª fase';return k!=='1ª fase'}if(examId==='enem'){if(phase.includes('1º'))return['linguagens','humanas','redacao'].includes(k);return['natureza','matematica'].includes(k)}if(examId==='link'){if(phase.includes('PREP'))return['portfolio','oral'].includes(k);if(phase.includes('Sprint'))return['matematica','business case','escrita','oral'].includes(k);return['entrevista','oral'].includes(k)}return true}
function choosePriority(candidates:RoadmapPriority[],week:number,boost:(p:RoadmapPriority)=>number){if(!candidates.length)return undefined;const effective=candidates.map(p=>({p,s:p.score*boost(p)}));const max=Math.max(...effective.map(x=>x.s),.01);const weighted=effective.flatMap(({p,s})=>Array.from({length:Math.max(1,Math.min(6,Math.round((s/max)*5)))},()=>p));return weighted[(week-1)%weighted.length]??candidates[0]}
function allocateHours(total:number,fullMock:boolean){const ratios=fullMock?{content:.18,questions:.24,review:.13,mock:.45}:{content:.27,questions:.36,review:.17,mock:.20};const content=round1(total*ratios.content),questions=round1(total*ratios.questions),review=round1(total*ratios.review);const mock=round1(Math.max(.3,total-content-questions-review));return{content,questions,review,mock}}
function mockPlan(examId:ExamId,week:number,mockHours:number,phase:string,close:boolean,totalHours:number){const canFull=totalHours>=8&&(close||week%3===0);const capacity=Math.max(8,Math.floor(mockHours*18));if(examId==='enem'){const q=canFull?Math.min(90,capacity):Math.min(45,capacity);return{full:canFull,q,label:canFull?`Simulado ENEM de ${q} questões em condição de prova + correção`:`Mini-simulado ENEM de ${q} questões, cronometrado e sem consulta`}}if(examId==='fuvest'){const max=phase.includes('1ª')?80:20;const q=canFull?Math.min(max,capacity):Math.min(32,capacity);return{full:canFull,q,label:phase.includes('1ª')?`${canFull?'Simulado':'Mini-simulado'} FUVEST de ${q} questões`:`Treino de 2ª fase com ${q} itens/discursivas + correção por critérios`}}if(examId==='cmmg'){const q=canFull?Math.min(60,capacity):Math.min(30,capacity);return{full:canFull,q,label:`${canFull?'Simulado CMMG':'Mini-simulado CMMG'} de ${q} questões + correção`}}if(examId==='insper'){const q=canFull?Math.min(60,capacity):Math.min(30,capacity);return{full:canFull,q,label:`${canFull?'Simulado Insper':'Mini-simulado Insper'} de ${q} questões${canFull?' + redação':''}`}}return{full:canFull,q:Math.max(4,Math.floor(mockHours*6)),label:phase.includes('Sprint')?'Simulação de Sprint: matemática + business case cronometrado':phase.includes('Entrevista')?'Simulação de entrevista com gravação e autoavaliação':'Revisão PREP com ensaio de vídeo/portfólio'}}

function officialTopicsFor(catalog:ReturnType<typeof getExamSkillCatalog>,focus:string){
  return catalog.subjects
    .filter(subject=>matchArea(subject.area,focus)||matchArea(subject.subject,focus))
    .flatMap(subject=>subject.topics.map(topic=>({subject:subject.subject,area:subject.area,topic})));
}
function detailStudy(topic:string,focus:string){
  const k=norm(`${focus} ${topic}`);
  const core=[`Dominar: ${topic}.`,`Resolver exemplos básicos antes de partir para questões de prova.`,`Fechar com uma explicação de 3–5 linhas, sem consultar material.`];
  if(k.includes('func')||k.includes('grafico'))return[`Revisar definição, domínio/imagem e leitura dos elementos do gráfico em ${topic}.`,`Treinar zeros/interseções, crescimento/decrescimento e transformação entre expressão, tabela e gráfico.`,`Resolver problemas contextualizados e justificar por que o modelo escolhido representa a situação.`];
  if(k.includes('porcent')||k.includes('propor')||k.includes('finance'))return[`Revisar razão, proporção, variação percentual e fatores multiplicativos.`,`Treinar aumentos/descontos sucessivos, taxas e comparação entre grandezas.`,`Resolver situações contextualizadas verificando unidade, ordem de grandeza e coerência do resultado.`];
  if(k.includes('probabil')||k.includes('combin'))return[`Identificar espaço amostral, eventos e princípio multiplicativo.`,`Distinguir quando ordenar importa e quando não importa; treinar contagem antes da fórmula.`,`Resolver questões mistas e conferir o resultado por estimativa/probabilidade máxima de 1.`];
  if(k.includes('genet'))return[`Revisar gene, alelo, genótipo/fenótipo e padrões de herança ligados a ${topic}.`,`Treinar cruzamentos, heredogramas e probabilidade genética passo a passo.`,`Conectar genética clássica a DNA, expressão gênica e biotecnologia quando a questão exigir.`];
  if(k.includes('ecolog'))return[`Revisar níveis de organização, cadeias/teias, fluxo de energia e relações ecológicas.`,`Treinar ciclos biogeoquímicos e impactos ambientais com leitura de gráficos/tabelas.`,`Resolver questões conectando causa → alteração ambiental → consequência ecológica.`];
  if(k.includes('estequi'))return[`Balancear equações e converter massa, mol, partículas e volume.`,`Treinar reagente limitante, pureza e rendimento em problemas graduais.`,`Resolver questões completas registrando unidades em cada etapa para evitar erro de cálculo.`];
  if(k.includes('circuit')||k.includes('eletric'))return[`Revisar corrente, tensão, resistência, potência e energia elétrica.`,`Treinar associação de resistores e leitura de circuitos/esquemas.`,`Resolver problemas aplicando relações físicas com unidade correta e interpretação do resultado.`];
  if(k.includes('interpret')||k.includes('inferencia'))return[`Identificar tema, tese/finalidade e pistas explícitas do texto.`,`Separar informação literal de inferência e testar cada alternativa contra evidências textuais.`,`Treinar textos de gêneros diferentes e registrar o trecho que sustenta cada resposta.`];
  if(k.includes('argument')||k.includes('tese'))return[`Definir tese/posição central e mapear os argumentos que a sustentam.`,`Reconhecer evidências, pressupostos, contra-argumentos e estratégias persuasivas.`,`Produzir uma síntese curta: tese + argumento 1 + argumento 2 + evidência.`];
  if(k.includes('redacao')||k.includes('intervencao')||k.includes('coesao'))return[`Planejar tese e dois eixos argumentativos antes de escrever.`,`Produzir parágrafos com tópico frasal, explicação, evidência/repertório e fechamento.`,`Revisar coesão, precisão linguística e, no ENEM, agente + ação + meio + finalidade da intervenção.`];
  if(k.includes('geopolit')||k.includes('globaliza'))return[`Revisar atores, interesses, território, fluxos e relações de poder ligados a ${topic}.`,`Construir relações de causa e consequência, evitando decorar fatos isolados.`,`Treinar mapas, charges, gráficos e textos de atualidades conectando-os aos conceitos do programa.`];
  if(k.includes('business case'))return[`Definir o problema em uma frase e separar sintomas de causas.`,`Montar hipóteses, escolher métricas e analisar os dados antes de recomendar.`,`Fechar com recomendação objetiva: decisão + evidência + risco + próximo passo.`];
  if(k.includes('portfolio'))return[`Selecionar experiências com evidência concreta de ação e impacto.`,`Escrever cada caso no formato contexto → ação → resultado → aprendizado.`,`Checar coerência entre trajetória, motivação e o perfil que será apresentado à instituição.`];
  if(k.includes('entrevista')||k.includes('oral')||k.includes('storytell'))return[`Preparar respostas de 60–90 s com começo, evidência concreta e fechamento.`,`Treinar exemplos comportamentais no formato situação → ação → resultado → aprendizado.`,`Gravar uma resposta, revisar clareza, objetividade, tempo e vícios de linguagem, e gravar novamente.`];
  return core;
}
function questionSkillsFor(questions:RoadmapQuestion[],focus:string,topic:string){
  const topicWords=norm(topic).split(/\s+/).filter(w=>w.length>4);
  return Array.from(new Set(questions.filter(q=>matchArea(q.area,focus)).sort((a,b)=>{
    const score=(q:RoadmapQuestion)=>topicWords.filter(w=>norm(`${q.skill_name} ${q.prompt}`).includes(w)).length;
    return score(b)-score(a)||b.difficulty-a.difficulty;
  }).map(q=>q.skill_name).filter(Boolean))).slice(0,4);
}
function buildSessions(hours:{content:number;questions:number;review:number;mock:number},topic:string,qTarget:number,mockLabel:string,studyChecklist:string[],questionSkills:string[]){
  const skills=questionSkills.length?` Priorize: ${questionSkills.join('; ')}.`:'';
  return[
    {label:'Aprender',minutes:min10(hours.content*60),task:`Estudar ${topic}. ${studyChecklist.join(' ')}`,proof:`Sem olhar material, explicar ${topic} e acertar 3 exemplos guiados em sequência.`},
    {label:'Aplicar',minutes:min10(hours.questions*60),task:`Resolver ${qTarget} questões com correção imediata.${skills}`,proof:'Em cada erro, registrar assunto, causa do erro e qual regra/conceito resolveria a questão.'},
    {label:'Consolidar',minutes:min10(hours.review*60),task:`Refazer os erros de ${topic} e montar uma folha curta de revisão com fórmulas, conceitos, pegadinhas e 3 exemplos.`,proof:'Refazer sem consultar a resolução e conseguir explicar cada correção em voz alta.'},
    {label:'Medir',minutes:min10(hours.mock*60),task:mockLabel,proof:'Registrar acertos, tempo, áreas dos erros e atualizar a prioridade da semana seguinte.'},
  ];
}

export function buildRoadmap(args:{model:ExamModel;course:string;priorities:RoadmapPriority[];weeklyHours:number;questions:RoadmapQuestion[];difficultyTopics?:DifficultySelection;diagnostics?:{area:string;skill:string}[];today?:Date}){
  const{model,course,priorities,questions}=args;const difficultyTopics=args.difficultyTopics??{};const diagnostics=args.diagnostics??[];const catalog=getExamSkillCatalog(model.examId,course);
  const difficultyFor=(focus:string)=>catalog.subjects.flatMap(s=>s.topics.map(topic=>({subject:s.subject,area:s.area,topic,level:difficultyTopics[topicKey(s.subject,topic)]??0}))).filter(x=>x.level>0&&(matchArea(x.area,focus)||matchArea(x.subject,focus))).sort((a,b)=>b.level-a.level);
  const diagnosticFor=(focus:string)=>diagnostics.filter(d=>matchArea(d.area,focus));const weeklyHours=Math.max(3,Math.min(30,Math.round(args.weeklyHours)));const milestones=getMilestones(model.examId,course);const finalDate=date(milestones[milestones.length-1].date);const rawToday=args.today??new Date();const startToday=new Date(rawToday.getFullYear(),rawToday.getMonth(),rawToday.getDate(),12);const monday=new Date(startToday);monday.setDate(startToday.getDate()-((startToday.getDay()+6)%7));const weeks:RoadmapWeek[]=[];const maxWeeks=22;
  for(let i=0;i<maxWeeks;i++){
    const ws=new Date(monday.getTime()+i*7*day);if(ws.getTime()>finalDate.getTime())break;const we=new Date(Math.min(ws.getTime()+6*day,finalDate.getTime()));const phase=phaseFor(model.examId,ws);let candidates=priorities.filter(p=>eligible(p,model.examId,phase));if(!candidates.length)candidates=priorities;const p=choosePriority(candidates,i+1,x=>{const key=x.metric.key.replace('2ª fase — ','');const manual=difficultyFor(key);const scans=diagnosticFor(key);return 1+Math.min(.75,manual.reduce((a,b)=>a+b.level,0)*.08)+Math.min(.35,scans.length*.1)});if(!p)continue;
    const baseKey=p.metric.key.replace('2ª fase — ','');const manual=difficultyFor(baseKey);const scans=diagnosticFor(baseKey);const official=officialTopicsFor(catalog,baseKey);const fallback=fallbackTopicPools[norm(baseKey)]??fallbackTopicPools[norm(p.metric.label)]??['Revisão dirigida e resolução de questões'];const manualTopic=manual.length?manual[i%Math.min(manual.length,4)]?.topic:null;const scanTopic=scans.length?scans[i%scans.length]?.skill:null;const officialTopic=official.length?official[Math.floor(i/Math.max(1,candidates.length))%official.length]?.topic:null;const topic=manualTopic||scanTopic||officialTopic||fallback[Math.floor(i/Math.max(1,candidates.length))%fallback.length];
    const relevant=questions.filter(q=>matchArea(q.area,baseKey));const closeToExam=(finalDate.getTime()-ws.getTime())/day<=12;const fullMockWanted=weeklyHours>=8&&(closeToExam||(i+1)%3===0);const hours=allocateHours(weeklyHours,fullMockWanted);const qTarget=Math.max(10,Math.min(90,Math.round(hours.questions*11*(p.score>.25?1.08:1))));const questionIds=relevant.length?Array.from({length:Math.min(qTarget,30)},(_,j)=>relevant[(i*7+j)%relevant.length].id):[];const questionSkills=questionSkillsFor(relevant,baseKey,topic);const studyChecklist=detailStudy(topic,baseKey);const mock=mockPlan(model.examId,i+1,hours.mock,phase,closeToExam,weeklyHours);const sessionPlan=buildSessions(hours,topic,qTarget,mock.label,studyChecklist,questionSkills);const totalMinutes=Math.round(weeklyHours*60);const measuredMinutes=sessionPlan.reduce((s,x)=>s+x.minutes,0);if(sessionPlan.length)sessionPlan[sessionPlan.length-1].minutes=Math.max(10,sessionPlan[sessionPlan.length-1].minutes+(totalMinutes-measuredMinutes));
    const accuracyText=p.accuracy==null?'ainda sem amostra suficiente de questões':`acerto recente de ${Math.round(p.accuracy*100)}% nas questões desta área`;const adaptationReason=manualTopic?` Você marcou ${manualTopic} como dificuldade, então esse tópico recebeu peso adicional.`:scanTopic?` Um diagnóstico recente apontou ${scanTopic}, então esse ponto entrou diretamente no foco.`:` O tópico foi escolhido dentro de ${catalog.label}.`;const rationale=p.metric.unit==='acertos'?`Você está em ${p.current}/${p.metric.max}, com meta ${p.goal}. Como faltam ${p.missing} acertos e há ${accuracyText}, esta área recebe prioridade proporcional — sem aumentar suas ${weeklyHours}h semanais.${adaptationReason}`:`Seu resultado atual é ${p.current}/${p.metric.max}, meta ${p.goal}; ${accuracyText}. Esta semana concentra prática aqui sem ultrapassar seu tempo disponível.${adaptationReason}`;
    const activities=sessionPlan.map(s=>`${s.label}: ${s.task} (${s.minutes} min)`);const target=activities.join(' • ');const nextGoal=p.metric.unit==='acertos'?Math.min(p.goal,p.current+Math.max(1,Math.ceil(p.missing/3))):p.goal;const checkpoint=p.metric.unit==='acertos'?`Fechar a semana com ${qTarget} questões corrigidas + ${mock.label}; no próximo bloco, buscar pelo menos ${nextGoal}/${p.metric.max}.`:`Fechar as quatro etapas e registrar o resultado do bloco de medição para recalibrar a semana seguinte.`;const successCriteria=[`Conseguir explicar os pontos de ${topic} listados no roteiro sem consultar material.`,`Cumprir ${qTarget} questões com correção e classificação dos erros.`,`Refazer os erros principais sem consultar a resolução.`,`Concluir o bloco de medição: ${mock.label}.`,`Manter o total em ${weeklyHours}h; nada desta semana é “extra” fora do seu orçamento de tempo.`];
    weeks.push({week:i+1,start:isoDate(ws),end:isoDate(we),phase,focusKey:baseKey,focusLabel:p.metric.label,topic,target,hours:weeklyHours,questionTarget:qTarget,questionIds,questionSkills,studyChecklist,videoTitle:`Aula dirigida: ${topic}`,videoChannel:channelFor(baseKey),videoUrl:ytUrl(baseKey,topic,model.examId,course),videoEmbedUrl:curatedEmbed(baseKey,topic),checkpoint,activities,mockExam:mock.label,mockQuestions:mock.q,hourBreakdown:{content:hours.content,questions:hours.questions,review:hours.review,mock:hours.mock},rationale,evidenceLabel:`Prioridade calculada por distância até a meta${p.accuracy==null?'':' + desempenho recente'}${manualTopic?' + dificuldade declarada':''}${scanTopic?' + diagnóstico por foto':''} + conteúdo do programa oficial`,sessionPlan,successCriteria,totalPlannedMinutes:totalMinutes});
  }
  return{weeks,milestones,finalDate:isoDate(finalDate),daysLeft:Math.max(0,Math.ceil((finalDate.getTime()-startToday.getTime())/day)),dateLabel:`${fmt(milestones[0].date)}${milestones.length>1?` → ${fmt(milestones[milestones.length-1].date)}`:''}`,sourceLabel:catalog.sourceLabel,sourceUrl:catalog.sourceUrl};
}
