import type { ExamId, ExamMetric, ExamModel } from '@/lib/exam-models';
import { getExamSkillCatalog, topicKey, type DifficultySelection } from '@/lib/exam-skill-catalog';

export type RoadmapQuestion = { id:number; exam_id:string; area:string; skill_name:string; prompt:string; difficulty:number };
export type RoadmapPriority = { metric: ExamMetric; current:number; goal:number; missing:number; score:number; accuracy?:number|null };
export type ExamMilestone = { label:string; date:string; note:string };
export type RoadmapSession = { label:string; minutes:number; task:string; proof:string };
export type RoadmapWeek = {
  week:number; start:string; end:string; phase:string; focusKey:string; focusLabel:string; topic:string;
  target:string; hours:number; questionTarget:number; questionIds:number[]; videoTitle:string; videoChannel:string; videoUrl:string; videoEmbedUrl:string|null;
  checkpoint:string; activities:string[]; mockExam:string; mockQuestions:number; hourBreakdown:{content:number;questions:number;review:number;mock:number};
  rationale:string; evidenceLabel:string; sessionPlan:RoadmapSession[]; successCriteria:string[]; totalPlannedMinutes:number;
};

const TZ='T12:00:00-03:00';
const day=86400000;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const date=(iso:string)=>new Date(`${iso}${TZ}`);
const isoDate=(d:Date)=>d.toISOString().slice(0,10);
const fmt=(iso:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(date(iso));
const round1=(n:number)=>Math.round(n*10)/10;
const min10=(n:number)=>Math.max(10,Math.round(n/10)*10);

export function getMilestones(examId:ExamId,course:string):ExamMilestone[]{
  if(examId==='insper')return[{label:'Vestibular Insper 2027.1',date:'2026-10-11',note:'60 objetivas + redação'}];
  if(examId==='cmmg')return course==='Medicina'?[{label:'CMMG Medicina 2027.1',date:'2026-10-18',note:'prova presencial'}]:[{label:`CMMG ${course} 2027.1`,date:'2026-10-17',note:'40 objetivas + redação'}];
  if(examId==='fuvest')return[{label:'FUVEST 1ª fase',date:'2026-11-01',note:'80 questões'},{label:'FUVEST 2ª fase — dia 1',date:'2026-12-06',note:'Português + redação'},{label:'FUVEST 2ª fase — dia 2',date:'2026-12-07',note:'disciplinas específicas da carreira'}];
  if(examId==='enem')return[{label:'ENEM — 1º dia',date:'2026-11-08',note:'Linguagens + Humanas + Redação'},{label:'ENEM — 2º dia',date:'2026-11-15',note:'Natureza + Matemática'}];
  return[{label:'PREP — prazo final',date:'2026-10-16',note:'vídeo + portfólio + documentação'},{label:'Link Sprint',date:'2026-10-23',note:'20–23/10: Matemática + Business Case'},{label:'Entrevistas — fim da janela',date:'2026-11-07',note:'28–30/10 e 03–07/11'}];
}

const topicPools:Record<string,string[]>={
  'linguagens':['interpretação e inferência','funções da linguagem e gêneros textuais','coesão, coerência e argumentação','literatura e leitura de texto','linguagem verbal e não verbal'],
  'lingua portuguesa':['interpretação, sintaxe e efeitos de sentido','coesão, regência e concordância','gêneros textuais e argumentação'],
  'portugues':['interpretação, sintaxe e efeitos de sentido','coesão, regência e concordância','literatura e análise textual'],
  'literatura':['obra obrigatória e interpretação literária','escolas literárias e recursos de linguagem','narrador, personagens e construção de sentido'],
  'ingles':['leitura instrumental e inferência','vocabulário em contexto e cognatos','interpretação de textos em inglês'],
  'humanas':['Brasil República e cidadania','geopolítica e globalização','filosofia, sociologia e leitura de fontes','território, população e economia','trabalho, tecnologia e desigualdade'],
  'conhecimentos gerais':['História e cidadania','Geografia e atualidades','Filosofia e Sociologia'],
  'historia':['Brasil República, cidadania e movimentos sociais','História Moderna e Contemporânea','interpretação de fontes históricas'],
  'geografia':['geopolítica e globalização','urbanização, população e território','clima, ambiente e economia'],
  'filosofia':['ética, política e teoria do conhecimento','filosofia moderna e contemporânea'],
  'sociologia':['cultura, desigualdade e cidadania','trabalho, poder e movimentos sociais'],
  'natureza':['ecologia e ciclos biogeoquímicos','mecânica, energia e eletricidade','estequiometria, soluções e química orgânica','genética, fisiologia e evolução','ambiente, saúde e tecnologia'],
  'biologia':['genética e biologia molecular','ecologia e evolução','fisiologia humana','citologia e metabolismo'],
  'fisica':['mecânica e dinâmica','energia, trabalho e potência','eletricidade e circuitos','ondas, óptica e termologia'],
  'quimica':['estequiometria e soluções','química orgânica e funções','equilíbrio, pH e eletroquímica','ligações e propriedades da matéria'],
  'matematica':['funções e gráficos','geometria plana e espacial','probabilidade e combinatória','razões, porcentagem e matemática financeira','estatística e análise de dados'],
  'redacao':['tese, repertório e projeto de texto','argumentação e desenvolvimento','coesão e proposta de intervenção','reescrita com correção por critérios'],
  '1ª fase':['prova interdisciplinar e gestão de tempo','revisão de alta incidência + estratégia de prova'],
  'business case':['estruturação de problema e hipóteses','unit economics e análise de dados','recomendação executiva baseada em evidências'],
  'escrita':['escrita executiva: problema, análise e recomendação','clareza, síntese e persuasão'],
  'oral':['comunicação em vídeo: estrutura, clareza e presença','storytelling e resposta objetiva'],
  'portfolio':['seleção de evidências, impacto e narrativa pessoal','portfólio: contexto, ação e resultado'],
  'entrevista':['motivação, fit e exemplos comportamentais','entrevista em português e inglês'],
};

const channelFor=(key:string)=>{const k=norm(key);if(k.includes('matemat'))return'Professor Ferretto / Khan Academy Brasil';if(['fisica','quimica','biologia','natureza'].some(x=>k.includes(x)))return'Professor Ferretto / Brasil Escola';if(['historia','geografia','filosofia','sociologia','humanas'].some(x=>k.includes(x)))return'Brasil Escola / Curso Enem Gratuito';if(['redacao','portugues','linguagens','literatura','ingles'].some(x=>k.includes(x)))return'Professor Noslen / Brasil Escola';if(k.includes('business')||k.includes('escrita')||k.includes('portfolio')||k.includes('entrevista')||k.includes('oral'))return'Link School of Business / Sebrae';return'Khan Academy Brasil / Brasil Escola'};
function ytUrl(key:string,topic:string,examId:ExamId,course:string){const channel=channelFor(key).split(' / ')[0];const context=examId==='fuvest'?'FUVEST':examId==='cmmg'?'vestibular Ciências Médicas':examId==='insper'?'vestibular Insper':examId==='link'?'Jornada Link':'ENEM';return`https://www.youtube.com/results?search_query=${encodeURIComponent(`${topic} ${context} ${course} ${channel}`)}`}
function curatedEmbed(key:string,topic:string){const k=norm(`${key} ${topic}`);if(k.includes('interpretacao'))return'https://www.youtube-nocookie.com/embed/X6g5caxEAvE';if(k.includes('func')||k.includes('grafico'))return'https://www.youtube-nocookie.com/embed/SPZqQ5qn3P0';if(k.includes('genet'))return'https://www.youtube-nocookie.com/embed/FZK4MJbafTU';if(k.includes('ecolog'))return'https://www.youtube-nocookie.com/embed/pgVVimiPR1o';return null}
function matchArea(area:string,key:string){const a=norm(area),k=norm(key.replace('2ª fase — ','').replace('2a fase — ',''));if(a===k||a.includes(k)||k.includes(a))return true;if(k==='natureza')return['natureza','biologia','fisica','quimica'].some(x=>a.includes(x));if(k==='humanas'||k==='conhecimentos gerais')return['humanas','historia','geografia','filosofia','sociologia','conhecimentos gerais'].some(x=>a.includes(x));if(k==='linguagens')return['linguagens','portugues','literatura','ingles'].some(x=>a.includes(x));if(k==='1ª fase')return true;if(k==='oral')return a.includes('comunicacao')||a.includes('entrevista');if(k==='portfolio')return a.includes('prep')||a.includes('portfolio');if(k==='escrita')return a.includes('business case')||a.includes('sprint')||a.includes('escrita');return false}
function phaseFor(examId:ExamId,start:Date){const t=start.getTime();if(examId==='fuvest')return t<date('2026-11-02').getTime()?'FUVEST · 1ª fase':'FUVEST · 2ª fase';if(examId==='enem')return t<date('2026-11-09').getTime()?'ENEM · 1º dia':'ENEM · 2º dia';if(examId==='link'){if(t<date('2026-10-17').getTime())return'Link · PREP';if(t<date('2026-10-24').getTime())return'Link · Sprint';return'Link · Entrevista'}return'Reta de preparação'}
function eligible(priority:RoadmapPriority,examId:ExamId,phase:string){const k=norm(priority.metric.key);if(examId==='fuvest'){if(phase.includes('1ª'))return k==='1ª fase';return k!=='1ª fase'}if(examId==='enem'){if(phase.includes('1º'))return['linguagens','humanas','redacao'].includes(k);return['natureza','matematica'].includes(k)}if(examId==='link'){if(phase.includes('PREP'))return['portfolio','oral'].includes(k);if(phase.includes('Sprint'))return['matematica','business case','escrita','oral'].includes(k);return['entrevista','oral'].includes(k)}return true}
function choosePriority(candidates:RoadmapPriority[],week:number,boost:(p:RoadmapPriority)=>number){if(!candidates.length)return undefined;const effective=candidates.map(p=>({p,s:p.score*boost(p)}));const max=Math.max(...effective.map(x=>x.s),.01);const weighted=effective.flatMap(({p,s})=>Array.from({length:Math.max(1,Math.min(6,Math.round((s/max)*5)))},()=>p));return weighted[(week-1)%weighted.length]??candidates[0]}
function allocateHours(total:number,fullMock:boolean){const ratios=fullMock?{content:.18,questions:.24,review:.13,mock:.45}:{content:.27,questions:.36,review:.17,mock:.20};const content=round1(total*ratios.content),questions=round1(total*ratios.questions),review=round1(total*ratios.review);const mock=round1(Math.max(.3,total-content-questions-review));return{content,questions,review,mock}}
function mockPlan(examId:ExamId,week:number,mockHours:number,phase:string,close:boolean,totalHours:number){const canFull=totalHours>=8&&(close||week%3===0);const capacity=Math.max(8,Math.floor(mockHours*18));if(examId==='enem'){const q=canFull?Math.min(90,capacity):Math.min(45,capacity);return{full:canFull,q,label:canFull?`Simulado ENEM de ${q} questões em condição de prova + correção`:`Mini-simulado ENEM de ${q} questões, cronometrado e sem consulta`}}if(examId==='fuvest'){const max=phase.includes('1ª')?80:20;const q=canFull?Math.min(max,capacity):Math.min(32,capacity);return{full:canFull,q,label:phase.includes('1ª')?`${canFull?'Simulado':'Mini-simulado'} FUVEST de ${q} questões`:`Treino de 2ª fase com ${q} itens/discursivas + correção por critérios`}}if(examId==='cmmg'){const q=canFull?Math.min(60,capacity):Math.min(30,capacity);return{full:canFull,q,label:`${canFull?'Simulado CMMG':'Mini-simulado CMMG'} de ${q} questões + correção`}}if(examId==='insper'){const q=canFull?Math.min(60,capacity):Math.min(30,capacity);return{full:canFull,q,label:`${canFull?'Simulado Insper':'Mini-simulado Insper'} de ${q} questões${canFull?' + redação':''}`}}return{full:canFull,q:Math.max(4,Math.floor(mockHours*6)),label:phase.includes('Sprint')?'Simulação de Sprint: matemática + business case cronometrado':phase.includes('Entrevista')?'Simulação de entrevista com gravação e autoavaliação':'Revisão PREP com ensaio de vídeo/portfólio'}}
function buildSessions(hours:{content:number;questions:number;review:number;mock:number},topic:string,qTarget:number,mockLabel:string){const items=[{label:'Aprender',minutes:min10(hours.content*60),task:`Aula guiada + recuperação ativa de ${topic}`,proof:'Fechar sem consulta com 5 ideias-chave e 2 dúvidas respondidas.'},{label:'Aplicar',minutes:min10(hours.questions*60),task:`Resolver ${qTarget} questões com correção imediata`,proof:'Marcar motivo de cada erro: conteúdo, interpretação, cálculo, tempo ou distração.'},{label:'Consolidar',minutes:min10(hours.review*60),task:'Caderno de erros + refazer sem olhar a resolução',proof:'Só encerrar quando conseguir explicar o erro e a correção em uma frase.'},{label:'Medir',minutes:min10(hours.mock*60),task:mockLabel,proof:'Registrar resultado e usar os erros para recalibrar a próxima semana.'}];return items}

export function buildRoadmap(args:{model:ExamModel;course:string;priorities:RoadmapPriority[];weeklyHours:number;questions:RoadmapQuestion[];difficultyTopics?:DifficultySelection;diagnostics?:{area:string;skill:string}[];today?:Date}){
  const{model,course,priorities,questions}=args;const difficultyTopics=args.difficultyTopics??{};const diagnostics=args.diagnostics??[];const catalog=getExamSkillCatalog(model.examId,course);
  const difficultyFor=(focus:string)=>catalog.subjects.flatMap(s=>s.topics.map(topic=>({subject:s.subject,area:s.area,topic,level:difficultyTopics[topicKey(s.subject,topic)]??0}))).filter(x=>x.level>0&&(matchArea(x.area,focus)||matchArea(x.subject,focus))).sort((a,b)=>b.level-a.level);
  const diagnosticFor=(focus:string)=>diagnostics.filter(d=>matchArea(d.area,focus));const weeklyHours=Math.max(3,Math.min(30,Math.round(args.weeklyHours)));const milestones=getMilestones(model.examId,course);const finalDate=date(milestones[milestones.length-1].date);const rawToday=args.today??new Date();const startToday=new Date(rawToday.getFullYear(),rawToday.getMonth(),rawToday.getDate(),12);const monday=new Date(startToday);monday.setDate(startToday.getDate()-((startToday.getDay()+6)%7));const weeks:RoadmapWeek[]=[];const maxWeeks=22;
  for(let i=0;i<maxWeeks;i++){
    const ws=new Date(monday.getTime()+i*7*day);if(ws.getTime()>finalDate.getTime())break;const we=new Date(Math.min(ws.getTime()+6*day,finalDate.getTime()));const phase=phaseFor(model.examId,ws);let candidates=priorities.filter(p=>eligible(p,model.examId,phase));if(!candidates.length)candidates=priorities;const p=choosePriority(candidates,i+1,x=>{const key=x.metric.key.replace('2ª fase — ','');const manual=difficultyFor(key);const scans=diagnosticFor(key);return 1+Math.min(.75,manual.reduce((a,b)=>a+b.level,0)*.08)+Math.min(.35,scans.length*.1)});if(!p)continue;const baseKey=p.metric.key.replace('2ª fase — ','');const pool=topicPools[norm(baseKey)]??topicPools[norm(p.metric.label)]??['revisão dirigida e resolução de questões'];const manual=difficultyFor(baseKey);const scans=diagnosticFor(baseKey);const manualTopic=manual.length?manual[i%Math.min(manual.length,4)]?.topic:null;const scanTopic=scans.length?scans[i%scans.length]?.skill:null;const topic=manualTopic||scanTopic||pool[Math.floor(i/Math.max(1,candidates.length))%pool.length];const relevant=questions.filter(q=>matchArea(q.area,baseKey));const closeToExam=(finalDate.getTime()-ws.getTime())/day<=12;
    const fullMockWanted=weeklyHours>=8&&(closeToExam||(i+1)%3===0);const hours=allocateHours(weeklyHours,fullMockWanted);const qTarget=Math.max(10,Math.min(90,Math.round(hours.questions*11*(p.score>.25?1.08:1))));const questionIds=relevant.length?Array.from({length:Math.min(qTarget,30)},(_,j)=>relevant[(i*7+j)%relevant.length].id):[];const mock=mockPlan(model.examId,i+1,hours.mock,phase,closeToExam,weeklyHours);const sessionPlan=buildSessions(hours,topic,qTarget,mock.label);const totalMinutes=Math.round(weeklyHours*60);const measuredMinutes=sessionPlan.reduce((s,x)=>s+x.minutes,0);if(sessionPlan.length)sessionPlan[sessionPlan.length-1].minutes=Math.max(10,sessionPlan[sessionPlan.length-1].minutes+(totalMinutes-measuredMinutes));
    const accuracyText=p.accuracy==null?'ainda sem amostra suficiente de questões':`acerto recente de ${Math.round(p.accuracy*100)}% nas questões desta área`;
    const rationale=p.metric.unit==='acertos'?`Você está em ${p.current}/${p.metric.max}, com meta ${p.goal}. Como faltam ${p.missing} acertos e há ${accuracyText}, esta área recebe prioridade proporcional — sem aumentar suas ${weeklyHours}h semanais.`:`Seu resultado atual é ${p.current}/${p.metric.max}, meta ${p.goal}; ${accuracyText}. Esta semana concentra prática aqui sem ultrapassar seu tempo disponível.`;
    const activities=sessionPlan.map(s=>`${s.label}: ${s.task} (${s.minutes} min)`);const target=activities.join(' • ');const nextGoal=p.metric.unit==='acertos'?Math.min(p.goal,p.current+Math.max(1,Math.ceil(p.missing/3))):p.goal;const checkpoint=p.metric.unit==='acertos'?`Fechar a semana com ${qTarget} questões corrigidas + ${mock.label}; no próximo bloco, buscar pelo menos ${nextGoal}/${p.metric.max}.`:`Fechar as quatro etapas e registrar o resultado do bloco de medição para recalibrar a semana seguinte.`;
    const successCriteria=[`Cumprir ${qTarget} questões com correção, não apenas marcar respostas.`,`Refazer os erros principais sem consultar a resolução.`,`Concluir o bloco de medição: ${mock.label}.`,`Manter o total em ${weeklyHours}h; nada desta semana é “extra” fora do seu orçamento de tempo.`];
    weeks.push({week:i+1,start:isoDate(ws),end:isoDate(we),phase,focusKey:baseKey,focusLabel:p.metric.label,topic,target,hours:weeklyHours,questionTarget:qTarget,questionIds,videoTitle:`Aula dirigida: ${topic}`,videoChannel:channelFor(baseKey),videoUrl:ytUrl(baseKey,topic,model.examId,course),videoEmbedUrl:curatedEmbed(baseKey,topic),checkpoint,activities,mockExam:mock.label,mockQuestions:mock.q,hourBreakdown:{content:hours.content,questions:hours.questions,review:hours.review,mock:hours.mock},rationale,evidenceLabel:`Prioridade calculada por distância até a meta${p.accuracy==null?'':' + desempenho recente'}`,sessionPlan,successCriteria,totalPlannedMinutes:totalMinutes});
  }
  return{weeks,milestones,finalDate:isoDate(finalDate),daysLeft:Math.max(0,Math.ceil((finalDate.getTime()-startToday.getTime())/day)),dateLabel:`${fmt(milestones[0].date)}${milestones.length>1?` → ${fmt(milestones[milestones.length-1].date)}`:''}`};
}
