export const COURSE_TO_AREA_ID: Record<string, string> = {
  'Administração': 'negocios-e-gestao',
  'Agronomia': 'agro-e-ciencias-da-vida',
  'Análise e Desenvolvimento de Sistemas': 'ads',
  'Arquitetura e Urbanismo': 'design-e-construcao',
  'Biomedicina': 'saude-e-laboratorio',
  'Ciência da Computação': 'tecnologia-e-ciencia',
  'Ciências Biológicas': 'biologia-e-ciencias-da-vida',
  'Ciências Contábeis': 'negocios-e-financas',
  'Ciências Econômicas': 'economia-e-financas',
  'Cinema e Audiovisual': 'cinema-e-audiovisual',
  'Design': 'criacao-e-produto',
  'Direito': 'humanidades-e-juridico',
  'Educação Física': 'saude-e-esporte',
  'Enfermagem': 'enfermagem',
  'Engenharia Ambiental': 'engenharia-ambiental-e-sustentabilidade',
  'Engenharia Civil': 'engenharia',
  'Engenharia de Alimentos': 'engenharia-de-alimentos',
  'Engenharia de Computação': 'engenharia-de-computacao',
  'Engenharia de Produção': 'engenharia-e-gestao',
  'Engenharia de Software': 'engenharia-de-software',
  'Engenharia Elétrica': 'engenharia-e-tecnologia',
  'Engenharia Mecânica': 'engenharia-mecanica',
  'Engenharia Química': 'engenharia-quimica-e-processos',
  'Farmácia': 'saude-e-quimica',
  'Física': 'fisica-e-ciencia-fundamental',
  'Fisioterapia': 'fisioterapia',
  'Fonoaudiologia': 'fonoaudiologia-e-comunicacao-humana',
  'Gastronomia': 'gastronomia-e-hospitalidade',
  'Geografia': 'geografia-e-territorio',
  'Gestão de Recursos Humanos': 'gestao-de-pessoas',
  'História': 'historia-e-sociedade',
  'Jornalismo': 'comunicacao',
  'Letras': 'linguagem-e-literatura',
  'Logística': 'logistica-e-supply-chain',
  'Marketing': 'marketing-e-growth',
  'Matemática': 'matematica-e-modelagem',
  'Medicina': 'saude',
  'Medicina Veterinária': 'saude-biologicas-e-agro',
  'Moda': 'moda-e-industria-criativa',
  'Nutrição': 'nutricao',
  'Odontologia': 'odontologia',
  'Pedagogia': 'educacao',
  'Psicologia': 'saude-e-ciencias-humanas',
  'Publicidade e Propaganda': 'comunicacao-e-marketing',
  'Química': 'quimica-e-ciencias-moleculares',
  'Relações Internacionais': 'humanidades-politica-e-negocios',
  'Relações Públicas': 'relacoes-publicas-e-reputacao',
  'Serviço Social': 'ciencias-sociais-aplicadas',
  'Sistemas de Informação': 'tecnologia',
  'Terapia Ocupacional': 'terapia-ocupacional-e-reabilitacao',
};
