import { useEffect, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, CalendarDays, Compass, FileText, GraduationCap, PlayCircle, Target } from 'lucide-react';
import AreaMatchPortal from '@/components/AreaMatchPortal';

const HERO_PHOTO='https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1600&q=86';
const CAMPUS_PHOTO='https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=84';
const STUDY_PHOTO='https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=84';

function ConectaeLogo({compact=false}:{compact?:boolean}){
  return <div className="flex items-center gap-3" aria-label="Conectaê">
    <svg viewBox="0 0 48 48" className={compact?'h-9 w-9':'h-10 w-10'} role="img" aria-hidden="true">
      <defs><linearGradient id="cx" x1="7" y1="8" x2="42" y2="40"><stop stopColor="#4B8CFF"/><stop offset="1" stopColor="#1E61FF"/></linearGradient></defs>
      <path d="M34 12.2A16 16 0 1 0 34.2 35.6" fill="none" stroke="url(#cx)" strokeWidth="6" strokeLinecap="round"/>
      <circle cx="8.7" cy="15.8" r="2.2" fill="#5C98FF"/><circle cx="6.8" cy="24" r="2" fill="#246CFF"/><circle cx="9.6" cy="32" r="1.7" fill="#8BB8FF"/>
      <path d="M20.8 18.2 31.5 24l-10.7 5.8Z" fill="#fff"/>
    </svg>
    <span className={compact?'text-xl font-extrabold tracking-[-0.035em] text-white':'text-2xl font-extrabold tracking-[-0.04em] text-white'}>Conectaê</span>
  </div>;
}

export default function ExpandedHomeMount(){
  const[openAreas,setOpenAreas]=useState(false);const[initialAreaId,setInitialAreaId]=useState<string|null>(null);const params=new URLSearchParams(window.location.search);const legacy=params.get('modo')==='business';
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{areaId?:string}>).detail;setInitialAreaId(detail?.areaId??null);setOpenAreas(true)};window.addEventListener('conectae:open-area-match',handler);return()=>window.removeEventListener('conectae:open-area-match',handler)},[]);
  const closeAreas=()=>{setOpenAreas(false);setInitialAreaId(null)};
  const openPlanner=()=>{const url=new URL(window.location.href);url.searchParams.set('planner','aprovacao');window.location.assign(`${url.pathname}${url.search}${url.hash}`)};
  if(legacy)return null;if(openAreas)return <div className="fixed inset-0 z-[90] overflow-y-auto"><AreaMatchPortal onClose={closeAreas} initialAreaId={initialAreaId}/></div>;
  return <div className="fixed inset-0 z-[80] overflow-y-auto bg-[#020817] text-white selection:bg-[#246cff]/35">
    <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute -top-48 left-[18%] h-[430px] w-[430px] rounded-full bg-[#246cff]/[0.10] blur-[140px]"/><div className="absolute top-[32%] right-[4%] h-[320px] w-[320px] rounded-full bg-[#1749a3]/[0.10] blur-[120px]"/></div>
    <nav className="relative z-20 border-b border-[#80aef0]/[0.14] bg-[#020817]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1380px] items-center justify-between px-5 py-4 md:px-10"><ConectaeLogo compact/><div className="hidden text-sm font-medium text-[#8ea9cf] sm:block">Escolha melhor. Prepare-se melhor.</div></div></nav>
    <main className="relative z-10 mx-auto max-w-[1260px] px-5 pb-24 md:px-8">
      <section className="grid items-center gap-12 pt-12 md:pt-16 lg:grid-cols-[1.04fr_.96fr] lg:gap-16 lg:pt-20">
        <div><div className="mb-5 text-sm font-bold text-[#6fa0f6]">Do curso à aprovação</div><h1 className="mb-6 max-w-[760px] text-[46px] font-extrabold leading-[.99] tracking-[-0.055em] text-white sm:text-6xl lg:text-[72px]">Descubra onde entrar. <span className="text-[#77a6fa]">E como chegar lá.</span></h1><p className="mb-8 max-w-2xl text-lg leading-relaxed text-[#a9bddc] md:text-xl">Compare faculdades, entenda o seu perfil e transforme uma meta de aprovação em um plano de estudo que acompanha sua evolução.</p>
          <div className="mb-9 flex flex-wrap gap-x-6 gap-y-2 border-y border-[#80aef0]/[0.13] py-4 text-sm text-[#8ea6c8]"><span><b className="text-white">50</b> cursos</span><span><b className="text-white">1.000+</b> opções</span><span><b className="text-white">200+</b> questões no plano</span><span><b className="text-white">5</b> provas com lógica própria</span></div>
          <div className="grid max-w-3xl gap-3 sm:grid-cols-2">
            <button className="group rounded-[18px] border border-[#78a9ef]/[0.16] bg-[#07162f] p-6 text-left transition hover:border-[#4b8cff]/50 hover:bg-[#092047]"><div className="mb-5 flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-[11px] bg-[#0e2d60] text-[#7eb0ff]"><Compass className="h-5 w-5"/></div><ArrowRight className="h-4 w-4 text-[#6f88ac] transition-transform group-hover:translate-x-0.5"/></div><div className="mb-1.5 text-xs font-bold text-[#6fa0f6]">Ainda explorando</div><h2 className="mb-2 text-2xl font-extrabold tracking-[-0.035em]">Fazer teste vocacional</h2><p className="text-sm leading-relaxed text-[#91a7c7]">48 perguntas para entender interesses, habilidades e ambientes em que você tende a render melhor.</p></button>
            <button onClick={()=>{setInitialAreaId(null);setOpenAreas(true)}} className="group rounded-[18px] border border-[#78a9ef]/[0.16] bg-[#07162f] p-6 text-left transition hover:border-[#4b8cff]/50 hover:bg-[#092047]"><div className="mb-5 flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-[11px] bg-[#0e2d60] text-[#7eb0ff]"><GraduationCap className="h-5 w-5"/></div><ArrowRight className="h-4 w-4 text-[#6f88ac] transition-transform group-hover:translate-x-0.5"/></div><div className="mb-1.5 text-xs font-bold text-[#6fa0f6]">Já sabe o curso</div><h2 className="mb-2 text-2xl font-extrabold tracking-[-0.035em]">Encontrar minha faculdade</h2><p className="text-sm leading-relaxed text-[#91a7c7]">Compare faculdades pelo seu perfil acadêmico, ambiente, metodologia e objetivos de carreira.</p></button>
          </div>
        </div>
        <div className="relative min-h-[430px] md:min-h-[540px]"><div className="absolute left-0 top-0 h-[82%] w-[79%] overflow-hidden rounded-[20px] border border-[#7aa9ec]/[0.15] shadow-2xl"><img src={HERO_PHOTO} alt="Estudantes universitários" className="h-full w-full object-cover" referrerPolicy="no-referrer"/><div className="absolute inset-0 bg-gradient-to-t from-[#020817]/80 via-[#020817]/10 to-transparent"/></div><div className="absolute right-0 top-[18%] h-[31%] w-[43%] overflow-hidden rounded-[16px] border-[5px] border-[#020817] shadow-2xl"><img src={CAMPUS_PHOTO} alt="Campus universitário" className="h-full w-full object-cover"/></div><div className="absolute bottom-[2%] right-[7%] h-[31%] w-[49%] overflow-hidden rounded-[16px] border-[5px] border-[#020817] shadow-2xl"><img src={STUDY_PHOTO} alt="Estudo para vestibular" className="h-full w-full object-cover"/></div></div>
      </section>
      <section className="mt-16"><button onClick={openPlanner} className="group w-full overflow-hidden rounded-[20px] border border-[#80aef0]/[0.16] bg-gradient-to-br from-[#081b3a] to-[#06142e] p-6 text-left transition hover:border-[#4b8cff]/45 md:p-9"><div className="grid items-center gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold text-[#68a0ff]"><Target className="h-4 w-4"/>Plano de Aprovação</div><h2 className="text-3xl font-extrabold tracking-[-0.045em] md:text-5xl">Já sabe onde quer entrar? Veja <span className="text-[#78a8ff]">o que fazer a cada semana.</span></h2><p className="mt-4 max-w-3xl text-base leading-relaxed text-[#a8bad6] md:text-lg">O plano cruza seu curso, faculdade, simulados, matérias fortes e histórico de questões para organizar o que merece mais tempo agora.</p><div className="mt-6 inline-flex items-center gap-2 rounded-[12px] bg-[#246cff] px-5 py-3.5 font-extrabold text-white">Montar meu plano <ArrowRight className="h-4.5 w-4.5"/></div></div><div className="grid gap-x-7 gap-y-5 sm:grid-cols-2">{[
          {icon:<CalendarDays className="h-4.5 w-4.5"/>,title:'Plano semanal',text:'Prioridades, checkpoints e simulados distribuídos até a prova.'},{icon:<BookOpen className="h-4.5 w-4.5"/>,title:'Questões no site',text:'Prática por prova e área com gabarito e explicação.'},{icon:<PlayCircle className="h-4.5 w-4.5"/>,title:'Provas oficiais',text:'Blocos de ENEM de anos diferentes no ritmo da semana.'},{icon:<FileText className="h-4.5 w-4.5"/>,title:'PDF semanal',text:'Roteiro, questões e material para estudar offline.'}
        ].map(card=><div key={card.title} className="border-t border-[#80aef0]/[0.14] pt-4"><div className="mb-2 flex items-center gap-2 text-[#6fa0f6]">{card.icon}<strong className="text-sm text-white">{card.title}</strong></div><p className="text-xs leading-relaxed text-[#8ea6c8]">{card.text}</p></div>)}</div></div></button></section>
      <section className="mt-16 grid gap-4 md:grid-cols-3">{[{icon:<Target className="h-4.5 w-4.5"/>,label:'Fit com você',text:'Compare sem transformar uma escolha complexa em um ranking simplista.'},{icon:<BarChart3 className="h-4.5 w-4.5"/>,label:'Metas visíveis',text:'Entenda onde está, para onde precisa ir e qual área merece prioridade.'},{icon:<BookOpen className="h-4.5 w-4.5"/>,label:'Preparação real',text:'ENEM, FUVEST, Insper, Link e Ciências Médicas recebem lógica própria.'}].map(card=><div key={card.label} className="rounded-[16px] border border-[#80aef0]/[0.13] bg-[#06142e] p-5"><div className="mb-3 text-[#6fa0f6]">{card.icon}</div><h3 className="text-xl font-extrabold tracking-[-0.03em]">{card.label}</h3><p className="mt-2 text-sm leading-relaxed text-[#8ea6c8]">{card.text}</p></div>)}</section>
    </main>
  </div>;
}
