import type { ExamSkillCatalog, SkillSubject } from '@/lib/exam-skill-catalog';

const DETAIL:Record<string,string[]>={
 'língua portuguesa':['Interpretação literal','Inferência e implícitos','Finalidade e função do texto','Tipologia textual','Gêneros textuais','Coesão referencial','Coesão sequencial','Coerência global','Conectivos e relações lógicas','Semântica lexical','Ambiguidade e polissemia','Figuras de linguagem','Variação linguística','Adequação de registro','Classes de palavras','Formação de palavras','Sintaxe do período simples','Orações coordenadas','Orações subordinadas','Concordância verbal e nominal','Regência verbal e nominal','Crase','Pontuação e vírgula','Colocação pronominal','Intertextualidade','Linguagem verbal, não verbal e multimodal','Argumentação, tese e estratégias persuasivas'],
 'português':['Interpretação literal','Inferência e implícitos','Finalidade e função do texto','Tipologia textual','Gêneros textuais','Coesão referencial','Coesão sequencial','Coerência global','Conectivos e relações lógicas','Semântica lexical','Ambiguidade e polissemia','Figuras de linguagem','Variação linguística','Adequação de registro','Classes de palavras','Formação de palavras','Sintaxe do período simples','Orações coordenadas','Orações subordinadas','Concordância verbal e nominal','Regência verbal e nominal','Crase','Pontuação e vírgula','Colocação pronominal','Intertextualidade','Linguagem verbal, não verbal e multimodal','Argumentação, tese e estratégias persuasivas'],
 'literatura':['Trovadorismo e Humanismo','Classicismo','Barroco','Arcadismo','Romantismo','Realismo e Naturalismo','Parnasianismo','Simbolismo','Pré-Modernismo','Modernismo: 1ª fase','Modernismo: 2ª fase','Modernismo: 3ª fase e contemporaneidade','Análise de poesia','Narrador e foco narrativo','Personagens, tempo e espaço','Intertextualidade literária','Contexto histórico e escola literária','Obras obrigatórias e leitura comparada'],
 'história':['Antiguidade oriental','Grécia e Roma','Feudalismo e Idade Média','Renascimento e Reformas','Absolutismo e mercantilismo','Iluminismo','Revolução Inglesa','Revolução Francesa','Revolução Industrial','Independências americanas','Imperialismo e neocolonialismo','Primeira Guerra Mundial','Revolução Russa','Crise de 1929 e fascismos','Segunda Guerra Mundial','Guerra Fria','Descolonização','Brasil pré-colonial e colonial','Escravidão e resistências','Mineração e sociedade colonial','Independência do Brasil','Primeiro Reinado e Regências','Segundo Reinado','Abolição e crise do Império','República Oligárquica','Era Vargas','República de 1946','Ditadura militar','Redemocratização e Nova República','Movimentos sociais e cidadania'],
 'geografia':['Escala e projeções cartográficas','Coordenadas e fusos horários','Leitura de mapas e geotecnologias','Estrutura geológica e relevo','Climatologia','Hidrografia','Solos','Biomas brasileiros','Problemas ambientais','Mudanças climáticas','Demografia','Migrações','Urbanização e rede urbana','Segregação socioespacial','Industrialização','Fontes de energia','Transportes e infraestrutura','Agropecuária e estrutura fundiária','Questão agrária','Globalização','Blocos econômicos','Geopolítica mundial','Conflitos contemporâneos','Regionalização do Brasil','Economia brasileira','Comércio internacional'],
 'filosofia':['Pré-socráticos','Sócrates, Platão e Aristóteles','Helenismo','Filosofia medieval','Racionalismo','Empirismo','Iluminismo','Kant','Ética','Filosofia política','Contrato social','Teoria do conhecimento','Filosofia da ciência','Marx','Nietzsche','Existencialismo e contemporaneidade'],
 'sociologia':['Socialização','Cultura e etnocentrismo','Identidade','Instituições sociais','Trabalho','Divisão social do trabalho','Classes e estratificação','Desigualdade social','Raça e racismo','Gênero e sociedade','Poder e dominação','Estado','Cidadania','Democracia','Movimentos sociais','Mídia e indústria cultural','Tecnologia e sociedade','Globalização e transformações sociais'],
 'biologia':['Bioquímica celular','Membrana plasmática e transportes','Organelas','Respiração celular','Fotossíntese','Mitose e meiose','DNA e RNA','Síntese proteica','Genética mendeliana','Heredogramas','Grupos sanguíneos','Linkage e recombinação','Mutações','Biotecnologia e CRISPR','Evolução e seleção natural','Especiação','Ecologia de populações','Relações ecológicas','Cadeias e teias alimentares','Ciclos biogeoquímicos','Sucessão ecológica','Impactos ambientais','Sistema digestório','Sistema respiratório','Sistema circulatório','Sistema excretor','Sistema nervoso','Sistema endócrino','Imunologia','Vírus, bactérias e doenças','Botânica: fisiologia vegetal','Botânica: reprodução e grupos','Zoologia e classificação'],
 'química':['Modelos atômicos','Distribuição eletrônica','Tabela periódica','Ligações iônica, covalente e metálica','Geometria molecular','Polaridade','Forças intermoleculares','Funções inorgânicas','Reações químicas','Balanceamento','Mol e massa molar','Estequiometria','Gases','Soluções e concentração','Diluição e mistura de soluções','Termoquímica','Cinética química','Equilíbrio químico','Equilíbrio iônico','Ácidos e bases','pH e pOH','Hidrólise e tampões','Oxirredução','Pilhas','Eletrólise','Funções orgânicas','Isomeria','Reações orgânicas','Polímeros','Química ambiental'],
 'física':['Grandezas, unidades e análise dimensional','Cinemática escalar','MRU','MRUV','Gráficos do movimento','Vetores','Leis de Newton','Força de atrito','Plano inclinado','Movimento circular','Trabalho','Energia mecânica','Potência e rendimento','Impulso e quantidade de movimento','Colisões','Gravitação','Hidrostática','Temperatura e calorimetria','Dilatação térmica','Gases e termodinâmica','Ondas','Acústica','Óptica geométrica','Espelhos','Lentes','Eletrostática','Campo e potencial elétrico','Corrente e resistência','Circuitos elétricos','Potência elétrica','Magnetismo','Indução eletromagnética'],
 'matemática':['Operações e conjuntos numéricos','Razão e proporção','Regra de três','Porcentagem','Juros simples e compostos','Equações do 1º grau','Equações do 2º grau','Inequações','Sistemas lineares','Função afim','Função quadrática','Função exponencial','Logaritmos','Função logarítmica','PA','PG','Matrizes e determinantes','Princípio fundamental da contagem','Permutações, arranjos e combinações','Probabilidade simples','Probabilidade condicional','Média, mediana e moda','Variância e desvio padrão','Leitura de tabelas e gráficos','Geometria plana','Semelhança de triângulos','Teorema de Pitágoras','Áreas e perímetros','Geometria espacial','Volumes e áreas de sólidos','Geometria analítica','Distância e ponto médio','Equação da reta','Circunferência','Trigonometria no triângulo','Ciclo trigonométrico'],
 'redação':['Interpretação do tema','Delimitação do recorte','Formulação da tese','Projeto de texto','Introdução','Tópico frasal','Desenvolvimento de argumento','Uso de repertório','Exemplificação e evidências','Contra-argumentação','Coesão entre frases','Coesão entre parágrafos','Conclusão','Norma-padrão','Pontuação aplicada à redação','Precisão vocabular','Revisão e reescrita','Proposta de intervenção: agente','Proposta de intervenção: ação','Proposta de intervenção: meio/modo','Proposta de intervenção: finalidade e detalhamento'],
 'inglês':['Compreensão global','Localização de informação explícita','Inferência','Vocabulário em contexto','Falsos cognatos','Pronomes e referenciação','Conectivos','Tempos verbais em contexto','Modal verbs','Voz passiva','Intenção comunicativa','Aspectos culturais'],
 'business case':['Definição do problema','Separação causa x sintoma','Árvore de problemas','Hipóteses','Priorização 80/20','Segmentação de clientes','Tamanho de mercado','Concorrência','Posicionamento','Receita','Custos fixos e variáveis','Margem','Break-even','Unit economics','Leitura de dados','Construção de KPI','Trade-offs','Análise de riscos','Experimentos','Plano de implementação','Recomendação executiva'],
 'entrevista':['Apresentação pessoal','Why Link / motivação','Por que business','Metas de carreira','Liderança','Trabalho em equipe','Conflito','Fracasso e aprendizado','Feedback','Iniciativa','Impacto mensurável','Ética','Autoconhecimento','Resposta STAR','Perguntas ao entrevistador'],
 'portfólio':['Seleção de experiências','Evidências acadêmicas','Projetos autorais','Liderança','Empreendedorismo','Impacto social','Resultados mensuráveis','Premiações','Aprendizados','Coerência da trajetória','Curadoria e ordem das evidências'],
 'oral':['Estrutura de roteiro','Gancho inicial','Storytelling','Clareza e objetividade','Dicção','Ritmo','Linguagem corporal','Gestão do tempo','Defesa de escolhas','Resposta a objeções'],
 'escrita':['Síntese executiva','Resposta ao comando','Estrutura lógica','Argumentação com dados','Priorização','Riscos','Próximos passos','Clareza e concisão']
};

function normalize(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function detailFor(subject:string){const n=normalize(subject);for(const [key,topics] of Object.entries(DETAIL))if(n.includes(normalize(key)))return topics;return[]}
function dedupe(xs:string[]){return Array.from(new Set(xs.map(x=>x.trim()).filter(Boolean)))}

export function expandStudyCatalog(catalog:ExamSkillCatalog):ExamSkillCatalog{
 const subjects:SkillSubject[]=catalog.subjects.map(s=>({...s,topics:dedupe([...s.topics,...detailFor(s.subject)])}));
 return {...catalog,subjects};
}

export function countGranularTopics(catalog:ExamSkillCatalog){return expandStudyCatalog(catalog).subjects.reduce((n,s)=>n+s.topics.length,0)}
