export type InterviewActivity = {
  id: string;
  category: 'Inglês' | 'Coragem' | 'Capacidade de trabalho' | 'Vontade de estar aqui';
  title: string;
  question: string;
  target: string;
  language: 'pt' | 'en';
};

export const interviewActivities: InterviewActivity[] = [
  {
    id: 'english-1',
    category: 'Inglês',
    title: 'Sua trajetória em inglês',
    question: 'Tell me about one experience that changed the way you think about business or entrepreneurship. What did you actually do?',
    target: 'Responda em inglês em até 90 segundos. Priorize fluidez, estrutura e exemplos concretos.',
    language: 'en',
  },
  {
    id: 'english-2',
    category: 'Inglês',
    title: 'Defenda uma escolha',
    question: 'Describe a difficult decision you made with incomplete information. What options did you consider, and why did you choose that path?',
    target: 'Responda em inglês em até 90 segundos. Explique alternativas, decisão e consequência.',
    language: 'en',
  },
  {
    id: 'english-3',
    category: 'Inglês',
    title: 'Why Link?',
    question: 'Why Link School of Business specifically? Give me two reasons that would not apply equally well to most business schools.',
    target: 'Responda em inglês em até 60 segundos. Evite argumentos genéricos.',
    language: 'en',
  },
  {
    id: 'english-4',
    category: 'Inglês',
    title: 'Follow-up sob pressão',
    question: 'I am not convinced by your answer. What evidence from your own experience supports the position you just defended?',
    target: 'Responda em inglês em até 60 segundos. Sustente sua posição sem repetir a resposta anterior.',
    language: 'en',
  },
  {
    id: 'english-5',
    category: 'Inglês',
    title: 'Erro e aprendizado',
    question: 'Tell me about a mistake that was genuinely your responsibility. What changed in your behavior afterward?',
    target: 'Responda em inglês em até 90 segundos. Assuma responsabilidade e mostre mudança verificável.',
    language: 'en',
  },
  {
    id: 'english-6',
    category: 'Inglês',
    title: 'Ambição e próximos passos',
    question: 'What do you want to build or achieve in the next few years, and what is the next concrete step you will take?',
    target: 'Responda em inglês em até 60 segundos. Seja específico e direto.',
    language: 'en',
  },
  {
    id: 'courage-1',
    category: 'Coragem',
    title: 'Defender uma ideia',
    question: 'Conte uma situação em que alguém relevante discordou de você. Qual posição você assumiu, como a defendeu e o que aconteceu depois?',
    target: 'Responda em até 90 segundos. Mostre posicionamento e como lidou com o desconforto.',
    language: 'pt',
  },
  {
    id: 'courage-2',
    category: 'Coragem',
    title: 'Decisão impopular',
    question: 'Qual foi uma decisão sua que poderia desagradar outras pessoas, mas que você decidiu sustentar mesmo assim? Por quê?',
    target: 'Responda em até 90 segundos. Explique risco, raciocínio e responsabilidade.',
    language: 'pt',
  },
  {
    id: 'courage-3',
    category: 'Coragem',
    title: 'Pergunta desconfortável',
    question: 'Qual é a crítica mais justa que alguém poderia fazer sobre uma escolha importante sua? O que nessa crítica você aceita e o que você contesta?',
    target: 'Responda em até 60 segundos. Não tente parecer perfeito.',
    language: 'pt',
  },
  {
    id: 'courage-4',
    category: 'Coragem',
    title: 'Objeção do entrevistador',
    question: 'Eu acho que sua decisão foi precipitada e que você teve sorte no resultado. Por que eu deveria interpretar a situação de outra forma?',
    target: 'Responda em até 60 segundos. Reconheça a objeção e defenda sua leitura com evidências.',
    language: 'pt',
  },
  {
    id: 'courage-5',
    category: 'Coragem',
    title: 'Risco real',
    question: 'Conte uma situação em que você realmente colocou algo em risco para tentar fazer uma ideia acontecer. O que poderia dar errado?',
    target: 'Responda em até 90 segundos. Diferencie risco real de simples dificuldade.',
    language: 'pt',
  },
  {
    id: 'courage-6',
    category: 'Coragem',
    title: 'Mudar de posição',
    question: 'Conte uma vez em que você defendeu uma ideia e depois percebeu que estava errado. O que fez você mudar de posição?',
    target: 'Responda em até 90 segundos. Coragem também inclui rever uma posição com evidências.',
    language: 'pt',
  },
  {
    id: 'work-1',
    category: 'Capacidade de trabalho',
    title: 'Disciplina por meses',
    question: 'Qual projeto exigiu de você mais consistência por um período longo? O que você fazia mesmo nos dias em que a motivação diminuía?',
    target: 'Responda em até 90 segundos. Dê evidências concretas de rotina, esforço e entrega.',
    language: 'pt',
  },
  {
    id: 'work-2',
    category: 'Capacidade de trabalho',
    title: 'Sua entrega específica',
    question: 'Escolha um projeto importante do seu portfólio. O que foi exclusivamente responsabilidade sua e qual entrega concreta ficou pronta por causa do seu trabalho?',
    target: 'Responda em até 90 segundos. Separe claramente seu papel do resultado do grupo.',
    language: 'pt',
  },
  {
    id: 'work-3',
    category: 'Capacidade de trabalho',
    title: 'Prazo apertado',
    question: 'Conte uma situação em que o prazo era curto e o volume de trabalho era alto. Como você organizou prioridades e o que conseguiu entregar?',
    target: 'Responda em até 90 segundos. Mostre método, escolhas e execução.',
    language: 'pt',
  },
  {
    id: 'work-4',
    category: 'Capacidade de trabalho',
    title: 'Quando o plano falhou',
    question: 'Quando uma estratégia sua não funcionou, como você reorganizou o trabalho e continuou avançando sem simplesmente abandonar o objetivo?',
    target: 'Responda em até 90 segundos. Mostre persistência com adaptação, não teimosia.',
    language: 'pt',
  },
  {
    id: 'work-5',
    category: 'Capacidade de trabalho',
    title: 'Business Case',
    question: 'Pensando no seu Business Case ou em outro desafio de execução rápida: o que você fez nas primeiras horas, o que mudou depois e qual evidência mostra evolução?',
    target: 'Responda em até 90 segundos. Foque em ação, evolução e entrega.',
    language: 'pt',
  },
  {
    id: 'work-6',
    category: 'Capacidade de trabalho',
    title: 'Esforço invisível',
    question: 'Qual resultado seu parece simples quando visto de fora, mas exigiu muito mais trabalho do que as pessoas imaginam?',
    target: 'Responda em até 60 segundos. Torne o esforço concreto sem exagerar.',
    language: 'pt',
  },
  {
    id: 'fit-1',
    category: 'Vontade de estar aqui',
    title: 'Por que Link, especificamente?',
    question: 'Por que a Link School of Business e não apenas qualquer faculdade de negócios? Cite aspectos específicos e conecte cada um à sua trajetória.',
    target: 'Responda em até 90 segundos. Evite frases que poderiam servir para qualquer faculdade.',
    language: 'pt',
  },
  {
    id: 'fit-2',
    category: 'Vontade de estar aqui',
    title: 'Metodologia prática',
    question: 'O que você espera fazer na Link que combina com a forma como você aprende melhor? Dê um exemplo anterior que sustente essa resposta.',
    target: 'Responda em até 90 segundos. Conecte a proposta da Link a evidências da sua trajetória.',
    language: 'pt',
  },
  {
    id: 'fit-3',
    category: 'Vontade de estar aqui',
    title: 'Consistência com o PREP',
    question: 'Se eu comparar esta resposta com seu vídeo do PREP, o que deveria aparecer de forma consistente sobre sua motivação e seus objetivos?',
    target: 'Responda em até 60 segundos. Mostre coerência sem repetir um discurso decorado.',
    language: 'pt',
  },
  {
    id: 'fit-4',
    category: 'Vontade de estar aqui',
    title: 'Contribuição para a comunidade',
    question: 'O que você pretende acrescentar à comunidade da Link no primeiro ano? Conecte sua resposta a algo que você já fez.',
    target: 'Responda em até 90 segundos. Traga uma contribuição viável e sustentada por histórico.',
    language: 'pt',
  },
  {
    id: 'fit-5',
    category: 'Vontade de estar aqui',
    title: 'Além de empreendedorismo',
    question: 'Dizer que você gosta de empreendedorismo ainda é genérico. O que na experiência da Link faz sentido para você de um jeito mais específico?',
    target: 'Responda em até 60 segundos. Aprofunde além do nome do curso ou da reputação.',
    language: 'pt',
  },
  {
    id: 'fit-6',
    category: 'Vontade de estar aqui',
    title: 'Coerência de futuro',
    question: 'Que objetivo seu hoje seria mais difícil de perseguir sem a formação que você espera encontrar na Link? Por quê?',
    target: 'Responda em até 90 segundos. Conecte objetivo, lacuna atual e escolha da instituição.',
    language: 'pt',
  },
];
