import { jsPDF } from 'jspdf';

export type StudyPdfQuestion={area:string;skill_name:string;difficulty:number;prompt:string;option_a:string|null;option_b:string|null;option_c:string|null;option_d:string|null;option_e:string|null;correct_option:string|null;explanation:string|null};
export type OfficialPractice={year:number;day:string;focus:string;range:string;duration:string;url:string};
export type StudyPdfWeek={week:number;phase:string;focus:string;secondary:string;hours:number;checkpoint:string;skills:string[];tasks:string[];questions:StudyPdfQuestion[];officialPractice?:OfficialPractice|null;simulation?:{label:string;duration:string;instructions:string}|null};
type Args={course:string;university:string;exam:string;readiness:number;weeklyHours:number;weeks:StudyPdfWeek[];singleWeek?:number};

const INK:[number,number,number]=[24,26,23];const GREEN:[number,number,number]=[15,92,73];const CREAM:[number,number,number]=[247,245,239];const PAPER:[number,number,number]=[255,254,250];const MUTED:[number,number,number]=[102,106,99];const LINE:[number,number,number]=[222,220,212];const ORANGE:[number,number,number]=[200,92,56];
function lines(doc:jsPDF,text:string,width:number){return doc.splitTextToSize((text||'').replace(/\s+/g,' ').trim(),width) as string[]}
function header(doc:jsPDF,label:string){doc.setFillColor(...PAPER);doc.rect(0,0,210,18,'F');doc.setDrawColor(...LINE);doc.line(14,18,196,18);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...GREEN);doc.text('CONECTAÊ',14,11);doc.setFont('helvetica','normal');doc.setTextColor(...MUTED);doc.text(label,196,11,{align:'right'});}
function footer(doc:jsPDF,page:number){doc.setDrawColor(...LINE);doc.line(14,282,196,282);doc.setFontSize(7.5);doc.setTextColor(...MUTED);doc.text('Plano pessoal de estudo • ajuste após cada simulado',14,289);doc.text(String(page),196,289,{align:'right'});}
function tag(doc:jsPDF,x:number,y:number,text:string,fill:[number,number,number]=GREEN){doc.setFontSize(7.5);doc.setFont('helvetica','bold');const w=Math.min(62,Math.max(25,doc.getTextWidth(text)+10));doc.setFillColor(...fill);doc.roundedRect(x,y-5,w,8,3,3,'F');doc.setTextColor(255,255,255);doc.text(text,x+5,y);return w;}
function subjectVisual(doc:jsPDF,area:string,x:number,y:number,w=45,h=28){const a=area.toLowerCase();doc.setFillColor(...CREAM);doc.setDrawColor(...LINE);doc.roundedRect(x,y,w,h,5,5,'FD');doc.setDrawColor(...GREEN);doc.setLineWidth(1.1);if(a.includes('mat')){doc.line(x+8,y+h-6,x+w-7,y+h-6);doc.line(x+9,y+h-5,x+9,y+6);let px=x+9,py=y+h-8;for(let i=1;i<27;i++){const nx=x+9+i,ny=y+h-8-(i*i)/42;doc.line(px,py,nx,ny);px=nx;py=ny;}}else if(a.includes('bio')||a.includes('natureza')){doc.ellipse(x+w/2,y+h/2,12,8);doc.circle(x+w/2,y+h/2,4,'S');doc.line(x+10,y+9,x+16,y+12);doc.line(x+29,y+16,x+36,y+21);}else if(a.includes('quim')){const pts=[[12,15],[20,8],[30,12],[31,21],[19,22]];pts.forEach(([dx,dy],i)=>{doc.circle(x+dx,y+dy,2,'S');const n=pts[(i+1)%pts.length];doc.line(x+dx+2,y+dy,x+n[0]-2,y+n[1]);});}else if(a.includes('fis')){for(let i=1;i<33;i++){const x1=x+6+i,y1=y+14+Math.sin(i/3)*5;const x0=x+5+i,y0=y+14+Math.sin((i-1)/3)*5;doc.line(x0,y0,x1,y1);}}else{doc.line(x+9,y+9,x+w-9,y+9);doc.line(x+9,y+14,x+w-13,y+14);doc.line(x+9,y+19,x+w-7,y+19);}}
function questionPage(doc:jsPDF,q:StudyPdfQuestion,index:number,week:number,page:number){doc.addPage();header(doc,`Semana ${week} • questão ${index+1}`);tag(doc,14,32,q.area);tag(doc,14,43,`nível ${q.difficulty}/5`,ORANGE);subjectVisual(doc,q.area,151,26);doc.setTextColor(...INK);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(lines(doc,q.skill_name,126),14,56);doc.setFont('helvetica','normal');doc.setFontSize(11);const p=lines(doc,`${index+1}. ${q.prompt}`,180);doc.text(p,14,70);let y=70+p.length*5.2+7;const opts:[string,string|null][]=[['A',q.option_a],['B',q.option_b],['C',q.option_c],['D',q.option_d],['E',q.option_e]];opts.filter(([,v])=>v).forEach(([letter,value])=>{const ls=lines(doc,`${letter}) ${value}`,169);const h=Math.max(10,ls.length*4.6+5);if(y+h>244){doc.setFontSize(8);doc.setTextColor(...MUTED);doc.text('Continue no verso se necessário.',14,249);return;}doc.setFillColor(...PAPER);doc.setDrawColor(...LINE);doc.roundedRect(14,y,182,h,3,3,'FD');doc.setTextColor(...INK);doc.setFontSize(9.5);doc.text(ls,19,y+6.5);y+=h+4;});doc.setTextColor(...MUTED);doc.setFontSize(8);doc.text('Rascunho / conta / justificativa',14,255);doc.setDrawColor(207,207,201);for(let yy=261;yy<=276;yy+=5)doc.line(14,yy,196,yy);footer(doc,page);}
function answerPage(doc:jsPDF,questions:StudyPdfQuestion[],week:number,page:number){doc.addPage();header(doc,`Semana ${week} • correção`);doc.setTextColor(...INK);doc.setFont('helvetica','bold');doc.setFontSize(22);doc.text('Gabarito comentado',14,34);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...MUTED);doc.text('Corrija depois de concluir o bloco. Marque o motivo do erro no seu caderno de erros.',14,42);let y=53;questions.forEach((q,i)=>{const answer=`${i+1}. ${q.correct_option?`Alternativa ${q.correct_option}. `:'Resposta aberta. '}${q.explanation||'Revise a habilidade indicada e refaça o raciocínio.'}`;const ls=lines(doc,answer,172);const h=11+ls.length*4.2;if(y+h>274){footer(doc,page++);doc.addPage();header(doc,`Semana ${week} • correção`);y=31;}doc.setFillColor(235,243,239);doc.setDrawColor(201,218,209);doc.roundedRect(14,y,182,h,4,4,'FD');doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(...GREEN);doc.text(q.area.toUpperCase(),19,y+7);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...INK);doc.text(ls,19,y+14);y+=h+5;});footer(doc,page);}

export function downloadStudyPlanPdfV6(args:Args){const doc=new jsPDF({unit:'mm',format:'a4'});const selected=args.singleWeek==null?args.weeks:args.weeks.filter(w=>w.week===args.singleWeek);let page=1;
  doc.setFillColor(...CREAM);doc.rect(0,0,210,297,'F');doc.setFillColor(...INK);doc.rect(0,0,210,88,'F');doc.setTextColor(194,225,212);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('CONECTAÊ • PLANO DE APROVAÇÃO',16,25);doc.setTextColor(255,255,255);doc.setFont('times','normal');doc.setFontSize(31);doc.text('Seu plano de estudo',16,46);doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text(lines(doc,`${args.course} • ${args.university}`,150),16,59);doc.setTextColor(215,218,212);doc.setFontSize(9);doc.text(args.exam,16,75);
  doc.setTextColor(...INK);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Ponto de partida',16,108);doc.setFont('times','normal');doc.setFontSize(37);doc.setTextColor(...GREEN);doc.text(`${args.readiness}%`,16,126);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...MUTED);doc.text('prontidão estimada agora',16,135);doc.setFillColor(...PAPER);doc.setDrawColor(...LINE);doc.roundedRect(92,101,102,43,5,5,'FD');doc.setTextColor(...INK);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('ROTINA',99,112);doc.setFont('times','normal');doc.setFontSize(24);doc.text(`${args.weeklyHours}h / semana`,99,128);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...MUTED);doc.text('Questões + teoria + correção + simulados',99,137);
  const intro=['Plano semanal com prioridades claras','Blocos de questões para resolver sem sair do Conectaê','Provas oficiais antigas quando fizer sentido','Simulados cronometrados e rotina de correção','Gabarito comentado no final de cada semana'];doc.setFontSize(9.5);doc.setTextColor(...INK);intro.forEach((t,i)=>{doc.setFillColor(...GREEN);doc.circle(19,165+i*12,1.5,'F');doc.text(t,25,168+i*12);});doc.setTextColor(...MUTED);doc.setFontSize(8);doc.text('Não é uma previsão de aprovação. É um roteiro ajustável conforme seu desempenho.',16,276);
  for(const w of selected){doc.addPage();page++;header(doc,`Semana ${w.week}`);doc.setTextColor(...INK);doc.setFont('times','normal');doc.setFontSize(29);doc.text(`Semana ${w.week}`,14,35);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...GREEN);doc.text(w.phase.toUpperCase(),14,44);subjectVisual(doc,w.focus,151,27);
    doc.setFillColor(...PAPER);doc.setDrawColor(...LINE);doc.roundedRect(14,53,182,38,5,5,'FD');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...MUTED);doc.text('FOCO DA SEMANA',20,63);doc.setFont('times','normal');doc.setFontSize(20);doc.setTextColor(...INK);doc.text(lines(doc,w.focus,112),20,75);doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(...MUTED);doc.text(`Secundário: ${w.secondary}  •  ${w.hours}h  •  ${w.checkpoint}`,20,84);
    let y=105;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...INK);doc.text('O que dominar',14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(8.8);doc.setTextColor(...MUTED);w.skills.slice(0,5).forEach(s=>{const ls=lines(doc,`• ${s}`,176);doc.text(ls,18,y);y+=ls.length*4.2+1;});y+=4;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...INK);doc.text('Roteiro',14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(8.8);doc.setTextColor(...MUTED);w.tasks.forEach(t=>{const ls=lines(doc,`□ ${t}`,176);doc.text(ls,18,y);y+=ls.length*4.2+2;});
    if(w.officialPractice){y=Math.max(y+3,190);doc.setFillColor(232,240,245);doc.setDrawColor(198,214,224);doc.roundedRect(14,y,182,37,5,5,'FD');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(40,91,122);doc.text(`PROVA OFICIAL ENEM ${w.officialPractice.year} • ${w.officialPractice.day}`,20,y+10);doc.setFont('helvetica','normal');doc.setTextColor(...INK);doc.setFontSize(8.5);doc.text(lines(doc,`${w.officialPractice.focus} • ${w.officialPractice.range} • ${w.officialPractice.duration}`,166),20,y+19);doc.setTextColor(40,91,122);doc.textWithLink('Abrir PDF oficial do Inep',20,y+30,{url:w.officialPractice.url});}
    if(w.simulation){const sy=w.officialPractice?239:217;doc.setFillColor(249,236,230);doc.setDrawColor(236,196,180);doc.roundedRect(14,sy,182,28,5,5,'FD');doc.setFont('helvetica','bold');doc.setTextColor(...ORANGE);doc.setFontSize(8.5);doc.text(`${w.simulation.label} • ${w.simulation.duration}`,20,sy+9);doc.setFont('helvetica','normal');doc.setTextColor(...INK);doc.setFontSize(8);doc.text(lines(doc,w.simulation.instructions,164),20,sy+18);}footer(doc,page);
    const qs=w.questions.slice(0,10);qs.forEach((q,i)=>{page++;questionPage(doc,q,i,w.week,page)});if(qs.length){page++;answerPage(doc,qs,w.week,page)}
  }
  const suffix=args.singleWeek==null?'completo':`semana-${args.singleWeek}`;doc.save(`conectae-plano-${suffix}.pdf`);
}
