import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Building2, Heart, Loader2, Target, TrendingUp } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type EventRow = { event_type:string; metadata:Record<string,unknown>|null; created_at:string };

export default function B2BInsights({ onBack }:{ onBack:()=>void }) {
  const [rows,setRows]=useState<EventRow[]>([]);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return;} const {data}=await supabase.from('analytics_events').select('event_type,metadata,created_at').in('event_type',['area_match_completed','program_interest','shortlist_added']).order('created_at',{ascending:false}).limit(2000); setRows((data??[]) as EventRow[]); setLoading(false);})();},[]);
  const stats=useMemo(()=>{
    const interests=new Map<string,number>(); const areas=new Map<string,number>(); let matches=0,shortlists=0;
    rows.forEach(r=>{const m=r.metadata??{}; if(r.event_type==='area_match_completed'){matches++; const a=String(m.area_name??m.area_id??'Área não informada');areas.set(a,(areas.get(a)??0)+1);} if(r.event_type==='program_interest'){const u=String(m.university??'Não informado');interests.set(u,(interests.get(u)??0)+1);} if(r.event_type==='shortlist_added') shortlists++;});
    return {matches,shortlists,interests:[...interests.entries()].sort((a,b)=>b[1]-a[1]).slice(0,15),areas:[...areas.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12)};
  },[rows]);
  return <div className="min-h-screen bg-[#070b16] text-ink-50"><header className="px-5 md:px-10 py-5 border-b border-white/10 flex items-center justify-between"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm text-ink-300"><ArrowLeft className="w-4 h-4"/> Voltar</button><div className="font-black flex items-center gap-2"><Building2 className="w-5 h-5 text-cyan-300"/> Conectaê University</div><span className="text-xs text-ink-500">B2B Insights</span></header><main className="max-w-6xl mx-auto px-5 py-10">{loading?<div className="py-24 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-cyan-300"/></div>:<><div className="mb-8"><div className="text-xs font-black tracking-[.16em] text-cyan-200 uppercase mb-2">Inteligência de recrutamento</div><h1 className="text-4xl md:text-5xl font-black mb-3">Demanda e intenção dos alunos</h1><p className="text-ink-400 max-w-3xl">Este painel separa interesse real de simples exposição: match concluído, entrada em shortlist e clique explícito de interesse.</p></div><div className="grid md:grid-cols-3 gap-4 mb-8"><Stat icon={<Target className="w-5 h-5"/>} label="Matches por área" value={stats.matches}/><Stat icon={<Heart className="w-5 h-5"/>} label="Shortlists" value={stats.shortlists}/><Stat icon={<TrendingUp className="w-5 h-5"/>} label="Interesses explícitos" value={stats.interests.reduce((s,[,v])=>s+v,0)}/></div><div className="grid lg:grid-cols-2 gap-6"><Ranking title="Instituições com maior intenção" items={stats.interests}/><Ranking title="Áreas com maior demanda" items={stats.areas}/></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-sm text-ink-400"><strong className="text-ink-200">Próximo nível comercial:</strong> quando o aluno consentir com contato, este painel pode mostrar leads qualificados por faixa de fit, curso, cidade e estágio do funil — sem expor dados de quem não autorizou compartilhamento.</div></>}</main></div>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-cyan-300 mb-3">{icon}</div><div className="text-3xl font-black">{value}</div><div className="text-xs text-ink-500 mt-1">{label}</div></div>}
function Ranking({title,items}:{title:string;items:[string,number][]}){const max=items[0]?.[1]||1;return <div className="rounded-[24px] border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center gap-2 mb-5"><BarChart3 className="w-5 h-5 text-violet-300"/><h2 className="font-black">{title}</h2></div>{items.length===0?<p className="text-sm text-ink-500">Ainda não há eventos suficientes.</p>:<div className="space-y-3">{items.map(([name,count],i)=><div key={name}><div className="flex justify-between text-sm mb-1"><span className="text-ink-300">{i+1}. {name}</span><span className="font-black">{count}</span></div><div className="h-1.5 rounded-full bg-white/[0.05] overflow-hidden"><div className="h-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{width:`${count/max*100}%`}}/></div></div>)}</div>}</div>}
