import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Check, ExternalLink, GraduationCap, Heart, Info, Scale, Sparkles, Target, X } from 'lucide-react';
import { trackEvent } from '@/lib/analytics';
import { supabase } from '@/lib/supabase';
import type { ProfessionalArea, ProfessionalMatchResult, ProfessionalUniversity } from '@/lib/professional-area-match';

type Props = { area:ProfessionalArea; answers:Record<string,number>; matches:ProfessionalMatchResult[]; onBack:()=>void; onHome:()=>void };
type Metric = { label:string; value:number };

const PROFILE_LABELS:Record<string,string>={rigor:'Rigor acadêmico',practical:'Aprendizagem prática',research:'Pesquisa',people:'Contato com pessoas',technology:'Tecnologia e dados',leadership:'Liderança',structure:'Estrutura',international:'Internacionalização',flexibility:'Flexibilidade',faculty:'Proximidade com professores',collaboration:'Colaboração',competition:'Competitividade',campus:'Vida universitária',career:'Carreira',entrepreneurship:'Empreendedorismo',impact:'Impacto social',quantitative:'Intensidade quantitativa',theory:'Base teórica'};

function officialMetrics(u:ProfessionalUniversity):Metric[]{return [['CPC',u.cpc],['Enade',u.enade],['IDD',u.idd],['IGC',u.igc],['CC',u.cc]].filter((x):x is [string,number]=>typeof x[1]==='number'&&Number.isFinite(x[1])).map(([label,value])=>({label,value}))}
function confidenceLabel(v:number){return v>=70?'Alta':v>=50?'Média':'Em verificação'}

export default function CommercialAreaResults({area,answers,matches,onBack,onHome}:Props){
  const [shortlist,setShortlist]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('conectae_shortlist')||'[]')}catch{return[]}});
  const [compare,setCompare]=useState<string[]>([]);
  const [detail,setDetail]=useState<ProfessionalMatchResult|null>(null);
  const [showCompare,setShowCompare]=useState(false);
  const [showMethod,setShowMethod]=useState(false);
  const [minFit,setMinFit]=useState(0);
  const [onlyEvidence,setOnlyEvidence]=useState(false);
  const [locationQuery,setLocationQuery]=useState('');
  const [interest,setInterest]=useState<ProfessionalMatchResult|null>(null);
  const [consent,setConsent]=useState(false);
  const [leadStatus,setLeadStatus]=useState<'idle'|'saving'|'saved'|'login'|'error'>('idle');

  useEffect(()=>{const top=matches[0];trackEvent('area_match_completed',{area_id:area.id,area_name:area.name,top_university:top?.university.name,top_score:top?.score,result_count:matches.length});},[area.id,area.name,matches]);
  useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('student_saved_programs').select('program_key').eq('user_id',user.id);if(data?.length){const merged=Array.from(new Set([...shortlist,...data.map((r:any)=>String(r.program_key))]));setShortlist(merged);try{localStorage.setItem('conectae_shortlist',JSON.stringify(merged))}catch{}}})();},[]);

  const profile=useMemo(()=>Object.entries(answers).filter(([k])=>PROFILE_LABELS[k]).map(([k,v])=>({label:PROFILE_LABELS[k],value:v*20})).sort((a,b)=>b.value-a.value),[answers]);
  const visibleMatches=matches.filter(m=>m.score>=minFit&&(!onlyEvidence||m.university.evidenceCount>0)&&(!locationQuery||`${m.university.location} ${m.university.campus??''}`.toLowerCase().includes(locationQuery.toLowerCase())));
  const top=matches[0];
  const topMetrics=top?officialMetrics(top.university):[];

  const setLocalShortlist=(next:string[])=>{setShortlist(next);try{localStorage.setItem('conectae_shortlist',JSON.stringify(next))}catch{}};
  const toggleShortlist=async(m:ProfessionalMatchResult)=>{
    const id=m.university.id,adding=!shortlist.includes(id),next=adding?[...shortlist,id]:shortlist.filter(x=>x!==id);
    setLocalShortlist(next);trackEvent(adding?'shortlist_added':'shortlist_removed',{area_id:area.id,university:m.university.name,program:m.university.course});
    if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;
    if(adding) await supabase.from('student_saved_programs').insert({user_id:user.id,program_key:id,area_id:area.id,university_name:m.university.name,program_name:m.university.course});
    else await supabase.from('student_saved_programs').delete().eq('user_id',user.id).eq('program_key',id);
  };
  const toggleCompare=(id:string)=>setCompare(prev=>prev.includes(id)?prev.filter(x=>x!==id):prev.length<4?[...prev,id]:prev);
  const selected=compare.map(id=>matches.find(m=>m.university.id===id)).filter(Boolean) as ProfessionalMatchResult[];
  const openInterest=(m:ProfessionalMatchResult)=>{trackEvent('program_interest',{area_id:area.id,area_name:area.name,university:m.university.name,program:m.university.course,fit_score:m.score});setInterest(m);setConsent(false);setLeadStatus('idle')};
  const confirmInterest=async()=>{
    if(!interest||!consent||!supabase)return;setLeadStatus('saving');const {data:{user}}=await supabase.auth.getUser();if(!user){setLeadStatus('login');return;}
    const {data:existing}=await supabase.from('institution_interest_leads').select('id').eq('user_id',user.id).eq('program_key',interest.university.id).maybeSingle();
    if(!existing){const {error}=await supabase.from('institution_interest_leads').insert({user_id:user.id,program_key:interest.university.id,area_id:area.id,university_name:interest.university.name,program_name:interest.university.course,fit_score:interest.score,contact_email:user.email??null,display_name:(user.user_metadata?.display_name as string|undefined)??null});if(error){setLeadStatus('error');return;}}
    if(!shortlist.includes(interest.university.id))await toggleShortlist(interest);trackEvent('qualified_lead_created',{area_id:area.id,university:interest.university.name,fit_score:interest.score});setLeadStatus('saved');
  };

  return <div className="min-h-screen bg-[#070b16] text-ink-50">
    <header className="sticky top-0 z-30 px-5 md:px-10 py-5 flex items-center justify-between border-b border-white/10 bg-[#070b16]/90 backdrop-blur-xl"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm text-ink-300"><ArrowLeft className="w-4 h-4"/> Trocar curso</button><div className="flex items-center gap-2 font-black"><GraduationCap className="w-5 h-5 text-cyan-300"/>Conecta<span className="text-cyan-300">ê</span></div><button onClick={onHome} className="text-sm text-ink-400">Início</button></header>
    <main className="max-w-6xl mx-auto px-5 py-10 md:py-12">
      <section className="rounded-[32px] border border-white/10 bg-gradient-to-br from-cyan-300/10 via-white/[0.03] to-violet-300/10 p-7 md:p-9 mb-6"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-7"><div><div className="text-sm font-bold text-cyan-200 mb-2 flex items-center gap-2"><Sparkles className="w-4 h-4"/> Seu diagnóstico · {area.name}</div><h1 className="text-4xl md:text-5xl font-black tracking-[-.03em] mb-3">Decisão, não só ranking.</h1><p className="text-ink-400 max-w-3xl">Fit pessoal, indicadores oficiais, admissão e confiança aparecem separados. O Conectaê não cria uma nota acadêmica artificial quando as métricas têm escalas, ciclos ou significados diferentes.</p></div><button onClick={()=>setShowMethod(true)} className="px-4 py-3 rounded-xl border border-white/10 bg-white/[0.04] text-sm font-bold inline-flex items-center gap-2"><Info className="w-4 h-4"/> Como calculamos</button></div></section>
      {top&&<section className="grid md:grid-cols-4 gap-3 mb-8"><DecisionCard label="Fit pessoal" value={`${top.score}%`} detail="Seu perfil vs. 24 dimensões" tone="cyan"/><DecisionCard label="Indicadores oficiais" value={topMetrics.length?`${topMetrics.length}/5 disponíveis`:'Em verificação'} detail={topMetrics.length?topMetrics.map(m=>m.label).join(' · '):'Sem métricas vinculadas ao programa'} tone="violet"/><DecisionCard label="Admissão" value="Separada" detail="Fit não é chance de aprovação" tone="amber"/><DecisionCard label="Confiança dos dados" value={confidenceLabel(top.confidence)} detail={`${top.confidence}% de cobertura/confiança`} tone="emerald"/></section>}
      <section className="grid lg:grid-cols-[1fr_330px] gap-6 mb-8"><div className="rounded-[26px] border border-white/10 bg-white/[0.035] p-6"><div className="flex items-center gap-2 mb-5"><Target className="w-5 h-5 text-cyan-300"/><h2 className="font-black text-xl">Seu perfil universitário</h2></div><div className="grid sm:grid-cols-2 gap-3">{profile.slice(0,12).map(item=><div key={item.label}><div className="flex justify-between text-xs mb-1"><span className="text-ink-400">{item.label}</span><span className="font-bold">{item.value}%</span></div><div className="h-1.5 rounded-full bg-white/[0.06] overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-brand-400" style={{width:`${item.value}%`}}/></div></div>)}</div></div><div className="rounded-[26px] border border-white/10 bg-white/[0.035] p-6"><h2 className="font-black mb-4">Refinar resultados</h2><label className="block text-xs text-ink-500 mb-2">Fit mínimo: {minFit||50}%</label><input type="range" min="0" max="95" step="5" value={minFit} onChange={e=>setMinFit(Number(e.target.value))} className="w-full mb-4"/><input value={locationQuery} onChange={e=>setLocationQuery(e.target.value)} placeholder="Cidade/campus..." className="w-full mb-4 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2.5 text-sm outline-none"/><label className="flex items-center gap-2 text-sm text-ink-300"><input type="checkbox" checked={onlyEvidence} onChange={e=>setOnlyEvidence(e.target.checked)}/> Só com evidências associadas</label><button disabled={compare.length<2} onClick={()=>setShowCompare(true)} className="mt-5 w-full px-4 py-3 rounded-xl bg-white/[0.06] border border-white/10 font-bold disabled:opacity-40 inline-flex justify-center items-center gap-2"><Scale className="w-4 h-4"/> Comparar {compare.length?`(${compare.length})`:''}</button></div></section>
      <div className="space-y-4">{visibleMatches.map((m,idx)=>{const metrics=officialMetrics(m.university),saved=shortlist.includes(m.university.id),compared=compare.includes(m.university.id);return <article key={m.university.id} className={`rounded-[26px] border p-5 md:p-6 ${idx===0?'border-cyan-300/30 bg-cyan-300/[0.055]':'border-white/10 bg-white/[0.03]'}`}><div className="flex flex-col md:flex-row gap-5"><div className="w-11 h-11 rounded-xl bg-white/[0.06] flex items-center justify-center font-black shrink-0">{idx+1}</div><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-black">{m.university.name}</h3><span className="text-[11px] px-2 py-1 rounded-full border border-white/10 text-ink-400">{confidenceLabel(m.confidence)} confiança</span></div><p className="text-sm text-ink-500 mt-1">{m.university.course}{m.university.campus?` · ${m.university.campus}`:''}</p><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4">{[['Acadêmico',m.breakdown.academic],['Aprendizagem',m.breakdown.learning],['Ambiente',m.breakdown.environment],['Carreira',m.breakdown.career],['Global',m.breakdown.globalPurpose]].map(([label,score])=><div key={String(label)} className="rounded-xl border border-white/10 bg-white/[0.025] p-3"><div className="text-[10px] text-ink-500">{label}</div><div className="font-black">{score}%</div></div>)}</div><div className="flex flex-wrap gap-2 mt-4">{m.strengths.map(s=><span key={s} className="text-xs px-2.5 py-1.5 rounded-full bg-cyan-300/[0.08] text-cyan-100">✓ {s}</span>)}{metrics.map(x=><span key={x.label} className="text-xs px-2.5 py-1.5 rounded-full bg-violet-300/[0.08] text-violet-100">{x.label} {x.value}</span>)}</div><div className="flex flex-wrap gap-2 mt-5"><button onClick={()=>setDetail(m)} className="px-3.5 py-2 rounded-xl border border-white/10 bg-white/[0.04] text-sm font-bold inline-flex items-center gap-2"><BookOpen className="w-4 h-4"/> Ver programa</button><button onClick={()=>toggleShortlist(m)} className={`px-3.5 py-2 rounded-xl border text-sm font-bold inline-flex items-center gap-2 ${saved?'border-fuchsia-300/30 bg-fuchsia-300/10 text-fuchsia-100':'border-white/10 bg-white/[0.04]'}`}><Heart className="w-4 h-4"/> {saved?'Na minha lista':'Salvar'}</button><button onClick={()=>toggleCompare(m.university.id)} className={`px-3.5 py-2 rounded-xl border text-sm font-bold inline-flex items-center gap-2 ${compared?'border-violet-300/30 bg-violet-300/10':'border-white/10 bg-white/[0.04]'}`}><Check className="w-4 h-4"/> Comparar</button><button onClick={()=>openInterest(m)} className="px-3.5 py-2 rounded-xl bg-cyan-300 text-[#06131c] text-sm font-black">Tenho interesse</button></div></div><div className="md:text-right shrink-0"><div className="text-4xl font-black text-cyan-200">{m.score}%</div><div className="text-[11px] text-ink-500">fit pessoal</div><div className="text-xs text-violet-200 mt-2">{metrics.length}/5 indicadores</div></div></div></article>})}</div>
      <section className="grid md:grid-cols-3 gap-4 mt-8"><InfoCard title="Fit ≠ qualidade">Compatibilidade pessoal não é ranking acadêmico.</InfoCard><InfoCard title="Fit ≠ aprovação">Não exibimos probabilidades de admissão sem dados robustos.</InfoCard><InfoCard title="Métricas sem média artificial">CPC, Enade, IDD, IGC e CC permanecem identificados individualmente.</InfoCard></section>
    </main>
    {detail&&<Modal onClose={()=>setDetail(null)} title={detail.university.name}><ProgramDetail m={detail} onInterest={()=>openInterest(detail)}/></Modal>}
    {showCompare&&<Modal onClose={()=>setShowCompare(false)} title="Comparação lado a lado"><Comparison items={selected}/></Modal>}
    {showMethod&&<Modal onClose={()=>setShowMethod(false)} title="Metodologia Conectaê"><Methodology/></Modal>}
    {interest&&<Modal onClose={()=>setInterest(null)} title={`Interesse em ${interest.university.name}`}><div className="max-w-2xl"><p className="text-ink-300 mb-5">Você pode apenas salvar esta faculdade ou autorizar o Conectaê a compartilhar seus dados de contato e seu fit com a instituição para receber informações sobre graduação e admissão.</p><label className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-sm text-ink-300"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>Autorizo o compartilhamento do meu nome, e-mail, curso de interesse e resultado de fit com <strong>{interest.university.name}</strong> exclusivamente para contato relacionado a graduação, processo seletivo, bolsas e admissão. Posso revogar esse consentimento posteriormente.</span></label>{leadStatus==='login'&&<p className="mt-4 text-amber-200 text-sm">Entre ou crie uma conta pelo botão no topo e tente novamente. Nenhum dado pessoal foi enviado.</p>}{leadStatus==='error'&&<p className="mt-4 text-rose-200 text-sm">Não foi possível registrar o interesse agora.</p>}{leadStatus==='saved'&&<p className="mt-4 text-emerald-200 text-sm font-bold">Interesse registrado com consentimento.</p>}<div className="flex flex-wrap gap-3 mt-5"><button onClick={()=>toggleShortlist(interest)} className="px-4 py-3 rounded-xl border border-white/10 bg-white/[0.04] font-bold">Só salvar na minha lista</button><button disabled={!consent||leadStatus==='saving'||leadStatus==='saved'} onClick={confirmInterest} className="px-4 py-3 rounded-xl bg-cyan-300 text-[#06131c] font-black disabled:opacity-40">{leadStatus==='saving'?'Registrando...':leadStatus==='saved'?'Registrado':'Autorizar contato'}</button></div></div></Modal>}
  </div>;
}

function DecisionCard({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}){const cls=tone==='cyan'?'text-cyan-200':tone==='violet'?'text-violet-200':tone==='amber'?'text-amber-200':'text-emerald-200';return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-xs text-ink-500 mb-2">{label}</div><div className={`text-2xl font-black ${cls}`}>{value}</div><div className="text-xs text-ink-500 mt-2">{detail}</div></div>}
function InfoCard({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="font-black text-sm mb-2">{title}</div><div className="text-sm text-ink-500">{children}</div></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[200] bg-black/70 backdrop-blur-sm p-4 overflow-y-auto"><div className="max-w-5xl mx-auto my-8 rounded-[28px] border border-white/10 bg-[#0b1220] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between p-5 border-b border-white/10 bg-[#0b1220]/95 backdrop-blur"><h2 className="font-black text-xl">{title}</h2><button onClick={onClose} className="p-2 rounded-xl bg-white/[0.05]"><X className="w-4 h-4"/></button></div><div className="p-5 md:p-7">{children}</div></div></div>}
function ProgramDetail({m,onInterest}:{m:ProfessionalMatchResult;onInterest:()=>void}){const u=m.university,metrics=officialMetrics(u),sections=[['Currículo',u.curriculumSummary],['Pesquisa',u.researchSummary],['Carreira',u.careerSummary],['Internacional',u.internationalSummary],['Bolsas e valor',u.scholarshipsSummary],['Experiência estudantil',u.studentExperienceSummary]];return <div><div className="grid md:grid-cols-4 gap-3 mb-6"><DecisionCard label="Fit" value={`${m.score}%`} detail="Compatibilidade pessoal" tone="cyan"/><DecisionCard label="Confiança" value={confidenceLabel(m.confidence)} detail={`${m.confidence}%`} tone="emerald"/><DecisionCard label="Evidências" value={String(u.evidenceCount)} detail="Registros associados" tone="violet"/><DecisionCard label="Indicadores oficiais" value={`${metrics.length}/5`} detail={metrics.length?metrics.map(x=>`${x.label} ${x.value}`).join(' · '):'Em verificação'} tone="amber"/></div>{u.highFit&&<div className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[0.05] p-5 mb-5"><div className="text-xs font-black text-cyan-200 mb-2">PERFIL DE ALTA ADERÊNCIA</div><p className="text-sm text-ink-300">{u.highFit}</p></div>}<div className="grid md:grid-cols-2 gap-4">{sections.filter(([,v])=>Boolean(v)).map(([title,text])=><div key={String(title)} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="font-black mb-2">{title}</h3><p className="text-sm leading-relaxed text-ink-400">{text}</p></div>)}</div><div className="flex flex-wrap gap-3 mt-6"><button onClick={onInterest} className="px-4 py-3 rounded-xl bg-cyan-300 text-[#06131c] font-black">Tenho interesse</button>{u.officialCourseUrl&&<a href={u.officialCourseUrl} target="_blank" rel="noreferrer" className="px-4 py-3 rounded-xl border border-white/10 bg-white/[0.04] font-bold inline-flex items-center gap-2">Fonte oficial <ExternalLink className="w-4 h-4"/></a>}</div></div>}
function Comparison({items}:{items:ProfessionalMatchResult[]}){if(items.length<2)return <p className="text-ink-400">Selecione pelo menos duas faculdades.</p>;const rows:[string,(m:ProfessionalMatchResult)=>string][]=[['Fit',m=>`${m.score}%`],['Acadêmico',m=>`${m.breakdown.academic}%`],['Aprendizagem',m=>`${m.breakdown.learning}%`],['Ambiente',m=>`${m.breakdown.environment}%`],['Carreira',m=>`${m.breakdown.career}%`],['Global/impacto',m=>`${m.breakdown.globalPurpose}%`],['Confiança',m=>`${m.confidence}%`],['CPC',m=>m.university.cpc==null?'—':String(m.university.cpc)],['Enade',m=>m.university.enade==null?'—':String(m.university.enade)],['IDD',m=>m.university.idd==null?'—':String(m.university.idd)],['IGC',m=>m.university.igc==null?'—':String(m.university.igc)],['CC',m=>m.university.cc==null?'—':String(m.university.cc)]];return <div className="overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr><th className="text-left p-3 text-ink-500">Critério</th>{items.map(m=><th key={m.university.id} className="text-left p-3">{m.university.name}</th>)}</tr></thead><tbody>{rows.map(([label,fn])=><tr key={label} className="border-t border-white/10"><td className="p-3 text-sm text-ink-500">{label}</td>{items.map(m=><td key={m.university.id} className="p-3 font-bold">{fn(m)}</td>)}</tr>)}</tbody></table></div>}
function Methodology(){return <div className="space-y-5 text-sm text-ink-300"><p>O match compara o perfil do aluno com perfis institucionais em 24 dimensões, usando pesos específicos por curso. As dimensões cobrem rigor, flexibilidade, pesquisa, prática, tecnologia, colaboração, carreira, empreendedorismo, internacionalização e impacto.</p><div className="grid md:grid-cols-2 gap-4"><InfoCard title="Fit pessoal">Compatibilidade de preferências; não é ranking de qualidade.</InfoCard><InfoCard title="Indicadores oficiais">CPC, Enade, IDD, IGC e CC são mostrados individualmente. Não são fundidos em uma média artificial.</InfoCard><InfoCard title="Admissão">É tratada separadamente; sem dados suficientes, não há probabilidade inventada.</InfoCard><InfoCard title="Confiança">Mostra quanto do perfil está apoiado por evidências específicas.</InfoCard></div><p className="text-ink-500">Resultados devem ser explicáveis, auditáveis e atualizados conforme novas evidências entram no banco.</p></div>}
