import { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, BrainCircuit, ChevronRight, Clock3, GraduationCap, Loader2, Minus, Plus, Save, School, Sparkles, Target } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Preference={exam_id:string;course_label:string|null;selected_area_id:string|null;selected_university_id:number|null;current_scores:Record<string,number>|null;difficulty_topics:Record<string,number>|null;weekly_hours:number|null;updated_at:string|null};
type University={area_university_id:number;university_name:string;course_label:string};
type Props={onOpenPlan:()=>void;onOpenTwin:()=>void;onOpenNotes:()=>void;onOpenTraining:()=>void;onOpenCourse:()=>void;onOpenUniversity:()=>void;};
const scoreLabel=(key:string)=>key==='Redação'?key:key.replace('Matemática','Mat.').replace('Linguagens','Ling.').replace('Humanas','Hum.').replace('Natureza','Nat.');
const clampHours=(value:number)=>Math.max(3,Math.min(30,Math.round(Number.isFinite(value)?value:9)));

export default function CourseDashboard({onOpenPlan,onOpenTwin,onOpenNotes,onOpenTraining,onOpenCourse,onOpenUniversity}:Props){
 const[loading,setLoading]=useState(true);const[pref,setPref]=useState<Preference|null>(null);const[enemPref,setEnemPref]=useState<Preference|null>(null);const[university,setUniversity]=useState<University|null>(null);const[userId,setUserId]=useState<string|null>(null);const[weeklyHours,setWeeklyHours]=useState(9);const[savedWeeklyHours,setSavedWeeklyHours]=useState(9);const[savingHours,setSavingHours]=useState(false);const[hoursMessage,setHoursMessage]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{let localHours=9;try{const raw=window.localStorage.getItem('conectae:weekly-hours');if(raw)localHours=clampHours(Number(raw))}catch{/* ignore local storage errors */}if(!supabase){if(alive){setWeeklyHours(localHours);setSavedWeeklyHours(localHours)}return}const{data:userData}=await supabase.auth.getUser();if(!userData.user)return;if(alive)setUserId(userData.user.id);const[{data:latest},{data:enem}]=await Promise.all([supabase.from('student_exam_preferences').select('exam_id,course_label,selected_area_id,selected_university_id,current_scores,difficulty_topics,weekly_hours,updated_at').eq('user_id',userData.user.id).order('updated_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('student_exam_preferences').select('exam_id,course_label,selected_area_id,selected_university_id,current_scores,difficulty_topics,weekly_hours,updated_at').eq('user_id',userData.user.id).eq('exam_id','enem').maybeSingle()]);if(!alive)return;const current=(latest??null) as Preference|null;const currentEnem=(enem??null) as Preference|null;setPref(current);setEnemPref(currentEnem);const hours=clampHours(Number(current?.weekly_hours??localHours));setWeeklyHours(hours);setSavedWeeklyHours(hours);try{window.localStorage.setItem('conectae:weekly-hours',String(hours))}catch{/* ignore local storage errors */}if(current?.selected_university_id){const{data:u}=await supabase.from('area_universities').select('area_university_id,university_name,course_label').eq('area_university_id',current.selected_university_id).maybeSingle();if(alive)setUniversity((u??null) as University|null)}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const targetCourse=university?.course_label||pref?.course_label||'Escolha seu curso';const targetUniversity=university?.university_name||'Escolha sua faculdade';const scoreEntries=useMemo(()=>Object.entries(enemPref?.current_scores??{}).filter(([,v])=>Number.isFinite(Number(v))).slice(0,5),[enemPref?.current_scores]);const twinTopics=Object.keys((pref?.difficulty_topics&&typeof pref.difficulty_topics==='object'?pref.difficulty_topics:{}) as Record<string,number>).length;const hoursDirty=weeklyHours!==savedWeeklyHours;
 const saveWeeklyHours=async()=>{setSavingHours(true);setHoursMessage('');try{const hours=clampHours(weeklyHours);setWeeklyHours(hours);try{window.localStorage.setItem('conectae:weekly-hours',String(hours))}catch{/* ignore local storage errors */}if(!supabase||!userId)throw new Error('auth');const now=new Date().toISOString();if(pref?.exam_id){const{error}=await supabase.from('student_exam_preferences').update({weekly_hours:hours,updated_at:now}).eq('user_id',userId);if(error)throw error;setPref(current=>current?{...current,weekly_hours:hours,updated_at:now}:current);setEnemPref(current=>current?{...current,weekly_hours:hours,updated_at:now}:current)}else{const{error}=await supabase.from('student_exam_preferences').upsert({user_id:userId,exam_id:'enem',weekly_hours:hours,updated_at:now},{onConflict:'user_id,exam_id'});if(error)throw error;const created:Preference={exam_id:'enem',course_label:null,selected_area_id:null,selected_university_id:null,current_scores:{},difficulty_topics:{},weekly_hours:hours,updated_at:now};setPref(created);setEnemPref(created)}setSavedWeeklyHours(hours);setHoursMessage(`Tempo atualizado para ${hours}h por semana. O plano usará esse limite no próximo recálculo.`)}catch{setHoursMessage('Não foi possível salvar o tempo semanal agora. Tente novamente.')}finally{setSavingHours(false)}};
 if(loading)return <div className="mx-auto grid min-h-[45vh] max-w-5xl place-items-center px-4 text-[#ffd45e]"><Loader2 className="animate-spin"/></div>;
 return <main className="mx-auto w-full max-w-5xl px-4 pb-[calc(9rem+env(safe-area-inset-bottom))] pt-4 text-white md:px-6 md:pb-12 md:pt-8">
  <header className="mb-5 md:mb-7"><div className="mb-2 inline-flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[.12em] text-[#ffd45e]"><Target size={14}/>Seu curso de aprovação</div><h1 className="max-w-2xl text-[28px] font-extrabold leading-[1.04] tracking-[-.045em] sm:text-[32px] md:text-5xl">O que importa para você agora.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#e0aa18]">Curso, faculdade, tempo semanal, últimas notas e seu gêmeo ficam juntos aqui. O restante está organizado nas abas abaixo.</p></header>
  <section className="grid gap-3 md:grid-cols-2 md:gap-4">
   <button type="button" onClick={onOpenCourse} className="group flex min-h-[94px] touch-manipulation items-center gap-3.5 rounded-[18px] border border-[#6f4f08] bg-[#0b0904] p-3.5 text-left transition active:scale-[.99] hover:border-[#6f4f08] sm:min-h-[108px] sm:gap-4 sm:rounded-[20px] sm:p-4 md:p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[14px] bg-[#171105] text-[#ffd45e] sm:h-11 sm:w-11 sm:rounded-2xl"><GraduationCap size={21}/></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[.08em] text-[#b88408]">Curso</span><strong className="mt-1 block break-words text-[17px] font-extrabold leading-tight tracking-[-.02em] sm:text-lg">{targetCourse}</strong><span className="mt-1 block text-xs font-bold text-[#ffd45e]">Alterar curso</span></span><ChevronRight className="shrink-0 text-[#ffd45e]" size={19}/></button>
   <button type="button" onClick={onOpenUniversity} className="group flex min-h-[94px] touch-manipulation items-center gap-3.5 rounded-[18px] border border-[#6f4f08] bg-[#0b0904] p-3.5 text-left transition active:scale-[.99] hover:border-[#6f4f08] sm:min-h-[108px] sm:gap-4 sm:rounded-[20px] sm:p-4 md:p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[14px] bg-[#171105] text-[#ffd45e] sm:h-11 sm:w-11 sm:rounded-2xl"><School size={21}/></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[.08em] text-[#b88408]">Faculdade</span><strong className="mt-1 block break-words text-[17px] font-extrabold leading-tight tracking-[-.02em] sm:text-lg">{targetUniversity}</strong><span className="mt-1 block text-xs font-bold text-[#ffd45e]">Alterar faculdade</span></span><ChevronRight className="shrink-0 text-[#ffd45e]" size={19}/></button>
   <section className="rounded-[20px] border border-[#6f4f08] bg-[#0b0904] p-4 md:col-span-2 md:p-5"><div className="flex items-start justify-between gap-4"><div><div className="inline-flex items-center gap-1.5 text-[11px] font-extrabold uppercase tracking-[.08em] text-[#ffd45e]"><Clock3 size={14}/>Tempo semanal</div><h2 className="mt-1 text-xl font-extrabold tracking-[-.02em]">{weeklyHours} horas por semana</h2><p className="mt-1 text-xs leading-relaxed text-[#e0aa18]">Mude aqui no Início. Ao salvar, o curso recalcula o volume de estudo usando esse limite.</p></div><span className="shrink-0 rounded-xl bg-[#171105] px-3 py-2 text-sm font-extrabold text-[#ffd45e]">{weeklyHours*60} min</span></div><div className="mt-4 flex items-center gap-2"><button type="button" onClick={()=>{setWeeklyHours(value=>clampHours(value-1));setHoursMessage('')}} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#241904] bg-[#171105] text-[#ffd45e]" aria-label="Diminuir uma hora por semana"><Minus size={17}/></button><input className="min-w-0 flex-1 accent-[#ffd45e]" type="range" min="3" max="30" step="1" value={weeklyHours} onChange={event=>{setWeeklyHours(clampHours(Number(event.target.value)));setHoursMessage('')}} aria-label="Horas de estudo por semana"/><button type="button" onClick={()=>{setWeeklyHours(value=>clampHours(value+1));setHoursMessage('')}} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#241904] bg-[#171105] text-[#ffd45e]" aria-label="Aumentar uma hora por semana"><Plus size={17}/></button></div><div className="mt-2 flex items-center justify-between text-[10px] font-bold text-[#b88408]"><span>3h</span><span>30h</span></div><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center"><button type="button" onClick={saveWeeklyHours} disabled={savingHours||!hoursDirty} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#ffd45e] px-4 text-sm font-extrabold text-black disabled:cursor-not-allowed disabled:opacity-45">{savingHours?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Salvar tempo semanal</button><div className="text-xs font-bold text-[#b88408]">{hoursDirty?'Alteração ainda não aplicada.':hoursMessage||`Salvo em ${savedWeeklyHours}h por semana.`}</div></div></section>
   <button type="button" onClick={onOpenNotes} className="touch-manipulation rounded-[18px] border border-[#241904] bg-[#0b0904] p-4 text-left transition active:scale-[.995] hover:border-[#6f4f08] sm:rounded-[20px] md:p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-bold uppercase tracking-[.08em] text-[#b88408]">Últimas notas do ENEM</div><div className="mt-1 text-lg font-extrabold tracking-[-.02em]">{scoreEntries.length?'Resultados salvos':'Adicione suas notas'}</div></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#171105] text-[#ffd45e]"><BookOpenCheck size={20}/></span></div>{scoreEntries.length?<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{scoreEntries.map(([k,v])=><div key={k} className="rounded-xl bg-[#171105] px-2.5 py-2.5"><div className="truncate text-[10px] font-bold text-[#b88408]">{scoreLabel(k)}</div><div className="mt-0.5 text-base font-extrabold">{v}</div></div>)}</div>:<p className="mt-3 text-xs leading-relaxed text-[#e0aa18]">Salve suas notas uma vez e elas passam a calibrar metas e prioridades.</p>}<div className="mt-3 flex items-center gap-1 text-xs font-extrabold text-[#ffd45e]">Atualizar notas <ChevronRight size={14}/></div></button>
   <button type="button" onClick={onOpenTwin} className="rounded-[20px] border border-[#6f4f08] bg-[linear-gradient(145deg,#171105,#171105)] p-4 text-left transition hover:border-[#ffd45e] md:p-5"><div className="flex items-center justify-between gap-3"><div><div className="inline-flex items-center gap-1.5 text-[11px] font-extrabold uppercase tracking-[.08em] text-[#ffd45e]"><Sparkles size={13}/>Seu gêmeo de estudos</div><div className="mt-1 text-lg font-extrabold tracking-[-.02em]">{twinTopics?`${twinTopics} dificuldades mapeadas`:'Crie seu gêmeo'}</div></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#6f4f08] text-white"><BrainCircuit size={21}/></span></div><p className="mt-3 text-xs leading-relaxed text-[#e0aa18]">Marque os pontos em que você tem mais dúvida. Não precisa enviar prova nem gabarito.</p><div className="mt-3 flex items-center gap-1 text-xs font-extrabold text-white">{twinTopics?'Atualizar meu gêmeo':'Criar meu gêmeo'} <ChevronRight size={14}/></div></button>
  </section>
  <section className="mt-6 border-t border-[#241904] pt-5"><div className="mb-3 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#b88408]">Continuar</div><div className="grid grid-cols-2 gap-2.5 md:grid-cols-4"><button type="button" onClick={onOpenPlan} className="rounded-2xl border border-[#241904] bg-[#0b0904] px-3 py-3 text-left text-sm font-bold">Plano da semana<span className="mt-1 block text-[11px] font-medium text-[#b88408]">O que estudar agora</span></button><button type="button" onClick={onOpenTraining} className="rounded-2xl border border-[#241904] bg-[#0b0904] px-3 py-3 text-left text-sm font-bold">Treinar<span className="mt-1 block text-[11px] font-medium text-[#b88408]">Questões e simulados</span></button><button type="button" onClick={onOpenTwin} className="rounded-2xl border border-[#241904] bg-[#0b0904] px-3 py-3 text-left text-sm font-bold">Dificuldades<span className="mt-1 block text-[11px] font-medium text-[#b88408]">Refinar o gêmeo</span></button><button type="button" onClick={onOpenPlan} className="rounded-2xl border border-[#241904] bg-[#0b0904] px-3 py-3 text-left text-sm font-bold">Metas<span className="mt-1 block text-[11px] font-medium text-[#b88408]">Ver progresso</span></button></div></section>
 </main>;
}
