import { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, BrainCircuit, ChevronRight, GraduationCap, Loader2, School, Sparkles, Target } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Preference={exam_id:string;course_label:string|null;selected_area_id:string|null;selected_university_id:number|null;current_scores:Record<string,number>|null;difficulty_topics:Record<string,number>|null;updated_at:string|null};
type University={area_university_id:number;university_name:string;course_label:string};
type Props={onOpenPlan:()=>void;onOpenTwin:()=>void;onOpenNotes:()=>void;onOpenTraining:()=>void;};
const scoreLabel=(key:string)=>key==='Redação'?key:key.replace('Matemática','Mat.').replace('Linguagens','Ling.').replace('Humanas','Hum.').replace('Natureza','Nat.');

export default function CourseDashboard({onOpenPlan,onOpenTwin,onOpenNotes,onOpenTraining}:Props){
 const[loading,setLoading]=useState(true);const[pref,setPref]=useState<Preference|null>(null);const[enemPref,setEnemPref]=useState<Preference|null>(null);const[university,setUniversity]=useState<University|null>(null);
 useEffect(()=>{let alive=true;(async()=>{try{if(!supabase)return;const{data:userData}=await supabase.auth.getUser();if(!userData.user)return;const[{data:latest},{data:enem}]=await Promise.all([supabase.from('student_exam_preferences').select('exam_id,course_label,selected_area_id,selected_university_id,current_scores,difficulty_topics,updated_at').eq('user_id',userData.user.id).order('updated_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('student_exam_preferences').select('exam_id,course_label,selected_area_id,selected_university_id,current_scores,difficulty_topics,updated_at').eq('user_id',userData.user.id).eq('exam_id','enem').maybeSingle()]);if(!alive)return;const current=(latest??null) as Preference|null;setPref(current);setEnemPref((enem??null) as Preference|null);if(current?.selected_university_id){const{data:u}=await supabase.from('area_universities').select('area_university_id,university_name,course_label').eq('area_university_id',current.selected_university_id).maybeSingle();if(alive)setUniversity((u??null) as University|null)}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const targetCourse=university?.course_label||pref?.course_label||'Escolha seu curso';const targetUniversity=university?.university_name||'Escolha sua faculdade';const scores=enemPref?.current_scores&&typeof enemPref.current_scores==='object'?enemPref.current_scores:{};const scoreEntries=useMemo(()=>Object.entries(scores).filter(([,v])=>Number.isFinite(Number(v))).slice(0,5),[scores]);const twinTopics=Object.keys((pref?.difficulty_topics&&typeof pref.difficulty_topics==='object'?pref.difficulty_topics:{}) as Record<string,number>).length;
 if(loading)return <div className="mx-auto grid min-h-[45vh] max-w-5xl place-items-center px-4 text-[#72a5ff]"><Loader2 className="animate-spin"/></div>;
 return <main className="mx-auto w-full max-w-5xl px-4 pb-28 pt-5 text-white md:px-6 md:pb-12 md:pt-8">
  <header className="mb-5 md:mb-7"><div className="mb-2 inline-flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[.12em] text-[#72a5ff]"><Target size={14}/>Seu curso de aprovação</div><h1 className="max-w-2xl text-[30px] font-extrabold leading-[1.05] tracking-[-.045em] md:text-5xl">O que importa para você agora.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#9fb5d4]">Curso, faculdade, últimas notas e seu gêmeo ficam juntos aqui. O restante está organizado nas abas abaixo.</p></header>
  <section className="grid gap-3 md:grid-cols-2 md:gap-4">
   <button type="button" onClick={onOpenNotes} className="group flex min-h-[108px] items-center gap-4 rounded-[20px] border border-[#173765] bg-[#06152f] p-4 text-left transition hover:border-[#315f9f] md:p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#0b2856] text-[#72a5ff]"><GraduationCap size={21}/></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[.08em] text-[#7691b5]">Curso</span><strong className="mt-1 block truncate text-lg tracking-[-.02em]">{targetCourse}</strong><span className="mt-1 block text-xs text-[#8ea6c9]">Toque para alterar</span></span><ChevronRight className="shrink-0 text-[#57739b]" size={19}/></button>
   <button type="button" onClick={onOpenNotes} className="group flex min-h-[108px] items-center gap-4 rounded-[20px] border border-[#173765] bg-[#06152f] p-4 text-left transition hover:border-[#315f9f] md:p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#0b2856] text-[#72a5ff]"><School size={21}/></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[.08em] text-[#7691b5]">Faculdade</span><strong className="mt-1 block truncate text-lg tracking-[-.02em]">{targetUniversity}</strong><span className="mt-1 block text-xs text-[#8ea6c9]">Sua meta principal</span></span><ChevronRight className="shrink-0 text-[#57739b]" size={19}/></button>
   <button type="button" onClick={onOpenNotes} className="rounded-[20px] border border-[#173765] bg-[#06152f] p-4 text-left transition hover:border-[#315f9f] md:p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-bold uppercase tracking-[.08em] text-[#7691b5]">Últimas notas do ENEM</div><div className="mt-1 text-lg font-extrabold tracking-[-.02em]">{scoreEntries.length?'Resultados salvos':'Adicione suas notas'}</div></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#0b2856] text-[#72a5ff]"><BookOpenCheck size={20}/></span></div>{scoreEntries.length?<div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-5">{scoreEntries.map(([k,v])=><div key={k} className="rounded-xl bg-[#081d40] px-2.5 py-2.5"><div className="truncate text-[10px] font-bold text-[#7691b5]">{scoreLabel(k)}</div><div className="mt-0.5 text-base font-extrabold">{v}</div></div>)}</div>:<p className="mt-3 text-xs leading-relaxed text-[#8ea6c9]">Salve suas notas uma vez e elas passam a calibrar metas e prioridades.</p>}<div className="mt-3 flex items-center gap-1 text-xs font-extrabold text-[#72a5ff]">Atualizar notas <ChevronRight size={14}/></div></button>
   <button type="button" onClick={onOpenTwin} className="rounded-[20px] border border-[#28569a] bg-[linear-gradient(145deg,#0b2856,#071a39)] p-4 text-left transition hover:border-[#4b8cff] md:p-5"><div className="flex items-center justify-between gap-3"><div><div className="inline-flex items-center gap-1.5 text-[11px] font-extrabold uppercase tracking-[.08em] text-[#8bb8ff]"><Sparkles size={13}/>Seu gêmeo de estudos</div><div className="mt-1 text-lg font-extrabold tracking-[-.02em]">{twinTopics?`${twinTopics} dificuldades mapeadas`:'Crie seu gêmeo'}</div></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#123d7e] text-white"><BrainCircuit size={21}/></span></div><p className="mt-3 text-xs leading-relaxed text-[#afc5e4]">Marque os pontos em que você tem mais dúvida. Não precisa enviar prova nem gabarito.</p><div className="mt-3 flex items-center gap-1 text-xs font-extrabold text-white">{twinTopics?'Atualizar meu gêmeo':'Criar meu gêmeo'} <ChevronRight size={14}/></div></button>
  </section>
  <section className="mt-6 border-t border-[#173765] pt-5"><div className="mb-3 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#7691b5]">Continuar</div><div className="grid grid-cols-2 gap-2.5 md:grid-cols-4"><button type="button" onClick={onOpenPlan} className="rounded-2xl border border-[#173765] bg-[#06152f] px-3 py-3 text-left text-sm font-bold">Plano da semana<span className="mt-1 block text-[11px] font-medium text-[#8199bb]">O que estudar agora</span></button><button type="button" onClick={onOpenTraining} className="rounded-2xl border border-[#173765] bg-[#06152f] px-3 py-3 text-left text-sm font-bold">Treinar<span className="mt-1 block text-[11px] font-medium text-[#8199bb]">Questões e simulados</span></button><button type="button" onClick={onOpenTwin} className="rounded-2xl border border-[#173765] bg-[#06152f] px-3 py-3 text-left text-sm font-bold">Dificuldades<span className="mt-1 block text-[11px] font-medium text-[#8199bb]">Refinar o gêmeo</span></button><button type="button" onClick={onOpenPlan} className="rounded-2xl border border-[#173765] bg-[#06152f] px-3 py-3 text-left text-sm font-bold">Metas<span className="mt-1 block text-[11px] font-medium text-[#8199bb]">Ver progresso</span></button></div></section>
 </main>;
}
