import { useEffect, useState } from 'react';
import { ArrowLeft, Heart, Loader2, Mail, MapPinned } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Saved={id:string;program_key:string;area_id:string;university_name:string;program_name:string;created_at:string};
type Lead={id:string;university_name:string;program_name:string;fit_score:number;status:string;consent_given_at:string};
const LABEL:Record<string,string>={new:'Interesse enviado',contacted:'Contato iniciado',interested:'Você demonstrou interesse',applying:'Candidatura em andamento',admitted:'Aprovado',enrolled:'Matriculado',closed:'Encerrado'};

export default function MyJourney({onBack}:{onBack:()=>void}){
 const [saved,setSaved]=useState<Saved[]>([]),[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return;}const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}const [s,l]=await Promise.all([supabase.from('student_saved_programs').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('institution_interest_leads').select('id,university_name,program_name,fit_score,status,consent_given_at').eq('user_id',user.id).order('created_at',{ascending:false})]);setSaved((s.data??[]) as Saved[]);setLeads((l.data??[]) as Lead[]);setLoading(false)})();},[]);
 const remove=async(item:Saved)=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('student_saved_programs').delete().eq('user_id',user.id).eq('id',item.id);if(!error)setSaved(prev=>prev.filter(x=>x.id!==item.id));};
 return <div className="min-h-screen bg-[#070b16] text-ink-50"><header className="px-5 md:px-10 py-5 border-b border-white/10 flex items-center justify-between"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm text-ink-300"><ArrowLeft className="w-4 h-4"/> Voltar</button><div className="font-black">Minha jornada</div><span className="text-xs text-ink-500">Conectaê Student</span></header><main className="max-w-5xl mx-auto px-5 py-10">{loading?<div className="py-24 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-cyan-300"/></div>:<><div className="mb-8"><div className="text-xs uppercase tracking-[.16em] font-black text-cyan-200 mb-2">Sua decisão universitária</div><h1 className="text-4xl md:text-5xl font-black mb-3">Tudo que você está considerando, em um só lugar.</h1><p className="text-ink-400">Salve programas, acompanhe interesses autorizados e use esta lista para comparar suas próximas decisões.</p></div><div className="grid md:grid-cols-2 gap-6"><section className="rounded-[26px] border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center gap-2 mb-5"><Heart className="w-5 h-5 text-fuchsia-300"/><h2 className="font-black text-xl">Minha lista</h2></div>{saved.length===0?<p className="text-sm text-ink-500">Você ainda não salvou nenhuma faculdade.</p>:<div className="space-y-3">{saved.map(s=><div key={s.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="font-black">{s.university_name}</div><div className="text-sm text-ink-500 mt-1">{s.program_name}</div><button onClick={()=>remove(s)} className="mt-3 text-xs text-rose-200 hover:text-rose-100">Remover da lista</button></div>)}</div>}</section><section className="rounded-[26px] border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center gap-2 mb-5"><Mail className="w-5 h-5 text-cyan-300"/><h2 className="font-black text-xl">Interesses autorizados</h2></div>{leads.length===0?<p className="text-sm text-ink-500">Nenhum contato institucional autorizado ainda.</p>:<div className="space-y-3">{leads.map(l=><div key={l.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex justify-between gap-3"><div><div className="font-black">{l.university_name}</div><div className="text-sm text-ink-500 mt-1">{l.program_name}</div></div><div className="text-2xl font-black text-cyan-200">{l.fit_score}%</div></div><div className="mt-3 inline-flex items-center gap-2 text-xs rounded-full border border-cyan-300/15 bg-cyan-300/[0.06] text-cyan-100 px-3 py-1.5"><MapPinned className="w-3.5 h-3.5"/>{LABEL[l.status]??l.status}</div></div>)}</div>}</section></div></>}</main></div>;
}
