import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, Search, X, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type ExamId='enem'|'cmmg'|'fuvest'|'insper'|'link';
type Mode='official'|'adapted'|'authorial';
type Alt={letter:string;text:string;file?:string|null};
type EnemOfficial={id:string;exam:'ENEM';year:number;number:number;area:string;discipline:string;language:string|null;context:string;prompt:string;alternatives:Alt[];correctOption:string;files:string[];source:string};
type Practice={id:number;exam_id:ExamId;area:string;skill_name:string;difficulty:number;prompt:string;option_a:string|null;option_b:string|null;option_c:string|null;option_d:string|null;option_e:string|null;correct_option:string|null;explanation:string|null;source_kind:string|null;source_exam_year:number|null;source_question_number:number|null;source_exam_label:string|null;source_exam_url:string|null;source_answer_url:string|null;image_url:string|null;image_alt:string|null};
type ExamCfg={id:ExamId;label:string};
const EXAMS:ExamCfg[]=[{id:'enem',label:'ENEM'},{id:'cmmg',label:'CMMG'},{id:'fuvest',label:'FUVEST'},{id:'insper',label:'Insper'},{id:'link',label:'Link'}];
const ENEM_AREAS=['Linguagens','Humanas','Natureza','Matemática'];
const LETTERS=['A','B','C','D','E'] as const;

function practiceAlt(q:Practice,l:string){return q[`option_${l.toLowerCase()}` as keyof Practice] as string|null}
function groupCmmgArea(area:string){const a=area.toLowerCase();if(/biologia|física|fisica|química|quimica|natureza/.test(a))return'Natureza';if(/matem/.test(a))return'Matemática';if(/portugu|ingl|liter|lingu/.test(a))return'Linguagens';return area}

export default function OfficialQuestionWorkspaceV4(){
  const[exam,setExam]=useState<ExamId>(()=>{const v=localStorage.getItem('conectae:active-exam') as ExamId|null;return EXAMS.some(x=>x.id===v)?v!:'enem'});
  const[mode,setMode]=useState<Mode>('official');
  const[practice,setPractice]=useState<Practice[]>([]);
  const[enemOfficial,setEnemOfficial]=useState<EnemOfficial[]>([]);
  const[enemCounts,setEnemCounts]=useState<Record<string,number>>({});
  const[loading,setLoading]=useState(true);
  const[area,setArea]=useState('Todas'); const[year,setYear]=useState('Todos'); const[search,setSearch]=useState('');
  const[activeEnem,setActiveEnem]=useState<EnemOfficial|null>(null); const[activePractice,setActivePractice]=useState<Practice|null>(null);
  const[selected,setSelected]=useState(''); const[submitted,setSubmitted]=useState(false);

  useEffect(()=>{localStorage.setItem('conectae:active-exam',exam);setArea('Todas');setYear('Todos');setSearch('');setMode(exam==='enem'||exam==='cmmg'?'official':'authorial')},[exam]);
  useEffect(()=>{let alive=true;(async()=>{setLoading(true);try{
    const [pool,pr]=await Promise.all([
      exam==='enem'?fetch('/api/enem-official-pool').then(async r=>{const d=await r.json();if(!r.ok||!d.guaranteed)throw new Error('Acervo oficial ENEM indisponível.');return d}):Promise.resolve(null),
      supabase?supabase.from('exam_practice_questions').select('id,exam_id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,source_kind,source_exam_year,source_question_number,source_exam_label,source_exam_url,source_answer_url,image_url,image_alt').eq('active',true).eq('exam_id',exam).range(0,1499):Promise.resolve({data:[]}),
    ]);
    if(!alive)return;setPractice(((pr as any)?.data??[]) as Practice[]);setEnemOfficial(pool?.questions??[]);setEnemCounts(pool?.counts??{});
  }catch(e){console.error(e);if(alive){setEnemOfficial([]);setEnemCounts({})}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[exam]);

  const officialPractice=useMemo(()=>practice.filter(q=>q.source_kind==='official'&&q.prompt?.trim()&&q.correct_option&&LETTERS.every(l=>Boolean(practiceAlt(q,l)))),[practice]);
  const adapted=useMemo(()=>practice.filter(q=>q.source_kind==='official_adapted'),[practice]);
  const authorial=useMemo(()=>practice.filter(q=>!q.source_kind||q.source_kind==='authorial'),[practice]);
  const officialRows=useMemo(()=>exam==='enem'?enemOfficial:exam==='cmmg'?officialPractice:[],[exam,enemOfficial,officialPractice]);
  const rows:any[]=mode==='official'?officialRows:mode==='adapted'?adapted:authorial;
  const availableAreas=useMemo(()=>{if(mode==='official'&&exam==='enem')return ENEM_AREAS;if(mode==='official'&&exam==='cmmg')return Array.from(new Set(officialPractice.map(q=>groupCmmgArea(q.area))));return Array.from(new Set((rows as Practice[]).map(q=>q.area).filter(Boolean)))},[mode,exam,officialPractice,rows]);
  const years=useMemo(()=>['Todos',...Array.from(new Set(rows.map((q:any)=>exam==='enem'&&mode==='official'?q.year:q.source_exam_year).filter((v:any)=>Number.isFinite(v)))).sort((a:any,b:any)=>b-a).map(String)],[rows,exam,mode]);
  const filtered=useMemo(()=>rows.filter((q:any)=>{const qArea=exam==='enem'&&mode==='official'?q.area:exam==='cmmg'&&mode==='official'?groupCmmgArea(q.area):q.area;if(area!=='Todas'&&qArea!==area)return false;const qYear=exam==='enem'&&mode==='official'?q.year:q.source_exam_year;if(year!=='Todos'&&String(qYear)!==year)return false;const t=search.trim().toLowerCase();if(!t)return true;const h=exam==='enem'&&mode==='official'?`${q.area} ${q.discipline} ${q.language||''} ${q.number} ${q.year} ${q.prompt} ${q.context}`:`${q.area} ${q.skill_name} ${q.source_question_number||''} ${q.prompt}`;return h.toLowerCase().includes(t)}),[rows,exam,mode,area,year,search]);
  const modalOpen=Boolean(activeEnem||activePractice);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('conectae:question-modal',{detail:{open:modalOpen}}));document.body.style.overflow=modalOpen?'hidden':'';return()=>{document.body.style.overflow='';window.dispatchEvent(new CustomEvent('conectae:question-modal',{detail:{open:false}}))}},[modalOpen]);

  function reset(){setSelected('');setSubmitted(false)}
  function close(){setActiveEnem(null);setActivePractice(null);reset()}
  function openEnem(q:EnemOfficial){reset();setActiveEnem(q);setActivePractice(null)}
  function openPractice(q:Practice){reset();setActivePractice(q);setActiveEnem(null)}
  const currentCorrect=activeEnem?.correctOption||activePractice?.correct_option||null;
  const result=submitted&&currentCorrect?selected===currentCorrect:null;

  if(loading)return <div className="grid min-h-[260px] place-items-center rounded-2xl border border-[#173765] bg-[#06152f]"><div className="flex items-center gap-2 text-sm font-bold text-[#9fb5d4]"><Loader2 size={17} className="animate-spin"/>Validando banco de questões…</div></div>;
  return <section className="pb-8">
    <div className="mb-4"><div className="text-[11px] font-extrabold uppercase tracking-[.1em] text-[#72a5ff]">Banco de questões</div><h1 className="mt-1 text-2xl font-extrabold tracking-[-.035em] md:text-3xl">Treine pela prova que você vai fazer.</h1><p className="mt-2 max-w-2xl text-sm text-[#93a9c9]">Questões oficiais só aparecem quando já estão completas para resolver dentro do Conectaê.</p></div>
    <div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{EXAMS.map(x=><button key={x.id} onClick={()=>setExam(x.id)} className={`shrink-0 rounded-xl border px-4 py-2.5 text-sm font-extrabold ${exam===x.id?'border-[#3479ff] bg-[#246cff] text-white':'border-[#234576] bg-[#071a38] text-[#a9bddc]'}`}>{x.label}</button>)}</div>
    <div className="mt-3 grid grid-cols-3 gap-2 rounded-2xl border border-[#173765] bg-[#06152f] p-2"><button disabled={!['enem','cmmg'].includes(exam)} onClick={()=>setMode('official')} className={`rounded-xl px-2 py-3 text-xs font-extrabold disabled:opacity-35 ${mode==='official'?'bg-emerald-500/15 text-emerald-200':'text-[#9fb5d4]'}`}>Oficiais<span className="block text-lg">{officialRows.length}</span></button><button onClick={()=>setMode('adapted')} className={`rounded-xl px-2 py-3 text-xs font-extrabold ${mode==='adapted'?'bg-[#0b2856] text-white':'text-[#9fb5d4]'}`}>Adaptadas<span className="block text-lg">{adapted.length}</span></button><button onClick={()=>setMode('authorial')} className={`rounded-xl px-2 py-3 text-xs font-extrabold ${mode==='authorial'?'bg-[#0b2856] text-white':'text-[#9fb5d4]'}`}>Estilo da prova<span className="block text-lg">{authorial.length}</span></button></div>

    {mode==='official'&&exam==='enem'&&<div className="mt-3 rounded-2xl border border-emerald-400/25 bg-emerald-400/[.05] p-4"><div className="font-extrabold">ENEM · questões estruturadas e validadas</div><p className="mt-1 text-xs text-[#9fb5d4]">Cada item já possui enunciado, alternativas e gabarito antes de aparecer aqui.</p><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{ENEM_AREAS.map(a=><button key={a} onClick={()=>setArea(a)} className={`shrink-0 rounded-xl border px-3 py-2 text-left ${area===a?'border-emerald-300/50 bg-emerald-300/10':'border-[#234576] bg-[#071a38]'}`}><strong className="block text-sm">{a}</strong><span className="text-[10px] text-[#9fb5d4]">{enemCounts[a]||0} prontas</span></button>)}</div></div>}
    {mode==='official'&&exam==='cmmg'&&<div className="mt-3 rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-4"><div className="font-extrabold">CMMG · somente questões integralmente validadas</div><p className="mt-1 text-xs leading-relaxed text-[#9fb5d4]">Referências de prova sem enunciado e alternativas completos não são exibidas como se fossem resolvíveis. Estou mantendo apenas o acervo que realmente abre de ponta a ponta.</p></div>}

    <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setArea('Todas')} className={`rounded-lg border px-3 py-2 text-xs font-bold ${area==='Todas'?'border-[#3479ff] bg-[#123a78]':'border-[#203d67] bg-[#071a38] text-[#8fa7c9]'}`}>Todas as áreas</button>{availableAreas.map(a=><button key={a} onClick={()=>setArea(a)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${area===a?'border-[#3479ff] bg-[#123a78]':'border-[#203d67] bg-[#071a38] text-[#8fa7c9]'}`}>{a}</button>)}</div>
    <div className="relative mt-3"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#6f8ebc]" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar conteúdo, matéria ou número" className="h-11 w-full rounded-xl border border-[#234576] bg-[#071a38] pl-10 pr-3 text-sm text-white outline-none placeholder:text-[#6680a5]"/></div>
    {years.length>1&&<div className="mt-2 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{years.map(v=><button key={v} onClick={()=>setYear(v)} className={`shrink-0 rounded-lg border px-3 py-1.5 text-[11px] font-bold ${year===v?'border-[#3479ff] bg-[#123a78] text-white':'border-[#203d67] bg-[#071a38] text-[#8fa7c9]'}`}>{v==='Todos'?'Todos os anos':v}</button>)}</div>}
    <div className="mt-4 text-xs font-bold text-[#8fa7c9]">{filtered.length} {filtered.length===1?'questão encontrada':'questões encontradas'}</div>
    <div className="mt-3 grid gap-2.5 md:grid-cols-2">{filtered.slice(0,160).map((q:any)=>exam==='enem'&&mode==='official'?<button key={q.id} onClick={()=>openEnem(q)} className="rounded-2xl border border-emerald-400/20 bg-[#06152f] p-4 text-left"><div className="flex items-center justify-between"><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[9px] font-black uppercase tracking-wide text-emerald-200">Oficial</span><span className="text-[10px] text-[#708bb3]">{q.year}</span></div><div className="mt-3 text-[11px] font-bold text-[#72a5ff]">ENEM {q.year} · Questão {q.number}</div><strong className="mt-1.5 block text-sm">{q.area}{q.language?` · ${q.language}`:''}</strong><p className="mt-2 line-clamp-2 text-xs text-[#8fa7c9]">{q.prompt||q.context}</p></button>:<button key={q.id} onClick={()=>openPractice(q)} className={`rounded-2xl border p-4 text-left ${mode==='official'?'border-emerald-400/20 bg-[#06152f]':'border-[#183965] bg-[#06152f]'}`}><div className="flex items-center justify-between"><span className={`text-[9px] font-black uppercase tracking-wide ${mode==='official'?'text-emerald-200':'text-[#72a5ff]'}`}>{mode==='official'?'Oficial':mode==='adapted'?'Adaptada':'Estilo da prova'}</span><span className="text-[10px] text-[#708bb3]">{q.source_exam_year||`nível ${q.difficulty}/5`}</span></div><div className="mt-3 text-[11px] font-bold text-[#72a5ff]">{mode==='official'?`CMMG ${q.source_exam_year||''} · Questão ${q.source_question_number||''}`:q.area}</div><strong className="mt-1.5 block text-sm">{q.skill_name}</strong><p className="mt-2 line-clamp-2 text-xs text-[#8fa7c9]">{q.prompt}</p></button>)}</div>
    {!filtered.length&&<div className="mt-4 rounded-2xl border border-[#173765] bg-[#06152f] p-5 text-sm text-[#9fb5d4]">Nenhuma questão completa disponível com esses filtros.</div>}

    {modalOpen&&<div className="fixed inset-0 z-[220] overflow-y-auto bg-[#020817] text-white" role="dialog" aria-modal="true"><div className="mx-auto min-h-full w-full max-w-3xl px-4 pb-[calc(env(safe-area-inset-bottom)+28px)] pt-[max(12px,env(safe-area-inset-top))] md:px-6"><div className="sticky top-0 z-10 -mx-1 flex items-center justify-between gap-3 border-b border-[#173765] bg-[#020817]/97 px-1 py-3 backdrop-blur-xl"><div><div className="text-[11px] font-black uppercase tracking-wide text-emerald-200">{mode==='official'?'Questão oficial':mode==='adapted'?'Adaptada de prova real':'Estilo da prova'}</div><div className="text-sm font-extrabold">{activeEnem?`ENEM ${activeEnem.year} · Questão ${activeEnem.number}`:activePractice?.source_exam_label||EXAMS.find(x=>x.id===exam)?.label}</div></div><button onClick={close} className="grid h-11 w-11 place-items-center rounded-xl border border-[#234576] bg-[#071a38]" aria-label="Fechar"><X size={20}/></button></div>
      <div className="py-5">{activeEnem&&<><div className="text-xs font-bold text-[#72a5ff]">{activeEnem.area}{activeEnem.language?` · ${activeEnem.language}`:''}</div>{activeEnem.context&&<p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-[#c2d0e5]">{activeEnem.context}</p>}{activeEnem.files?.length>0&&<div className="mt-4 grid gap-3">{activeEnem.files.map(src=><img key={src} src={src} alt="Elemento visual da questão oficial" className="max-h-[460px] w-full rounded-xl bg-white object-contain" loading="eager"/>)}</div>}<h2 className="mt-5 whitespace-pre-line text-lg font-extrabold leading-relaxed md:text-xl">{activeEnem.prompt}</h2><div className="mt-5 grid gap-2.5">{activeEnem.alternatives.map(a=>{const chosen=selected===a.letter,isCorrect=submitted&&activeEnem.correctOption===a.letter,isWrong=submitted&&chosen&&!isCorrect;return <button key={a.letter} disabled={submitted} onClick={()=>setSelected(a.letter)} className={`flex min-h-14 items-start gap-3 rounded-xl border px-4 py-3 text-left ${isCorrect?'border-emerald-400 bg-emerald-400/10':isWrong?'border-rose-400 bg-rose-400/10':chosen?'border-[#3479ff] bg-[#123a78]':'border-[#234576] bg-[#071a38]'}`}><strong>{a.letter}</strong><span className="text-sm leading-relaxed">{a.text}</span></button>})}</div></>}
      {activePractice&&<><div className="text-xs font-bold text-[#72a5ff]">{activePractice.area}</div>{activePractice.image_url&&<img src={activePractice.image_url} alt={activePractice.image_alt||'Imagem da questão'} className="mt-4 max-h-[460px] w-full rounded-xl bg-white object-contain"/>}<h2 className="mt-4 whitespace-pre-line text-lg font-extrabold leading-relaxed md:text-xl">{activePractice.prompt}</h2><div className="mt-5 grid gap-2.5">{LETTERS.map(l=>{const text=practiceAlt(activePractice,l);if(!text)return null;const chosen=selected===l,isCorrect=submitted&&activePractice.correct_option===l,isWrong=submitted&&chosen&&!isCorrect;return <button key={l} disabled={submitted} onClick={()=>setSelected(l)} className={`flex min-h-14 items-start gap-3 rounded-xl border px-4 py-3 text-left ${isCorrect?'border-emerald-400 bg-emerald-400/10':isWrong?'border-rose-400 bg-rose-400/10':chosen?'border-[#3479ff] bg-[#123a78]':'border-[#234576] bg-[#071a38]'}`}><strong>{l}</strong><span className="text-sm leading-relaxed">{text}</span></button>})}</div></>}
      {!submitted?<button disabled={!selected} onClick={()=>setSubmitted(true)} className="mt-5 min-h-12 w-full rounded-xl bg-[#246cff] px-4 text-sm font-extrabold disabled:opacity-40">Confirmar resposta</button>:<div className={`mt-5 rounded-2xl border p-4 ${result?'border-emerald-400/30 bg-emerald-400/[.07]':'border-rose-400/30 bg-rose-400/[.07]'}`}><div className="flex items-center gap-2 font-extrabold">{result?<><CheckCircle2 size={19}/>Resposta correta</>:<><XCircle size={19}/>Resposta incorreta</>}</div><p className="mt-2 text-sm">Gabarito: <strong>{currentCorrect}</strong></p>{activePractice?.explanation&&<p className="mt-2 text-sm text-[#a9bddc]">{activePractice.explanation}</p>}</div>}
      </div></div></div>}
  </section>;
}
