import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ExternalLink, Loader2, Search, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type ExamId='enem'|'cmmg'|'fuvest'|'insper'|'link';
type Mode='official'|'practice';
type PracticeQuestion={id:number;exam_id:ExamId;area:string;skill_name:string;difficulty:number;prompt:string;option_a:string|null;option_b:string|null;option_c:string|null;option_d:string|null;option_e:string|null;correct_option:string|null;explanation:string|null;source_kind:string|null;source_exam_year:number|null;source_question_number:number|null;source_exam_label:string|null;source_exam_url:string|null;source_answer_url:string|null};
type OfficialRef={question_id:string;vestibular:string;year:number;question_number:number;area:string|null;subject:string|null;skill_name:string|null;correct_option:string|null;answer_status:string|null;source_pdf_url:string|null;answer_key_url:string|null;source_url:string|null;booklet_code:string|null;color:string|null;day:number|null};

const EXAMS:{id:ExamId;label:string;indexed:number}[]=[
  {id:'enem',label:'ENEM',indexed:1260},{id:'cmmg',label:'CMMG',indexed:600},{id:'fuvest',label:'FUVEST',indexed:270},{id:'insper',label:'Insper',indexed:0},{id:'link',label:'Link',indexed:0},
];
const officialVestibular=(exam:ExamId)=>exam==='enem'?'ENEM':exam==='cmmg'?'Vestibular Ciências Médicas-MG':exam==='fuvest'?'FUVEST':'';

export default function OfficialQuestionWorkspace(){
  const[exam,setExam]=useState<ExamId>(()=>{const s=localStorage.getItem('conectae:active-exam') as ExamId|null;return EXAMS.some(x=>x.id===s)?s!:'enem'});
  const[mode,setMode]=useState<Mode>(()=>['enem','cmmg','fuvest'].includes(localStorage.getItem('conectae:active-exam')||'enem')?'official':'practice');
  const[practice,setPractice]=useState<PracticeQuestion[]>([]);
  const[official,setOfficial]=useState<OfficialRef[]>([]);
  const[loading,setLoading]=useState(true);
  const[area,setArea]=useState('Todas');const[skill,setSkill]=useState('Todos');const[year,setYear]=useState('Todos');const[search,setSearch]=useState('');
  const[practiceActive,setPracticeActive]=useState<PracticeQuestion|null>(null);const[officialActive,setOfficialActive]=useState<OfficialRef|null>(null);const[selected,setSelected]=useState('');const[result,setResult]=useState<boolean|null>(null);

  useEffect(()=>{localStorage.setItem('conectae:active-exam',exam);setArea('Todas');setSkill('Todos');setYear('Todos');setSearch('');setMode(['enem','cmmg','fuvest'].includes(exam)?'official':'practice')},[exam]);
  useEffect(()=>{let alive=true;(async()=>{if(!supabase)return;setLoading(true);const practiceQuery=supabase.from('exam_practice_questions').select('id,exam_id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,source_kind,source_exam_year,source_question_number,source_exam_label,source_exam_url,source_answer_url').eq('active',true).eq('exam_id',exam).range(0,1499);const vest=officialVestibular(exam);const officialQuery=vest?supabase.from('official_vestibular_question_bank').select('question_id,vestibular,year,question_number,area,subject,skill_name,correct_option,answer_status,source_pdf_url,answer_key_url,source_url,booklet_code,color,day').eq('vestibular',vest).order('year',{ascending:false}).order('question_number',{ascending:true}).range(0,499):Promise.resolve({data:[] as OfficialRef[]});const[p,o]=await Promise.all([practiceQuery,officialQuery as any]);if(alive){setPractice((p.data??[]) as PracticeQuestion[]);setOfficial((o.data??[]) as OfficialRef[]);setLoading(false)}})();return()=>{alive=false}},[exam]);

  const rows=mode==='official'?official:practice;
  const areas=useMemo(()=>['Todas',...Array.from(new Set(rows.map((q:any)=>q.area).filter(Boolean))).sort()],[rows]);
  const areaRows=useMemo(()=>area==='Todas'?rows:rows.filter((q:any)=>q.area===area),[rows,area]);
  const skills=useMemo(()=>['Todos',...Array.from(new Set(areaRows.map((q:any)=>mode==='official'?(q.skill_name||q.subject):q.skill_name).filter(Boolean))).sort()],[areaRows,mode]);
  const years=useMemo(()=>['Todos',...Array.from(new Set(rows.map((q:any)=>mode==='official'?q.year:q.source_exam_year).filter((x:any)=>Number.isFinite(x)))).sort((a:any,b:any)=>b-a).map(String)],[rows,mode]);
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return rows.filter((q:any)=>{const qSkill=mode==='official'?(q.skill_name||q.subject||''):q.skill_name;const qYear=mode==='official'?q.year:q.source_exam_year;if(area!=='Todas'&&q.area!==area)return false;if(skill!=='Todos'&&qSkill!==skill)return false;if(year!=='Todos'&&String(qYear)!==year)return false;if(term&&!`${q.area||''} ${qSkill||''} ${mode==='official'?`questão ${q.question_number}`:q.prompt||''}`.toLowerCase().includes(term))return false;return true})},[rows,area,skill,year,search,mode]);
  const counts=useMemo(()=>({official:practice.filter(q=>q.source_kind==='official').length,adapted:practice.filter(q=>q.source_kind==='official_adapted').length,authorial:practice.filter(q=>!q.source_kind||q.source_kind==='authorial').length}),[practice]);
  const selectedExam=EXAMS.find(x=>x.id===exam)!;
  const modalOpen=Boolean(practiceActive||officialActive);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('conectae:question-modal',{detail:{open:modalOpen}}));document.body.style.overflow=modalOpen?'hidden':'';return()=>{document.body.style.overflow='';window.dispatchEvent(new CustomEvent('conectae:question-modal',{detail:{open:false}}))}},[modalOpen]);

  const answer=()=>{if(!practiceActive||!selected||result!==null)return;setResult(selected===practiceActive.correct_option)};
  if(loading)return <div className="grid min-h-[260px] place-items-center rounded-2xl border border-[#173765] bg-[#06152f]"><div className="flex items-center gap-2 text-sm font-bold text-[#9fb5d4]"><Loader2 size={17} className="animate-spin"/>Carregando banco…</div></div>;

  return <section className="pb-8">
    <div className="mb-4"><div className="text-[11px] font-extrabold uppercase tracking-[.1em] text-[#72a5ff]">Banco de questões</div><h1 className="mt-1 text-2xl font-extrabold tracking-[-.035em] md:text-3xl">Treine pela prova certa.</h1><p className="mt-2 max-w-2xl text-sm text-[#93a9c9]">Oficiais aparecem primeiro. Questões autorais ficam separadas como treino complementar.</p></div>
    <div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{EXAMS.map(x=><button key={x.id} onClick={()=>setExam(x.id)} className={`shrink-0 rounded-xl border px-4 py-2.5 text-sm font-extrabold ${exam===x.id?'border-[#3479ff] bg-[#246cff] text-white':'border-[#234576] bg-[#071a38] text-[#a9bddc]'}`}>{x.label}</button>)}</div>
    <div className="mt-3 grid grid-cols-2 gap-2 rounded-2xl border border-[#173765] bg-[#06152f] p-2">
      <button disabled={selectedExam.indexed===0} onClick={()=>setMode('official')} className={`rounded-xl px-3 py-3 text-sm font-extrabold ${mode==='official'?'bg-[#246cff] text-white':'text-[#9fb5d4]'} disabled:opacity-40`}>Questões oficiais{selectedExam.indexed>0?<span className="ml-1 text-xs opacity-75">({selectedExam.indexed.toLocaleString('pt-BR')})</span>:null}</button>
      <button onClick={()=>setMode('practice')} className={`rounded-xl px-3 py-3 text-sm font-extrabold ${mode==='practice'?'bg-[#0b2856] text-white':'text-[#9fb5d4]'}`}>Treino complementar</button>
    </div>

    {mode==='official'?<div className="mt-3 rounded-2xl border border-emerald-400/25 bg-emerald-400/[.05] p-4"><div className="text-lg font-extrabold">{selectedExam.label} · questões oficiais</div><p className="mt-1 text-xs leading-relaxed text-[#9fb5d4]">{selectedExam.indexed.toLocaleString('pt-BR')} itens oficiais indexados. Aqui mostramos prova, ano e número; ao abrir, você acessa a fonte oficial dentro do fluxo. Não reclassificamos questões autorais como oficiais.</p></div>:<div className="mt-3 rounded-2xl border border-[#173765] bg-[#06152f] p-4"><div className="text-lg font-extrabold">Treino complementar</div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border border-[#1b3b69] bg-[#081a38] p-2"><strong className="block text-lg">{counts.official}</strong><span className="text-[10px] text-[#9fb5d4]">Oficiais completas</span></div><div className="rounded-xl border border-[#1b3b69] bg-[#081a38] p-2"><strong className="block text-lg">{counts.adapted}</strong><span className="text-[10px] text-[#9fb5d4]">Adaptadas</span></div><div className="rounded-xl border border-[#1b3b69] bg-[#081a38] p-2"><strong className="block text-lg">{counts.authorial}</strong><span className="text-[10px] text-[#9fb5d4]">Estilo da prova</span></div></div></div>}

    <div className="mt-3 grid gap-2 md:grid-cols-4"><label className="relative md:col-span-2"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#6f8ebc]" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={mode==='official'?'Buscar matéria, conteúdo ou número':'Buscar conteúdo ou palavra-chave'} className="h-11 w-full rounded-xl border border-[#234576] bg-[#071a38] pl-10 pr-3 text-sm text-white outline-none placeholder:text-[#6680a5]"/></label>{[{value:area,set:setArea,options:areas,label:'Matéria'},{value:skill,set:setSkill,options:skills,label:'Conteúdo'}].map((f,i)=><label key={i} className="relative"><select value={f.value} onChange={e=>f.set(e.target.value)} className="h-11 w-full appearance-none rounded-xl border border-[#234576] bg-[#071a38] px-3 pr-8 text-xs font-bold text-white outline-none">{f.options.map(o=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#6f8ebc]" size={15}/></label>)}</div>
    {years.length>1&&<div className="mt-2 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{years.map(y=><button key={y} onClick={()=>setYear(y)} className={`shrink-0 rounded-lg border px-3 py-1.5 text-[11px] font-bold ${year===y?'border-[#3479ff] bg-[#123a78] text-white':'border-[#203d67] bg-[#071a38] text-[#8fa7c9]'}`}>{y==='Todos'?'Todos os anos':y}</button>)}</div>}
    <div className="mt-4 text-xs font-bold text-[#8fa7c9]">{filtered.length} {filtered.length===1?'item encontrado':'itens encontrados'}{mode==='official'&&official.length>=500?' · mostrando até 500 por vez':''}</div>

    <div className="mt-3 grid gap-2.5 md:grid-cols-2">{filtered.slice(0,120).map((q:any)=>mode==='official'?<button key={q.question_id} onClick={()=>setOfficialActive(q as OfficialRef)} className="rounded-2xl border border-emerald-400/20 bg-[#06152f] p-4 text-left hover:border-emerald-300/50"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[9px] font-black uppercase tracking-wide text-emerald-200">Oficial</span><span className="text-[10px] text-[#708bb3]">{q.year}</span></div><div className="mt-3 text-[11px] font-bold text-[#72a5ff]">{selectedExam.label} {q.year} · Questão {q.question_number}</div><strong className="mt-1.5 block text-sm text-white">{q.skill_name||q.subject||q.area||'Questão da prova oficial'}</strong><p className="mt-2 text-xs text-[#8fa7c9]">Abrir questão na fonte oficial{q.correct_option?' · gabarito oficial disponível':''}</p></button>:<button key={q.id} onClick={()=>{setPracticeActive(q as PracticeQuestion);setSelected('');setResult(null)}} className="rounded-2xl border border-[#183965] bg-[#06152f] p-4 text-left hover:border-[#3479ff]"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-[#10294f] px-2 py-1 text-[9px] font-black uppercase tracking-wide text-[#9fb5d4]">{q.source_kind==='official'?'Oficial completa':q.source_kind==='official_adapted'?'Adaptada de prova real':'Estilo da prova'}</span><span className="text-[10px] text-[#708bb3]">nível {q.difficulty}/5</span></div><div className="mt-3 text-[11px] font-bold text-[#72a5ff]">{selectedExam.label}{q.source_exam_year?` ${q.source_exam_year}`:''}{q.source_question_number?` · Q${q.source_question_number}`:''} · {q.area}</div><strong className="mt-1.5 block text-sm text-white">{q.skill_name}</strong><p className="mt-2 line-clamp-2 text-xs text-[#8fa7c9]">{q.prompt}</p></button>)}</div>
    {!filtered.length&&<div className="mt-4 rounded-2xl border border-[#173765] bg-[#06152f] p-5 text-sm text-[#9fb5d4]">Nenhum item com esses filtros. Tente outro ano, matéria ou conteúdo.</div>}

    {officialActive&&<div className="fixed inset-0 z-[220] overflow-y-auto bg-[#020817] text-white" role="dialog" aria-modal="true"><div className="mx-auto min-h-full max-w-4xl px-4 pb-8 pt-[max(12px,env(safe-area-inset-top))]"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#173765] bg-[#020817]/97 py-3 backdrop-blur-xl"><div><div className="text-xs font-bold text-emerald-200">QUESTÃO OFICIAL</div><div className="mt-1 font-extrabold">{selectedExam.label} {officialActive.year} · Questão {officialActive.question_number}</div></div><button onClick={()=>setOfficialActive(null)} className="grid h-11 w-11 place-items-center rounded-xl border border-[#234576] bg-[#071a38]"><X size={20}/></button></div><div className="py-4"><div className="rounded-2xl border border-[#173765] bg-[#06152f] p-4"><p className="text-sm leading-relaxed text-[#b6c8e2]">Esta é uma referência oficial verificada. O enunciado completo permanece na fonte da prova para preservar a procedência. Use o visualizador abaixo ou abra a prova oficial.</p><div className="mt-3 flex flex-wrap gap-2">{(officialActive.source_pdf_url||officialActive.source_url)&&<a href={officialActive.source_pdf_url||officialActive.source_url||'#'} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#246cff] px-4 py-2.5 text-sm font-extrabold"><ExternalLink size={15}/>Abrir prova oficial</a>}{officialActive.answer_key_url&&<a href={officialActive.answer_key_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#234576] bg-[#071a38] px-4 py-2.5 text-sm font-bold">Gabarito oficial</a>}</div>{officialActive.correct_option&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/[.06] p-3 text-sm"><span className="text-[#9fb5d4]">Resposta oficial indexada:</span> <strong className="text-emerald-200">{officialActive.correct_option}</strong></div>}</div>{(officialActive.source_pdf_url||officialActive.source_url)&&<iframe title="Fonte oficial da questão" src={officialActive.source_pdf_url||officialActive.source_url||''} className="mt-4 h-[68vh] w-full rounded-2xl border border-[#173765] bg-white"/>}</div></div></div>}

    {practiceActive&&<div className="fixed inset-0 z-[220] overflow-y-auto bg-[#020817] text-white" role="dialog" aria-modal="true"><div className="mx-auto min-h-full max-w-3xl px-4 pb-8 pt-[max(12px,env(safe-area-inset-top))]"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#173765] bg-[#020817]/97 py-3 backdrop-blur-xl"><div className="text-sm font-extrabold">{selectedExam.label} · {practiceActive.skill_name}</div><button onClick={()=>setPracticeActive(null)} className="grid h-11 w-11 place-items-center rounded-xl border border-[#234576] bg-[#071a38]"><X size={20}/></button></div><div className="py-5"><h2 className="text-xl font-extrabold leading-snug">{practiceActive.prompt}</h2><div className="mt-5 space-y-2">{(['a','b','c','d','e'] as const).map(letter=>{const text=(practiceActive as any)[`option_${letter}`] as string|null;if(!text)return null;const value=letter.toUpperCase();return <button key={value} disabled={result!==null} onClick={()=>setSelected(value)} className={`flex w-full gap-3 rounded-xl border p-4 text-left ${selected===value?'border-[#3d83ff] bg-[#123a78]':'border-[#234576] bg-[#071a38]'}`}><strong>{value}</strong><span>{text}</span></button>})}</div>{result===null?<button disabled={!selected} onClick={answer} className="mt-5 w-full rounded-xl bg-[#246cff] px-4 py-3 font-extrabold disabled:opacity-40">Responder</button>:<div className={`mt-5 rounded-xl border p-4 ${result?'border-emerald-400/30 bg-emerald-400/[.06]':'border-red-400/30 bg-red-400/[.06]'}`}><strong>{result?'Resposta correta.':'Resposta incorreta.'}</strong>{practiceActive.explanation&&<p className="mt-2 text-sm text-[#b6c8e2]">{practiceActive.explanation}</p>}</div>}</div></div></div>}
  </section>;
}
