import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, BookOpenCheck, ExternalLink, ListChecks, Loader2, Search, Video } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Edition={id:string;year:number;application:string;application_label:string|null};
type Booklet={id:string;edition_id:string;day:number|null;booklet_code:string|null;color:string|null;question_start:number|null;question_end:number|null;source_pdf_url:string|null;answer_key_url:string|null};
type Item={id:string;area:string|null;subject:string|null;skill_code:string|null;skill_name:string|null;prompt_text:string|null;explanation:string|null};
type Mapping={id:string;question_number:number;correct_option:string|null;answer_status:string;official_exam_items:Item|null};
type Practice={id:number;area:string;skill_name:string;prompt:string};

type Group={key:string;area:string;subject:string;skill:string;numbers:number[];video:string;practice:Practice[]};

const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const videoFor=(subject:string,skill:string)=>`https://www.youtube.com/results?search_query=${encodeURIComponent(`${subject} ${skill} ENEM aula exercícios`)}`;
function parseNumbers(raw:string,min:number,max:number){const set=new Set<number>();raw.split(/[;,\s]+/).filter(Boolean).forEach(t=>{const r=t.match(/^(\d+)-(\d+)$/);if(r){for(let n=Math.min(+r[1],+r[2]);n<=Math.max(+r[1],+r[2]);n++)if(n>=min&&n<=max)set.add(n);return;}const n=Number(t.replace(/\D/g,''));if(n>=min&&n<=max)set.add(n)});return [...set].sort((a,b)=>a-b)}

export default function OfficialExamReviewV2(){
  const[editions,setEditions]=useState<Edition[]>([]);const[booklets,setBooklets]=useState<Booklet[]>([]);
  const[year,setYear]=useState(2025);const[editionId,setEditionId]=useState('');const[bookletId,setBookletId]=useState('');
  const[number,setNumber]=useState(1);const[result,setResult]=useState<Mapping|null>(null);const[wrongRaw,setWrongRaw]=useState('');
  const[groups,setGroups]=useState<Group[]>([]);const[missing,setMissing]=useState<number[]>([]);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);

  useEffect(()=>{(async()=>{if(!supabase)return;const{data}=await supabase.from('official_exam_editions').select('id,year,application,application_label').eq('series_id','enem').order('year',{ascending:false});const rows=(data??[]) as Edition[];setEditions(rows);const first=rows.find(x=>x.year===2025)??rows[0];if(first){setYear(first.year);setEditionId(first.id)}})()},[]);
  useEffect(()=>{const apps=editions.filter(e=>e.year===year);if(apps.length&&!apps.some(a=>a.id===editionId))setEditionId(apps[0].id)},[year,editions,editionId]);
  useEffect(()=>{(async()=>{if(!supabase||!editionId){setBooklets([]);return}const{data}=await supabase.from('official_exam_booklets').select('id,edition_id,day,booklet_code,color,question_start,question_end,source_pdf_url,answer_key_url').eq('edition_id',editionId).order('day').order('booklet_code');const rows=(data??[]) as Booklet[];setBooklets(rows);setBookletId(rows[0]?.id??'');setNumber(rows[0]?.question_start??1);setResult(null);setGroups([]);setMissing([]);setMessage('')})()},[editionId]);

  const years=useMemo(()=>[...new Set(editions.map(e=>e.year))].sort((a,b)=>b-a),[editions]);
  const types=useMemo(()=>editions.filter(e=>e.year===year),[editions,year]);
  const booklet=booklets.find(b=>b.id===bookletId);const minQ=booklet?.question_start??1,maxQ=booklet?.question_end??180;
  const wrong=useMemo(()=>parseNumbers(wrongRaw,minQ,maxQ),[wrongRaw,minQ,maxQ]);

  const findOne=async()=>{if(!supabase||!bookletId)return;setBusy(true);setResult(null);const{data}=await supabase.from('official_exam_item_booklet_map').select('id,question_number,correct_option,answer_status,official_exam_items(id,area,subject,skill_code,skill_name,prompt_text,explanation)').eq('booklet_id',bookletId).eq('question_number',number).maybeSingle();setResult((data as unknown as Mapping)??null);setBusy(false)};

  const analyze=async()=>{if(!supabase||!bookletId||!wrong.length)return;setBusy(true);setGroups([]);setMissing([]);setMessage('');try{const{data:userData}=await supabase.auth.getUser();if(!userData.user)throw new Error('login');const{data}=await supabase.from('official_exam_item_booklet_map').select('id,question_number,correct_option,answer_status,official_exam_items(id,area,subject,skill_code,skill_name,prompt_text,explanation)').eq('booklet_id',bookletId).in('question_number',wrong);const rows=((data??[]) as unknown as Mapping[]).sort((a,b)=>a.question_number-b.question_number);const found=new Set(rows.map(r=>r.question_number));const miss=wrong.filter(n=>!found.has(n));setMissing(miss);if(!rows.length){setMessage('O caderno está cadastrado, mas essas questões ainda não foram indexadas individualmente. Não vou inventar habilidades ou gabaritos.');return}
    const reports=rows.map(r=>({user_id:userData.user!.id,booklet_id:bookletId,item_id:r.official_exam_items?.id??null,question_number:r.question_number,area:r.official_exam_items?.area??null,subject:r.official_exam_items?.subject??null,skill_code:r.official_exam_items?.skill_code??null,skill_name:r.official_exam_items?.skill_name??null,error_type:'simulado_oficial'}));await supabase.from('official_exam_error_reports').upsert(reports,{onConflict:'user_id,booklet_id,question_number'});
    const diagnosable=rows.filter(r=>r.official_exam_items?.area||r.official_exam_items?.skill_name);if(diagnosable.length)await supabase.from('student_skill_diagnostics').insert(diagnosable.map(r=>({user_id:userData.user!.id,exam_id:'enem',skill_code:r.official_exam_items?.skill_code??null,area:r.official_exam_items?.area??'ENEM',question_text:`ENEM ${year} · ${booklet?.color??''} · questão ${r.question_number}`,correct:false,confidence:1,error_type:'simulado_oficial',diagnosis:{source:'official_exam_batch',question_number:r.question_number,skill_name:r.official_exam_items?.skill_name,subject:r.official_exam_items?.subject}})));
    const map=new Map<string,{area:string;subject:string;skill:string;numbers:number[]}>();rows.forEach(r=>{const i=r.official_exam_items;const area=i?.area||'ENEM',subject=i?.subject||area,skill=i?.skill_name||subject,key=`${norm(area)}|${norm(subject)}|${norm(skill)}`;const g=map.get(key)??{area,subject,skill,numbers:[]};g.numbers.push(r.question_number);map.set(key,g)});const bases=[...map.entries()].sort((a,b)=>b[1].numbers.length-a[1].numbers.length);const{data:p}=await supabase.from('exam_practice_questions').select('id,area,skill_name,prompt').eq('exam_id','enem').eq('active',true).limit(350);const practice=(p??[]) as Practice[];setGroups(bases.map(([key,g])=>({key,...g,video:videoFor(g.subject,g.skill),practice:practice.filter(q=>norm(q.skill_name||'').includes(norm(g.skill))||norm(q.area)===norm(g.area)).slice(0,8)})));window.dispatchEvent(new CustomEvent('conectae:diagnostic-saved'));setMessage(`${rows.length} erro(s) identificado(s) e enviados ao Plano.${miss.length?` ${miss.length} ainda aguardam indexação.`:''}`)}catch{setMessage('Não foi possível analisar agora. Tente novamente.')}finally{setBusy(false)}};

  return <section id="correcao-simulado" className="max-w-[1180px] mx-auto px-4 md:px-6 py-8 text-white font-['Plus_Jakarta_Sans'] scroll-mt-24"><div className="rounded-[20px] border border-[#173765] bg-[#06152f] p-5 md:p-6">
    <div className="flex items-center gap-2 text-xs font-extrabold text-[#72a5ff]"><BookOpenCheck size={16}/>Simulados oficiais</div><h2 className="mt-2 text-2xl md:text-3xl font-extrabold tracking-[-.04em]">Corrigir um ENEM que você já fez</h2><p className="mt-2 text-sm text-[#9fb5d4]">Escolha o ano, o <b className="text-white">tipo de prova</b>, o dia/cor do caderno e informe as questões que errou. Esta área é de correção, não é o cronograma do seu Plano.</p>
    <div className="mt-5 grid grid-cols-1 md:grid-cols-3 gap-3"><label className="text-xs text-[#b8cae4]">Ano<select className="mt-1 w-full rounded-xl border border-[#234576] bg-[#081a38] p-3 text-white" value={year} onChange={e=>setYear(+e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label className="text-xs text-[#b8cae4]">Tipo de prova<select className="mt-1 w-full rounded-xl border border-[#234576] bg-[#081a38] p-3 text-white" value={editionId} onChange={e=>setEditionId(e.target.value)}>{types.map(e=><option key={e.id} value={e.id}>{e.application_label||e.application}</option>)}</select></label><label className="text-xs text-[#b8cae4]">Dia e caderno<select className="mt-1 w-full rounded-xl border border-[#234576] bg-[#081a38] p-3 text-white" value={bookletId} onChange={e=>setBookletId(e.target.value)}>{booklets.length?booklets.map(b=><option key={b.id} value={b.id}>Dia {b.day} · {b.color} · caderno {b.booklet_code}</option>):<option value="">Caderno ainda em indexação</option>}</select></label></div>
    <div className="mt-5 rounded-2xl border border-[#234576] bg-[#081a38] p-4"><div className="flex items-center gap-2 text-sm font-extrabold"><ListChecks size={17}/>Quais questões você errou?</div><textarea className="mt-3 min-h-[92px] w-full rounded-xl border border-[#234576] bg-[#06152f] p-3 text-white" value={wrongRaw} onChange={e=>setWrongRaw(e.target.value)} placeholder="Ex.: 12, 37, 84, 102, 146  ou  90-95"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={analyze} disabled={!bookletId||!wrong.length||busy} className="inline-flex items-center gap-2 rounded-xl bg-[#246cff] px-4 py-3 text-sm font-extrabold disabled:opacity-40">{busy?<Loader2 size={16} className="animate-spin"/>:<Search size={16}/>}Identificar habilidades e criar recuperação</button>{booklet?.source_pdf_url&&<a href={booklet.source_pdf_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#234576] px-4 py-3 text-sm font-bold">Abrir prova oficial <ExternalLink size={15}/></a>}{booklet?.answer_key_url&&<a href={booklet.answer_key_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#234576] px-4 py-3 text-sm font-bold">Gabarito oficial <ExternalLink size={15}/></a>}</div>{message&&<p className="mt-3 text-sm text-[#b8cae4]">{message}</p>}{missing.length>0&&<div className="mt-3 flex gap-2 text-xs text-amber-200"><AlertCircle size={15}/>Ainda não indexadas: {missing.join(', ')}</div>}</div>
    {groups.length>0&&<div className="mt-5 grid gap-3">{groups.map(g=><article key={g.key} className="rounded-2xl border border-[#234576] bg-[#081a38] p-4"><div className="text-xs font-extrabold text-[#72a5ff]">{g.numbers.length} erro(s) · questões {g.numbers.join(', ')}</div><h3 className="mt-1 text-lg font-extrabold">{g.subject} · {g.skill}</h3><p className="mt-1 text-sm text-[#9fb5d4]">Treino recomendado: vídeo dirigido + {Math.max(15,g.numbers.length*6)} questões semelhantes + refazer as originais.</p><div className="mt-3 flex flex-wrap gap-2"><a href={g.video} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#246cff] px-3 py-2 text-xs font-extrabold"><Video size={14}/>Vídeo desta habilidade</a>{g.practice.length>0&&<span className="rounded-xl border border-[#234576] px-3 py-2 text-xs font-bold">{g.practice.length} questões semelhantes encontradas no banco</span>}</div></article>)}</div>}
    <div className="mt-7 border-t border-[#173765] pt-5"><div className="text-xs font-extrabold text-[#72a5ff]">Consulta individual</div><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-xs text-[#b8cae4]">Número da questão<input className="mt-1 block w-32 rounded-xl border border-[#234576] bg-[#081a38] p-3 text-white" type="number" min={minQ} max={maxQ} value={number} onChange={e=>setNumber(+e.target.value)}/></label><button onClick={findOne} disabled={!bookletId||busy} className="rounded-xl border border-[#234576] bg-[#0b2856] px-4 py-3 text-sm font-extrabold">Identificar questão</button></div>{result&&<div className="mt-3 rounded-xl bg-[#0b2856] p-3 text-sm"><b>Questão {result.question_number}</b> · gabarito {result.answer_status==='annulled'?'ANULADA':result.correct_option||'em validação'}{result.official_exam_items?.skill_name&&<> · habilidade: <b>{result.official_exam_items.skill_name}</b></>}</div>}</div>
  </div></section>;
}
