import { useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Brain, CheckCircle2, FileText, Lightbulb, Search, Target } from 'lucide-react';

type Topic = {
  slug: string; title: string; eixo: string; foco: string; argumentos: string[]; repertorios: string[]; intervencao: string;
};

const TOPICS: Topic[] = [
  {slug:'gestao-de-lixo',title:'Gestão de lixo',eixo:'Meio ambiente',foco:'Descarte, coleta seletiva, reciclagem e responsabilidade compartilhada.',argumentos:['Baixa educação ambiental e descarte inadequado','Infraestrutura desigual de coleta e reciclagem','Responsabilidade de Estado, empresas e consumidores'],repertorios:['Política Nacional de Resíduos Sólidos','Economia circular','Consumo e sustentabilidade'],intervencao:'Poder público + municípios: ampliar coleta seletiva, educação ambiental e integração de cooperativas, com metas e monitoramento.'},
  {slug:'nomofobia',title:'Nomofobia',eixo:'Tecnologia e saúde',foco:'Dependência do celular e impactos sociais, acadêmicos, físicos e psicológicos.',argumentos:['Pressão para permanecer conectado','Medo de exclusão e baixa autoestima','Prejuízos à concentração e às relações presenciais'],repertorios:['Bauman — fragilidade dos laços humanos','Her e M3GAN — dependência/substituição de relações','Biologia — sistema de recompensa e dopamina'],intervencao:'Escolas e Ministério da Saúde: promover educação digital e prevenção ao uso problemático, com orientação e acesso a apoio especializado.'},
  {slug:'dependentes-quimicos',title:'Dependentes químicos',eixo:'Saúde pública',foco:'Dependência química, estigma, prevenção, tratamento e reinserção social.',argumentos:['Estigma dificulta busca por tratamento','Vulnerabilidades sociais ampliam riscos','Prevenção e cuidado continuado são essenciais'],repertorios:['Saúde pública e redução de danos','Direitos humanos e dignidade','Rede de atenção psicossocial'],intervencao:'SUS e redes locais: ampliar prevenção, cuidado multiprofissional e reinserção, com campanhas antiestigma e acompanhamento.'},
  {slug:'patrimonio',title:'Patrimônio',eixo:'Cultura e cidadania',foco:'Preservação do patrimônio material e imaterial e construção da memória coletiva.',argumentos:['Desvalorização da memória coletiva','Falta de educação patrimonial','Pressões econômicas e urbanas sobre bens culturais'],repertorios:['Patrimônio cultural brasileiro','Memória e identidade','Educação patrimonial'],intervencao:'IPHAN, escolas e governos locais: mapear, preservar e ensinar patrimônio, com participação comunitária e fiscalização.'},
  {slug:'mulheres-na-ciencia',title:'Mulheres na Ciência',eixo:'Gênero e educação',foco:'Barreiras à participação, permanência e reconhecimento de mulheres na produção científica.',argumentos:['Estereótipos de gênero afetam escolhas acadêmicas','Sub-representação reduz referências','Desigualdades institucionais prejudicam progressão'],repertorios:['História das mulheres na ciência','Efeito Matilda','Igualdade de oportunidades'],intervencao:'Instituições de ensino e pesquisa: criar mentorias, bolsas, divulgação de cientistas e métricas de equidade.'},
  {slug:'ist-dst',title:'IST/DST',eixo:'Saúde e educação',foco:'Prevenção de infecções sexualmente transmissíveis, informação e acesso a diagnóstico e tratamento.',argumentos:['Desinformação aumenta vulnerabilidade','Estigma dificulta prevenção e diagnóstico','Acesso desigual aos serviços de saúde'],repertorios:['Educação em saúde','Prevenção combinada','Saúde pública'],intervencao:'SUS e escolas: ampliar educação baseada em evidências, testagem, prevenção e encaminhamento, preservando privacidade.'},
  {slug:'racismo-ambiental',title:'Racismo ambiental',eixo:'Meio ambiente e desigualdade',foco:'Distribuição desigual de riscos ambientais e infraestrutura entre grupos e territórios.',argumentos:['Riscos ambientais não são distribuídos igualmente','Segregação territorial amplia vulnerabilidades','Políticas ambientais precisam considerar justiça social'],repertorios:['Justiça ambiental','Urbanização desigual','Direito ao meio ambiente equilibrado'],intervencao:'Governos: mapear vulnerabilidades, priorizar saneamento e prevenção de riscos e incluir comunidades nas decisões.'},
  {slug:'inteligencia-artificial',title:'Perspectivas da Inteligência Artificial na sociedade',eixo:'Tecnologia',foco:'Benefícios, riscos e transformações sociais provocados pela inteligência artificial.',argumentos:['IA amplia produtividade e acesso a serviços','Vieses e uso irresponsável podem reproduzir desigualdades','Educação digital e governança precisam acompanhar a inovação'],repertorios:['Ética em tecnologia','Transformação do trabalho','Alfabetização digital'],intervencao:'Estado, escolas e empresas: promover alfabetização em IA, transparência, proteção de dados e avaliação de impactos.'},
  {slug:'automedicacao',title:'Automedicação',eixo:'Saúde pública',foco:'Riscos do uso de medicamentos sem orientação adequada e fatores que estimulam essa prática.',argumentos:['Desinformação favorece uso inadequado','Facilidade de acesso pode incentivar consumo irresponsável','Automedicação pode mascarar sintomas e gerar riscos'],repertorios:['Uso racional de medicamentos','Educação em saúde','Responsabilidade sanitária'],intervencao:'Ministério da Saúde, farmácias e mídia: reforçar orientação profissional, campanhas educativas e fiscalização.'},
  {slug:'saude-mental',title:'Ausência de discussão sobre saúde mental',eixo:'Saúde e sociedade',foco:'Consequências do silêncio, estigma e falta de educação sobre saúde mental.',argumentos:['Estigma desestimula procura por ajuda','Desinformação dificulta reconhecimento de sofrimento','Ambientes escolares e profissionais precisam de prevenção'],repertorios:['Saúde integral','Estigma social','Educação socioemocional'],intervencao:'Escolas, empresas e SUS: criar espaços de informação, acolhimento e encaminhamento profissional.'},
  {slug:'exploracao-sexual',title:'Combate à exploração sexual',eixo:'Direitos humanos',foco:'Prevenção, identificação, denúncia e proteção de vítimas de exploração sexual.',argumentos:['Vulnerabilidade socioeconômica amplia exposição','Subnotificação dificulta enfrentamento','Proteção exige articulação de diferentes instituições'],repertorios:['ECA e proteção integral','Direitos humanos','Rede de proteção'],intervencao:'Poder público e rede de proteção: fortalecer canais de denúncia, capacitação, acolhimento e investigação.'},
  {slug:'autismo',title:'Autismo',eixo:'Inclusão e cidadania',foco:'Inclusão de pessoas autistas, combate ao capacitismo e garantia de acesso a direitos.',argumentos:['Desinformação alimenta preconceitos','Barreiras escolares e profissionais limitam inclusão','Políticas precisam considerar diferentes necessidades de suporte'],repertorios:['Neurodiversidade','Inclusão educacional','Acessibilidade e cidadania'],intervencao:'Escolas, empresas e Estado: capacitar equipes, oferecer adaptações razoáveis e ampliar informação pública.'},
  {slug:'seguranca-publica',title:'Segurança pública',eixo:'Cidadania',foco:'Prevenção da violência, atuação estatal e construção de políticas de segurança eficazes.',argumentos:['Desigualdades territoriais afetam exposição à violência','Prevenção requer políticas sociais e inteligência','Confiança institucional depende de atuação responsável'],repertorios:['Cidadania e direitos','Prevenção da violência','Políticas públicas baseadas em evidências'],intervencao:'Governos: integrar prevenção social, inteligência, formação profissional e avaliação de resultados.'},
  {slug:'saude-bucal',title:'Saúde bucal',eixo:'Saúde pública',foco:'Prevenção, acesso a cuidados odontológicos e impactos da desigualdade na saúde bucal.',argumentos:['Prevenção reduz doenças evitáveis','Acesso a atendimento é desigual','Educação e hábitos cotidianos são determinantes'],repertorios:['Saúde integral','Prevenção em saúde','Desigualdade de acesso'],intervencao:'SUS e escolas: ampliar prevenção, acompanhamento odontológico e educação em higiene bucal.'},
  {slug:'educacao-financeira',title:'Educação Financeira',eixo:'Educação e cidadania',foco:'Formação para decisões financeiras conscientes, planejamento e prevenção do endividamento.',argumentos:['Baixa alfabetização financeira prejudica decisões','Consumo e crédito exigem capacidade de planejamento','Educação precoce fortalece autonomia'],repertorios:['Cidadania financeira','Consumo consciente','Planejamento e orçamento'],intervencao:'Escolas e instituições públicas: oferecer educação financeira prática, simulações e materiais acessíveis.'}
];

export default function RedacaoHub({ onBack }: { onBack: () => void }) {
  const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Topic|null>(null);
  const filtered=useMemo(()=>TOPICS.filter(t=>(t.title+' '+t.eixo).toLowerCase().includes(query.toLowerCase())),[query]);
  if(selected) return <div className="min-h-screen bg-ink-950 text-ink-100 px-5 py-8"><div className="max-w-5xl mx-auto">
    <button onClick={()=>setSelected(null)} className="mb-6 text-brand-300 flex gap-2 items-center"><ArrowLeft className="w-4 h-4"/>Todos os temas</button>
    <div className="rounded-3xl border border-brand-500/30 bg-ink-900/70 p-6 md:p-9"><span className="text-xs font-bold text-brand-300 uppercase tracking-wider">{selected.eixo}</span><h1 className="text-3xl md:text-4xl font-bold mt-2">{selected.title}</h1><p className="text-ink-300 mt-3 text-lg">{selected.foco}</p></div>
    <div className="grid md:grid-cols-2 gap-4 mt-5">
      <Section icon={<FileText/>} title="Material da professora"><p>Conteúdo-base do material enviado, organizado para revisão. Use esta aula como fonte principal antes de partir para os exercícios e repertórios complementares.</p></Section>
      <Section icon={<Target/>} title="O que dominar"><ul>{selected.argumentos.map(x=><li key={x}>• {x}</li>)}</ul></Section>
      <Section icon={<Lightbulb/>} title="Repertórios para a redação"><ul>{selected.repertorios.map(x=><li key={x}>• {x}</li>)}</ul><p className="mt-3 text-ink-400 text-sm">Não basta citar: explique a relação do repertório com a tese.</p></Section>
      <Section icon={<Brain/>} title="Estratégia de argumentação"><p>Monte a introdução com recorte do problema + tese. No D1, explique uma causa estrutural. No D2, desenvolva uma consequência ou segunda causa. Em cada parágrafo: tópico frasal → explicação → repertório → conexão com o tema.</p></Section>
      <Section icon={<CheckCircle2/>} title="Proposta de intervenção"><p>{selected.intervencao}</p><p className="mt-3 text-ink-400 text-sm">Cheque os 5 elementos: agente, ação, meio/modo, finalidade e detalhamento.</p></Section>
      <Section icon={<BookOpen/>} title="Treino ENEM"><p className="font-semibold text-ink-100">Escreva uma tese em 2 linhas para o tema.</p><p className="mt-2">Depois, escolha dois argumentos acima e produza um tópico frasal para cada desenvolvimento. Finalize criando uma intervenção completa sem ferir os direitos humanos.</p></Section>
    </div>
    <div className="mt-5 rounded-2xl border border-ink-800 bg-ink-900/60 p-6"><h3 className="font-bold mb-3">Checklist antes de escrever</h3><div className="grid sm:grid-cols-2 gap-2 text-sm text-ink-300">{['Entendi exatamente o recorte do tema','Tenho uma tese clara','Escolhi 2 argumentos diferentes','Sei como usar meus repertórios','Cada repertório será explicado','Minha conclusão tem os 5 elementos do ENEM'].map(x=><span key={x}>□ {x}</span>)}</div></div>
  </div></div>;
  return <div className="min-h-screen bg-ink-950 text-ink-100 px-5 py-8"><div className="max-w-6xl mx-auto">
    <button onClick={onBack} className="mb-8 text-ink-300 flex gap-2 items-center"><ArrowLeft className="w-4 h-4"/>Voltar</button>
    <div className="max-w-3xl"><span className="text-brand-300 text-sm font-bold">CURSO DE REDAÇÃO</span><h1 className="text-4xl md:text-5xl font-bold mt-2">Biblioteca de temas</h1><p className="text-ink-400 mt-3 text-lg">15 aulas temáticas para transformar conteúdo em argumento, repertório e proposta de intervenção no padrão ENEM.</p></div>
    <div className="relative mt-7 max-w-xl"><Search className="absolute left-4 top-3.5 w-5 h-5 text-ink-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tema..." className="w-full rounded-xl border border-ink-700 bg-ink-900 py-3 pl-12 pr-4 outline-none focus:border-brand-500"/></div>
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-7">{filtered.map((t,i)=><button key={t.slug} onClick={()=>setSelected(t)} className="text-left rounded-2xl border border-ink-800 bg-ink-900/60 p-5 hover:border-brand-500/50 hover:-translate-y-0.5 transition-all"><span className="text-xs text-brand-300 font-bold">AULA {String(i+1).padStart(2,'0')}</span><h2 className="font-bold text-lg mt-2">{t.title}</h2><p className="text-sm text-ink-400 mt-2">{t.eixo}</p><p className="text-sm text-ink-500 mt-3 line-clamp-2">{t.foco}</p></button>)}</div>
  </div></div>;
}
function Section({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-ink-800 bg-ink-900/60 p-6"><div className="flex items-center gap-2 text-brand-300 mb-3">{icon}<h2 className="font-bold text-ink-100">{title}</h2></div><div className="text-ink-300 leading-relaxed space-y-1">{children}</div></div>}
