from pathlib import Path

p=Path('src/components/AdmissionsPlannerV11.tsx')
s=p.read_text()
s=s.replace("import WeeklyPlanExperience from '@/components/WeeklyPlanExperience';", "import WeeklyPlanExperience from '@/components/WeeklyPlanExperience';\nimport DifficultyProfile from '@/components/DifficultyProfile';\nimport { type DifficultySelection } from '@/lib/exam-skill-catalog';")
s=s.replace("  const[cutoffs,setCutoffs]=useState<AdmissionCutoff[]>([]);", "  const[cutoffs,setCutoffs]=useState<AdmissionCutoff[]>([]);\n  const[difficultyTopics,setDifficultyTopics]=useState<DifficultySelection>({});")
s=s.replace("select('current_scores,weekly_hours')", "select('current_scores,weekly_hours,difficulty_topics')")
s=s.replace("if(pref?.weekly_hours){setWeeklyHours(Number(pref.weekly_hours));setAppliedWeeklyHours(Number(pref.weekly_hours))}await reloadDiagnostics", "if(pref?.weekly_hours){setWeeklyHours(Number(pref.weekly_hours));setAppliedWeeklyHours(Number(pref.weekly_hours))}if(pref?.difficulty_topics&&typeof pref.difficulty_topics==='object')setDifficultyTopics(pref.difficulty_topics as DifficultySelection);else setDifficultyTopics({});await reloadDiagnostics")
s=s.replace("const roadmap=useMemo(()=>buildRoadmap({model,course,priorities,weeklyHours:appliedWeeklyHours,questions:allowedQuestions}),[model,course,priorities,appliedWeeklyHours,allowedQuestions]);", "const roadmap=useMemo(()=>buildRoadmap({model,course,priorities,weeklyHours:appliedWeeklyHours,questions:allowedQuestions,difficultyTopics,diagnostics:relevantDiagnostics.map(d=>({area:d.area,skill:d.diagnosis?.skill_name||d.skill_code||d.area}))}),[model,course,priorities,appliedWeeklyHours,allowedQuestions,difficultyTopics,relevantDiagnostics]);")
old="  const top=priorities[0];\n  const roadmap=useMemo(()=>buildRoadmap({model,course,priorities,weeklyHours:appliedWeeklyHours,questions:allowedQuestions,difficultyTopics,diagnostics:relevantDiagnostics.map(d=>({area:d.area,skill:d.diagnosis?.skill_name||d.skill_code||d.area}))}),[model,course,priorities,appliedWeeklyHours,allowedQuestions,difficultyTopics,relevantDiagnostics]);\n  const relevantDiagnostics=useMemo(()=>diagnostics.filter(d=>d.exam_id===model.examId&&model.allowedQuestionAreas.some(a=>matchQuestionArea(d.area,a))).slice(0,5),[diagnostics,model]);"
new="  const top=priorities[0];\n  const relevantDiagnostics=useMemo(()=>diagnostics.filter(d=>d.exam_id===model.examId&&model.allowedQuestionAreas.some(a=>matchQuestionArea(d.area,a))).slice(0,8),[diagnostics,model]);\n  const roadmap=useMemo(()=>buildRoadmap({model,course,priorities,weeklyHours:appliedWeeklyHours,questions:allowedQuestions,difficultyTopics,diagnostics:relevantDiagnostics.map(d=>({area:d.area,skill:d.diagnosis?.skill_name||d.skill_code||d.area}))}),[model,course,priorities,appliedWeeklyHours,allowedQuestions,difficultyTopics,relevantDiagnostics]);"
s=s.replace(old,new)
s=s.replace("course_label:course,updated_at:new Date().toISOString()", "course_label:course,difficulty_topics:difficultyTopics,updated_at:new Date().toISOString()")
needle="      {tab==='plano'&&<div className=\"plan6-grid\">\n        <section className=\"plan6-card span12\"><div className=\"plan6-sectionlabel\">Semana por semana</div>"
rep="      {tab==='plano'&&<div className=\"plan6-grid\">\n        <DifficultyProfile examId={model.examId} course={course} value={difficultyTopics} onChange={setDifficultyTopics}/>\n        <section className=\"plan6-card span12\"><div className=\"plan6-sectionlabel\">Semana por semana</div>"
s=s.replace(needle,rep)
s=s.replace("Esse cronograma usa apenas as notas que você salvou. Novas dificuldades enviadas pelo scanner entram abaixo como <b>extras</b>, sem apagar a estrutura principal.", "O cronograma combina notas salvas, tempo disponível, dificuldades que você marcou, erros em questões e diagnósticos enviados por foto. Tudo é redistribuído dentro das mesmas horas semanais.")
s=s.replace("<h2>Notas + erros + tempo.</h2><p>As notas salvas definem a estrutura semanal. Seus erros e diagnósticos entram como recuperação extra.</p>", "<h2>Notas + dificuldades + erros + tempo.</h2><p>O plano cruza desempenho, tópicos marcados por você, questões erradas e diagnósticos de fotos. Nenhuma dificuldade adiciona horas escondidas: o mesmo orçamento semanal é redistribuído.</p>")
p.write_text(s)

r=Path('src/lib/admissions-roadmap.ts')
t=r.read_text()
t=t.replace("import type { ExamId, ExamMetric, ExamModel } from '@/lib/exam-models';", "import type { ExamId, ExamMetric, ExamModel } from '@/lib/exam-models';\nimport { getExamSkillCatalog, topicKey, type DifficultySelection } from '@/lib/exam-skill-catalog';")
t=t.replace("function choosePriority(candidates:RoadmapPriority[],week:number){if(!candidates.length)return undefined;const max=Math.max(...candidates.map(p=>p.score),.01);const weighted=candidates.flatMap(p=>Array.from({length:Math.max(1,Math.min(4,Math.round((p.score/max)*4)))},()=>p));return weighted[(week-1)%weighted.length]??candidates[0]}", "function choosePriority(candidates:RoadmapPriority[],week:number,boost:(p:RoadmapPriority)=>number){if(!candidates.length)return undefined;const effective=candidates.map(p=>({p,s:p.score*boost(p)}));const max=Math.max(...effective.map(x=>x.s),.01);const weighted=effective.flatMap(({p,s})=>Array.from({length:Math.max(1,Math.min(6,Math.round((s/max)*5)))},()=>p));return weighted[(week-1)%weighted.length]??candidates[0]}")
t=t.replace("export function buildRoadmap(args:{model:ExamModel;course:string;priorities:RoadmapPriority[];weeklyHours:number;questions:RoadmapQuestion[];today?:Date}){", "export function buildRoadmap(args:{model:ExamModel;course:string;priorities:RoadmapPriority[];weeklyHours:number;questions:RoadmapQuestion[];difficultyTopics?:DifficultySelection;diagnostics?:{area:string;skill:string}[];today?:Date}){")
t=t.replace("  const{model,course,priorities,questions}=args;", "  const{model,course,priorities,questions}=args;const difficultyTopics=args.difficultyTopics??{};const diagnostics=args.diagnostics??[];const catalog=getExamSkillCatalog(model.examId,course);\n  const difficultyFor=(focus:string)=>catalog.subjects.flatMap(s=>s.topics.map(topic=>({subject:s.subject,area:s.area,topic,level:difficultyTopics[topicKey(s.subject,topic)]??0}))).filter(x=>x.level>0&&(matchArea(x.area,focus)||matchArea(x.subject,focus))).sort((a,b)=>b.level-a.level);\n  const diagnosticFor=(focus:string)=>diagnostics.filter(d=>matchArea(d.area,focus));")
t=t.replace("const p=choosePriority(candidates,i+1);if(!p)continue;const baseKey=p.metric.key.replace('2ª fase — ','');const pool=topicPools", "const p=choosePriority(candidates,i+1,x=>{const key=x.metric.key.replace('2ª fase — ','');const manual=difficultyFor(key);const scans=diagnosticFor(key);return 1+Math.min(.75,manual.reduce((a,b)=>a+b.level,0)*.08)+Math.min(.35,scans.length*.1)});if(!p)continue;const baseKey=p.metric.key.replace('2ª fase — ','');const pool=topicPools")
old="const topic=pool[Math.floor(i/Math.max(1,candidates.length))%pool.length];const relevant=questions.filter(q=>matchArea(q.area,baseKey));"
new="const manual=difficultyFor(baseKey);const scans=diagnosticFor(baseKey);const manualTopic=manual.length?manual[i%Math.min(manual.length,4)]?.topic:null;const scanTopic=scans.length?scans[i%scans.length]?.skill:null;const topic=manualTopic||scanTopic||pool[Math.floor(i/Math.max(1,candidates.length))%pool.length];const relevant=questions.filter(q=>matchArea(q.area,baseKey));"
t=t.replace(old,new)
old2="const rationale=`${p.metric.label} foi priorizada porque faltam ${p.missing} ${p.metric.unit==='acertos'?'acertos':'pontos'} para a meta${p.accuracy!=null?` e seu desempenho recente está em ${Math.round(p.accuracy*100)}%`:''}.`;"
new2="const rationale=`${p.metric.label} foi priorizada porque faltam ${p.missing} ${p.metric.unit==='acertos'?'acertos':'pontos'} para a meta${p.accuracy!=null?` e seu desempenho recente está em ${Math.round(p.accuracy*100)}%`:''}${manualTopic?'; você marcou este tópico como dificuldade':''}${scanTopic&&!manualTopic?'; um diagnóstico recente também apontou dificuldade aqui':''}.`;"
t=t.replace(old2,new2)
r.write_text(t)
print('adaptive difficulty matrix integrated')
