-- Expands the official skill map and authorial practice corpus for Insper and Link.
with skills(exam_id,area,skill_code,skill_name,parent_skill,importance,diagnostic_tags) as (
  values
  ('insper','Linguagens','INSP-LANG-VAR','Variação linguística e registro','Língua Portuguesa',1.10,array['registro','variação','adequação']::text[]),
  ('insper','Linguagens','INSP-LANG-SINT','Sintaxe, pontuação e relações de sentido','Língua Portuguesa',1.20,array['sintaxe','pontuação','conectivos']::text[]),
  ('insper','Linguagens','INSP-LANG-COES','Coesão, coerência e progressão textual','Língua Portuguesa',1.25,array['coesão','coerência','progressão']::text[]),
  ('insper','Linguagens','INSP-LIT','Literatura e contexto histórico-cultural','Língua Portuguesa',1.05,array['literatura','intertextualidade','contexto']::text[]),
  ('insper','Matemática','INSP-FIN','Porcentagem e matemática financeira','Matemática',1.30,array['porcentagem','juros','taxas']::text[]),
  ('insper','Matemática','INSP-COMB','Análise combinatória e contagem','Matemática',1.25,array['contagem','permutação','combinação']::text[]),
  ('insper','Matemática','INSP-PROB','Probabilidade simples e condicional','Matemática',1.30,array['probabilidade','condicional','eventos']::text[]),
  ('insper','Matemática','INSP-GEO-ESP','Geometria espacial e medidas','Matemática',1.15,array['volume','área','sólidos']::text[]),
  ('insper','Matemática','INSP-DADOS','Estatística, boxplot e dispersão','Matemática',1.30,array['boxplot','variância','desvio padrão','gráficos']::text[]),
  ('insper','Natureza','INSP-BIO-GEN','Genética, biologia molecular e biotecnologia','Biologia',1.15,array['genética','DNA','biotecnologia']::text[]),
  ('insper','Natureza','INSP-BIO-ECO','Ecologia, ciclos e impactos ambientais','Biologia',1.10,array['ecologia','ciclos','impacto ambiental']::text[]),
  ('insper','Natureza','INSP-FIS-MEC','Mecânica, energia e interpretação experimental','Física',1.15,array['mecânica','energia','experimento']::text[]),
  ('insper','Natureza','INSP-FIS-ELE','Eletricidade, circuitos e magnetismo','Física',1.10,array['circuito','potência','eletricidade']::text[]),
  ('insper','Natureza','INSP-QUI-EST','Estequiometria, gases e soluções','Química',1.15,array['mol','estequiometria','soluções']::text[]),
  ('insper','Natureza','INSP-QUI-EQ','Equilíbrio, ácidos, bases e eletroquímica','Química',1.10,array['equilíbrio','pH','eletroquímica']::text[]),
  ('insper','Humanas','INSP-HIST','Processos históricos e cidadania','História',1.10,array['história','cidadania','causa e consequência']::text[]),
  ('insper','Humanas','INSP-GEOP','Geopolítica, território e globalização','Geografia',1.15,array['geopolítica','território','globalização']::text[]),
  ('insper','Humanas','INSP-SOC','Cultura, trabalho, desigualdade e poder','Sociologia',1.10,array['sociologia','desigualdade','poder']::text[]),
  ('insper','Redação','INSP-RED-COES','Coerência global e coesão entre partes','Redação',1.30,array['coesão','coerência','progressão']::text[]),
  ('insper','Redação','INSP-RED-LING','Linguagem, registro e precisão','Redação',1.20,array['norma-padrão','registro','precisão']::text[]),
  ('link','Portfólio','LINK-ACADEMIC','Evidências de desempenho e curiosidade acadêmica','PREP',1.25,array['acadêmico','curiosidade','evidência']::text[]),
  ('link','Portfólio','LINK-IMPACT','Impacto demonstrado com métricas e evidências','PREP',1.40,array['impacto','métricas','portfólio']::text[]),
  ('link','Portfólio','LINK-COHERENCE','Coerência entre trajetória, ambição e propósito','PREP',1.35,array['trajetória','propósito','coerência']::text[]),
  ('link','Oral','LINK-VIDEO-SCRIPT','Roteiro de vídeo com gancho, evidência e fechamento','PREP',1.35,array['vídeo','roteiro','storytelling']::text[]),
  ('link','Matemática','LINK-RATES','Razão, porcentagem, taxas e estimativas','SPRINT',1.35,array['porcentagem','taxas','estimativa']::text[]),
  ('link','Matemática','LINK-GRAPHS','Leitura de gráficos e indicadores de negócio','SPRINT',1.35,array['gráfico','indicador','dados']::text[]),
  ('link','Business Case','LINK-PROBLEM','Causa, sintoma e definição do problema','SPRINT',1.50,array['problema','causa','sintoma']::text[]),
  ('link','Business Case','LINK-CUSTOMER','Cliente, mercado, concorrência e posicionamento','SPRINT',1.40,array['cliente','mercado','concorrência']::text[]),
  ('link','Business Case','LINK-TRADEOFF','Trade-offs, riscos e priorização','SPRINT',1.45,array['trade-off','risco','priorização']::text[]),
  ('link','Business Case','LINK-EXPERIMENT','Experimentos, implementação e indicadores','SPRINT',1.40,array['experimento','implementação','KPI']::text[]),
  ('link','Escrita','LINK-MEMO','Síntese executiva e resposta ao comando','SPRINT',1.40,array['síntese','memo','comando']::text[]),
  ('link','Escrita','LINK-WRITTEN-RISK','Argumentação com dados, riscos e próximos passos','SPRINT',1.40,array['dados','riscos','próximos passos']::text[]),
  ('link','Oral','LINK-PITCH-DATA','Pitch sustentado por dados e recomendação','SPRINT',1.40,array['pitch','dados','recomendação']::text[]),
  ('link','Oral','LINK-OBJECTION','Resposta a objeções e defesa de escolhas','SPRINT',1.30,array['objeção','defesa','decisão']::text[]),
  ('link','Entrevista','LINK-STAR','Respostas comportamentais no formato STAR','Entrevista',1.35,array['STAR','comportamental','evidência']::text[]),
  ('link','Entrevista','LINK-LEARNING','Fracasso, feedback e aprendizado','Entrevista',1.30,array['fracasso','feedback','aprendizado']::text[]),
  ('link','Entrevista','LINK-ETHICS','Ética, impacto e alinhamento com a missão','Entrevista',1.30,array['ética','impacto','missão']::text[]),
  ('link','Entrevista','LINK-ENGLISH','Prontidão para comunicação em inglês','Entrevista',1.10,array['inglês','comunicação','entrevista']::text[])
), numbered as (
  select s.*, coalesce((select max(id) from public.exam_skill_taxonomy),0)+row_number() over () as new_id from skills s
)
insert into public.exam_skill_taxonomy(id,exam_id,area,skill_code,skill_name,parent_skill,importance,diagnostic_tags)
select new_id,exam_id,area,skill_code,skill_name,parent_skill,importance,diagnostic_tags from numbered
on conflict (exam_id,skill_code) do update set area=excluded.area,skill_name=excluded.skill_name,parent_skill=excluded.parent_skill,importance=excluded.importance,diagnostic_tags=excluded.diagnostic_tags;

insert into public.exam_ai_skill_reference(exam_id,skill_code,area,skill_name,scope,diagnostic_tags,parent_skill_code,source_kind,source_label,source_url,source_version,official_reference,updated_at)
select t.exam_id,t.skill_code,t.area,t.skill_name,
  case when t.exam_id='insper' then 'Reconhecer e diagnosticar '||t.skill_name||' no conteúdo programático e no padrão de resolução do Vestibular Insper.' else 'Reconhecer e diagnosticar '||t.skill_name||' na etapa adequada da Jornada Link, exigindo evidência, decisão e comunicação.' end,
  t.diagnostic_tags,null,'official_reference',
  case when t.exam_id='insper' then 'Insper — Conteúdos Programáticos Vestibular 2027.1' else 'Link School of Business — Processo Seletivo' end,
  case when t.exam_id='insper' then 'https://www.insper.edu.br/pt/cursos/vestibular' else 'https://lsb.edu.br/pt-br/adm' end,
  '2027.1',true,now()
from public.exam_skill_taxonomy t where t.exam_id in ('insper','link')
on conflict (exam_id,skill_code) do update set area=excluded.area,skill_name=excluded.skill_name,scope=excluded.scope,diagnostic_tags=excluded.diagnostic_tags,source_label=excluded.source_label,source_url=excluded.source_url,source_version=excluded.source_version,official_reference=excluded.official_reference,updated_at=now();

with questions(exam_id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,estimated_minutes) as (
 values
 ('insper','Matemática','Porcentagem e matemática financeira',2,'Uma mensalidade de R$ 2.000 recebe desconto de 10% e depois reajuste de 10% sobre o valor descontado. Qual é o valor final?','R$ 1.800','R$ 1.980','R$ 2.000','R$ 2.020','R$ 2.200','B','Os fatores sucessivos são 0,90 e 1,10. Logo, 2.000 × 0,90 × 1,10 = 1.980.',3),
 ('insper','Matemática','Probabilidade simples e condicional',3,'Em uma turma, 60% estudam inglês, 40% estudam espanhol e 20% estudam ambos. Escolhido um aluno que estuda inglês, qual a probabilidade de ele também estudar espanhol?','20%','25%','33,3%','40%','50%','C','P(espanhol | inglês) = P(ambos)/P(inglês) = 0,20/0,60 = 1/3.',4),
 ('insper','Matemática','Estatística, boxplot e dispersão',3,'Dois conjuntos têm a mesma média. O conjunto A tem desvio padrão 2 e o B, desvio padrão 7. Qual conclusão é correta?','A tem maior amplitude necessariamente','B tem valores mais dispersos em torno da média','A tem maior mediana necessariamente','B tem média maior','Os conjuntos são idênticos','B','O maior desvio padrão indica maior dispersão dos valores em torno da média; não determina sozinho amplitude ou mediana.',3),
 ('insper','Matemática','Funções e modelagem quantitativa',3,'Uma empresa tem custo C(x)=1200+18x e receita R(x)=30x. A partir de quantas unidades inteiras há lucro positivo?','99','100','101','120','121','C','Lucro positivo exige 30x > 1200+18x, então 12x > 1200 e x > 100. A primeira quantidade inteira é 101.',4),
 ('insper','Matemática','Análise combinatória e contagem',3,'Quantas senhas de três algarismos distintos podem ser formadas com 1, 2, 3, 4 e 5?','10','15','20','60','125','D','Há 5 escolhas para a primeira posição, 4 para a segunda e 3 para a terceira: 5×4×3=60.',3),
 ('insper','Linguagens','Coesão, coerência e progressão textual',2,'Em “A empresa reduziu preços. Portanto, esperava ampliar as vendas”, o conectivo “portanto” estabelece relação de:','oposição','conclusão','explicação','condição','alternância','B','“Portanto” introduz uma conclusão decorrente da informação anterior.',2),
 ('insper','Linguagens','Variação linguística e registro',2,'Em uma entrevista de emprego, substituir “a gente vai tá fazendo” por “nós faremos” exemplifica principalmente:','mudança de tema','adequação do registro à situação comunicativa','eliminação de regionalismo obrigatório','correção de ambiguidade lexical','uso de linguagem figurada','B','As duas formas comunicam ideia semelhante, mas a segunda se ajusta ao registro formal esperado na situação.',2),
 ('insper','Linguagens','Sintaxe, pontuação e relações de sentido',3,'Assinale a frase em que a vírgula altera corretamente o sentido ao marcar uma explicação sobre todos os alunos.','Os alunos que estudaram passaram.','Os alunos, que estudaram, passaram.','Os alunos que, estudaram passaram.','Os, alunos que estudaram passaram.','Os alunos que estudaram, passaram.','B','As vírgulas tornam a oração “que estudaram” explicativa, atribuindo a informação ao conjunto inteiro dos alunos.',3),
 ('insper','Humanas','Geopolítica, território e globalização',3,'Quando uma empresa distribui pesquisa, produção e montagem por países diferentes, o fenômeno exemplifica:','autarquia econômica','fragmentação internacional da produção','fim da divisão do trabalho','isolamento regional','desurbanização','B','A cadeia produtiva é fragmentada territorialmente segundo custos, competências e mercados de diferentes países.',3),
 ('insper','Humanas','Cultura, trabalho, desigualdade e poder',2,'O conceito de mobilidade social descreve:','a migração diária entre casa e trabalho','a mudança de posição de indivíduos ou grupos na estrutura social','a circulação de mercadorias entre países','a substituição do Estado pelo mercado','a expansão física das cidades','B','Mobilidade social é a mudança de posição na estratificação social, ascendente ou descendente.',2),
 ('insper','Humanas','Processos históricos e cidadania',3,'A ampliação histórica do direito ao voto é melhor compreendida como:','processo linear sem conflitos','resultado de disputas sociais e mudanças institucionais','efeito exclusivo do crescimento econômico','eliminação automática das desigualdades','negação da representação política','B','Direitos políticos foram ampliados por disputas, mobilizações e reformas institucionais, sem eliminar automaticamente outras desigualdades.',3),
 ('insper','Natureza','Genética, biologia molecular e biotecnologia',3,'Em um cruzamento Aa × Aa, qual a probabilidade de um descendente ter genótipo aa?','0%','25%','50%','75%','100%','B','O quadro de Punnett produz AA, Aa, Aa e aa; um dos quatro resultados é aa.',3),
 ('insper','Natureza','Ecologia, ciclos e impactos ambientais',3,'A retirada de um predador de topo tende, inicialmente, a:','reduzir todas as populações igualmente','alterar populações de presas e desencadear efeitos em cascata','aumentar a energia disponível em cada nível trófico','interromper a fotossíntese','eliminar a competição intraespecífica','B','Predadores de topo regulam presas; sua retirada pode aumentar essas populações e repercutir nos demais níveis da teia.',3),
 ('insper','Natureza','Mecânica, energia e interpretação experimental',2,'Um carro percorre 120 km em 2 horas e depois 60 km em 1 hora. Sua velocidade média no percurso total é:','45 km/h','60 km/h','75 km/h','90 km/h','180 km/h','B','A distância total é 180 km e o tempo total é 3 h; portanto, 180/3=60 km/h.',3),
 ('insper','Natureza','Eletricidade, circuitos e magnetismo',3,'Um aparelho de 1.000 W funciona por 3 horas. A energia consumida é:','0,3 kWh','1 kWh','3 kWh','30 kWh','3.000 kWh','C','1.000 W correspondem a 1 kW; em 3 h, o consumo é 1×3=3 kWh.',3),
 ('insper','Natureza','Estequiometria, gases e soluções',3,'Quantos mols existem em 36 g de água, cuja massa molar é 18 g/mol?','0,5','1','2','18','36','C','n=m/M=36/18=2 mol.',2),
 ('insper','Redação','Recorte do tema e tese explícita',3,'Qual abertura apresenta uma tese mais precisa para o tema “uso de dados pessoais por empresas”?','Dados existem desde sempre.','A tecnologia é boa e ruim.','A coleta de dados pode melhorar serviços, mas exige transparência e limites para proteger a autonomia do usuário.','Muitas empresas usam a internet.','Esse assunto é muito polêmico.','C','A alternativa C delimita o tema e assume uma posição discutível, com dois eixos claros: benefícios e limites.',3),
 ('insper','Redação','Argumentos, evidências e repertório produtivo',3,'Em um parágrafo argumentativo, uma estatística é produtiva quando:','substitui a tese','é citada sem fonte nem interpretação','é explicada e conectada à afirmação defendida','aparece apenas na conclusão','contradiz o argumento principal','C','A evidência precisa ser interpretada e ligada logicamente à tese; sozinha, não constitui argumento completo.',3),
 ('insper','Redação','Coerência global e coesão entre partes',3,'Qual sequência organiza melhor um parágrafo argumentativo?','exemplo → título → tema','tópico frasal → explicação → evidência → fechamento','conclusão → pergunta → citação solta','repertório → saudação → tese nova','lista → contradição → repetição','B','Essa sequência apresenta a ideia, desenvolve sua lógica, sustenta-a e fecha o raciocínio sem romper a progressão.',3),
 ('insper','Redação','Linguagem, registro e precisão',2,'Qual frase é mais adequada ao registro formal de uma redação?','A galera não tá nem aí para isso.','Esse negócio dá ruim demais.','A ausência de transparência reduz a capacidade de escolha dos cidadãos.','Tipo assim, ninguém entende nada.','As empresas meio que exageram.','C','A alternativa C usa vocabulário preciso, construção formal e relação causal clara.',2),
 ('link','Matemática','Razão, porcentagem, taxas e estimativas',2,'Uma startup tinha 800 clientes e cresceu 25%. Quantos clientes passou a ter?','825','900','1.000','1.025','1.200','C','25% de 800 são 200; o novo total é 1.000.',2),
 ('link','Matemática','Leitura de gráficos e indicadores de negócio',3,'A receita cresceu de R$ 100 mil para R$ 130 mil, enquanto os custos cresceram de R$ 80 mil para R$ 120 mil. O que ocorreu com o lucro?','cresceu R$ 30 mil','cresceu R$ 10 mil','ficou igual','caiu R$ 10 mil','caiu R$ 20 mil','D','O lucro foi de R$ 20 mil para R$ 10 mil, portanto caiu R$ 10 mil.',3),
 ('link','Matemática','Unit economics e lógica de negócios',3,'Um produto é vendido por R$ 120, tem custo variável de R$ 70 e CAC de R$ 30. Desconsiderando custos fixos, qual a contribuição após aquisição?','R$ 20','R$ 30','R$ 50','R$ 70','R$ 90','A','120−70−30=20 reais de contribuição por cliente adquirido.',3),
 ('link','Business Case','Causa, sintoma e definição do problema',3,'Um aplicativo perdeu usuários ativos após aumentar o tempo de carregamento. Qual formulação é a melhor hipótese inicial?','O marketing deve mudar de cor.','A lentidão pode estar elevando o abandono antes da conclusão das tarefas.','Todos os usuários deixaram de gostar da marca.','A empresa deve contratar mais vendedores.','O mercado deixou de existir.','B','A hipótese conecta um fato observado a um mecanismo mensurável e pode ser testada com dados de carregamento e abandono.',3),
 ('link','Business Case','Hipóteses, árvore de problemas e priorização',4,'Uma loja online teve queda de receita. Qual decomposição é mais útil para iniciar a análise?','receita = clima × opinião','receita = tráfego × conversão × ticket médio','receita = funcionários + reuniões','receita = custos fixos − impostos','receita = seguidores ÷ anúncios','B','A identidade permite localizar se a queda vem de aquisição, conversão ou valor por pedido.',4),
 ('link','Business Case','Cliente, mercado, concorrência e posicionamento',3,'Antes de recomendar entrada em um novo segmento, qual dado é mais decisivo?','cor favorita do fundador','tamanho e crescimento do segmento, necessidade do cliente e capacidade de atender','número de slides da apresentação','idade do prédio da empresa','quantidade de reuniões realizadas','B','A decisão exige atratividade do mercado, dor real e aderência das capacidades da empresa.',3),
 ('link','Business Case','Trade-offs, riscos e priorização',4,'Uma solução tem alto impacto esperado, baixo custo e risco reversível. Em uma matriz impacto × esforço, ela tende a ser:','descartada','prioridade rápida para teste','adiada indefinidamente','tratada como custo afundado','implementada sem medir','B','Alto impacto e baixo esforço justificam priorização, mas o resultado ainda deve ser testado e medido.',3),
 ('link','Business Case','Experimentos, implementação e indicadores',4,'Para testar se frete grátis aumenta conversão sem destruir margem, o melhor primeiro passo é:','oferecer a todos para sempre','fazer teste controlado, definir conversão e margem por pedido e comparar grupos','perguntar apenas ao fundador','ignorar custos logísticos','medir somente curtidas','B','Um experimento controlado com métricas de benefício e custo permite avaliar causalidade e viabilidade.',4),
 ('link','Business Case','Criatividade com viabilidade e impacto',3,'Qual recomendação é mais completa?','Criar um aplicativo porque aplicativos são modernos.','Reduzir preços sem calcular efeitos.','Pilotar assinatura em um segmento, com meta de retenção, teto de CAC e revisão em 30 dias.','Copiar integralmente um concorrente.','Aguardar sem coletar dados.','C','A proposta combina ideia, público, indicadores, restrição econômica e prazo de aprendizado.',3),
 ('link','Escrita','Síntese executiva e resposta ao comando',3,'Qual primeira frase funciona melhor em uma recomendação executiva?','Desde o início dos tempos, empresas decidem.','Há muitos pontos para pensar e talvez algo possa ser feito.','Recomendamos testar o canal B por quatro semanas, pois ele tem menor CAC e retenção semelhante ao canal A.','Meu grupo gostou bastante da ideia.','O case foi muito interessante.','C','A frase responde ao comando, apresenta decisão, prazo e evidência decisiva.',3),
 ('link','Escrita','Argumentação com dados, riscos e próximos passos',4,'Depois de recomendar uma expansão, qual fechamento fortalece mais a entrega?','Vai dar certo.','Não há risco algum.','O principal risco é baixa retenção; por isso, o piloto terá meta mínima de 60% no mês 2 antes da escala.','Precisamos de mais slides.','A concorrência não importa.','C','O fechamento nomeia o risco, define mitigação e cria um critério mensurável para decidir a escala.',3),
 ('link','Oral','Roteiro de vídeo com gancho, evidência e fechamento',2,'Em um vídeo curto de apresentação pessoal, qual estrutura é mais eficaz?','lista de adjetivos sem exemplos','nome, experiência concreta, aprendizado e conexão com a Link','leitura integral do currículo','piada longa e despedida','apenas notas escolares','B','A estrutura é concisa, traz evidência e conecta a trajetória à motivação específica.',2),
 ('link','Oral','Pitch sustentado por dados e recomendação',3,'Ao apresentar um business case em vídeo, o candidato deve priorizar:','repetir todos os dados','declarar a recomendação, explicar os dois dados decisivos e indicar risco/próximo passo','usar termos técnicos sem definição','esconder incertezas','falar o mais rápido possível','B','Um pitch forte seleciona o raciocínio decisivo e mostra capacidade de decisão e implementação.',3),
 ('link','Oral','Resposta a objeções e defesa de escolhas',4,'Diante da objeção “seu plano pode reduzir a margem”, qual resposta é mais sólida?','Isso não vai acontecer.','Você não entendeu o case.','É um risco real; por isso proponho teto de desconto e teste com margem mínima antes de escalar.','Margem não importa.','Vamos mudar de assunto.','C','A resposta reconhece a objeção e oferece controle mensurável, sem abandonar a recomendação.',3),
 ('link','Portfólio','Impacto demonstrado com métricas e evidências',3,'Qual descrição de portfólio demonstra melhor impacto?','Participei de um projeto legal.','Ajudei bastante minha equipe.','Coordenei cinco voluntários e elevamos de 40 para 95 as inscrições em seis semanas.','Sempre fui muito proativo.','Tenho perfil de liderança.','C','A alternativa apresenta papel, escala, resultado mensurável e prazo.',2),
 ('link','Portfólio','Coerência entre trajetória, ambição e propósito',3,'Qual conexão com a Link é menos genérica?','Quero estudar aí porque é uma faculdade boa.','Gosto de negócios desde criança.','Ao validar um projeto de reciclagem, percebi que preciso aprofundar experimentação e gestão para ampliar impacto; é essa prática que busco na Link.','Meus amigos também vão prestar.','A localização parece conveniente.','C','A resposta liga uma experiência específica a uma lacuna de desenvolvimento e ao modelo de aprendizagem buscado.',3),
 ('link','Entrevista','Respostas comportamentais no formato STAR',3,'Ao responder “conte uma situação em que liderou”, qual elemento não pode faltar?','apenas a opinião sobre liderança','uma situação, sua responsabilidade, ações específicas e resultado/aprendizado','uma definição de dicionário','nomes de líderes famosos','uma lista de qualidades','B','O formato STAR exige contexto, tarefa, ação atribuível ao candidato e resultado verificável.',3),
 ('link','Entrevista','Fracasso, feedback e aprendizado',3,'Qual resposta demonstra maior maturidade sobre um fracasso?','Nunca fracassei.','A culpa foi inteiramente da equipe.','Subestimei o prazo, comuniquei tarde e perdi a entrega; depois passei a quebrar marcos e sinalizar riscos semanalmente.','Prefiro não falar disso.','O resultado não teve importância.','C','A resposta assume responsabilidade, mostra diagnóstico e apresenta mudança concreta de comportamento.',3),
 ('link','Entrevista','Ética, impacto e alinhamento com a missão',4,'Uma solução aumenta receita, mas depende de esconder uma taxa do cliente. Qual decisão é mais defensável?','lançar porque receita é a única métrica','esconder melhor a taxa','rejeitar o desenho e testar uma alternativa transparente, medindo receita e confiança','culpar o setor jurídico','copiar concorrentes','C','A alternativa integra resultado econômico, transparência e sustentabilidade da relação com o cliente.',3),
 ('link','Entrevista','Prontidão para comunicação em inglês',2,'Asked “Why do you want to study business?”, which answer is clearest?','Because yes.','Business is nice and I like things.','I want to learn how to test ideas and build sustainable solutions, based on my experience leading a school project.','No comments.','Everybody studies business.','C','The answer states a goal and supports it with a concrete experience.',2)
)
insert into public.exam_practice_questions(exam_id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,estimated_minutes,source_basis,active)
select q.exam_id,q.area,q.skill_name,q.difficulty,q.prompt,q.option_a,q.option_b,q.option_c,q.option_d,q.option_e,q.correct_option,q.explanation,q.estimated_minutes,
  case when q.exam_id='insper' then 'Questão autoral Conectaê alinhada ao conteúdo programático oficial do Insper 2027.1' else 'Questão autoral Conectaê alinhada às etapas oficiais PREP, SPRINT e entrevista da Link' end,true
from questions q where not exists(select 1 from public.exam_practice_questions e where e.exam_id=q.exam_id and e.prompt=q.prompt);
