create table if not exists public.admission_phase_drills (
  id bigint generated by default as identity primary key,
  exam_id text not null,
  phase text not null,
  competency text not null,
  title text not null,
  prompt text not null,
  instructions text not null default '',
  rubric jsonb not null default '[]'::jsonb,
  time_limit_minutes integer not null default 5 check (time_limit_minutes between 1 and 120),
  response_mode text not null default 'text' check (response_mode in ('text','video','oral','group','portfolio','case','math')),
  source_basis text not null default 'Treino autoral alinhado ao formato público do processo seletivo',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists admission_phase_drills_exam_phase_idx on public.admission_phase_drills(exam_id,phase);
create unique index if not exists admission_phase_drills_unique_prompt_idx on public.admission_phase_drills(exam_id,phase,title,prompt);

alter table public.admission_phase_drills enable row level security;
drop policy if exists "public read admission phase drills" on public.admission_phase_drills;
create policy "public read admission phase drills" on public.admission_phase_drills for select to anon, authenticated using (active = true);

-- Seed content is generated and applied to production separately so the UI can
-- grow without relabelling authorial simulations as official exam questions.
