-- Applied to production as Supabase migration 20261006151059.
-- Full audit hardening: safe grants, anonymous analytics, rate limiting, RLS performance and indexes.

DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('REVOKE TRUNCATE, REFERENCES, TRIGGER ON TABLE public.%I FROM anon, authenticated', t.tablename);
  END LOOP;
END $$;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE TRUNCATE, REFERENCES, TRIGGER ON TABLES FROM anon, authenticated;

REVOKE ALL PRIVILEGES ON TABLE public.analytics_events FROM anon;
GRANT INSERT ON TABLE public.analytics_events TO anon;

CREATE TABLE IF NOT EXISTS public.api_rate_limit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket text NOT NULL,
  subject_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.api_rate_limit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.api_rate_limit_events FROM public, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.api_rate_limit_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.api_rate_limit_events_id_seq TO service_role;
CREATE INDEX IF NOT EXISTS api_rate_limit_events_lookup_idx
  ON public.api_rate_limit_events(bucket, subject_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS essay_corrections_reviewer_id_idx ON public.essay_corrections(reviewer_id);
CREATE INDEX IF NOT EXISTS essay_corrections_submission_id_idx ON public.essay_corrections(submission_id);
CREATE INDEX IF NOT EXISTS essay_course_materials_module_id_idx ON public.essay_course_materials(module_id);
CREATE INDEX IF NOT EXISTS essay_course_progress_module_id_idx ON public.essay_course_progress(module_id);
CREATE INDEX IF NOT EXISTS essay_reviewers_assigned_by_idx ON public.essay_reviewers(assigned_by);
CREATE INDEX IF NOT EXISTS essay_submissions_reviewer_id_idx ON public.essay_submissions(reviewer_id);
CREATE INDEX IF NOT EXISTS student_exam_route_scores_area_university_id_idx ON public.student_exam_route_scores(area_university_id);

DO $$
DECLARE
  r record;
  q text;
  wc text;
BEGIN
  FOR r IN
    SELECT p.*
    FROM pg_policies p
    JOIN (VALUES
      ('essay_correctors','corrector can read own role'),
      ('essay_submissions','students read own submissions'),
      ('essay_submissions','students insert own submissions'),
      ('essay_submissions','correctors read all submissions'),
      ('essay_submissions','correctors review submissions'),
      ('student_exam_route_scores','route_scores_update_own'),
      ('student_exam_route_scores','route_scores_delete_own'),
      ('essay_reviewers','read_own_reviewer_role'),
      ('student_exam_route_scores','route_scores_select_own'),
      ('essay_reviewers','admin_read_all_reviewers'),
      ('essay_reviewers','admin_insert_reviewers'),
      ('essay_reviewers','admin_delete_reviewers'),
      ('essay_course_access','read_own_essay_access'),
      ('student_exam_route_scores','route_scores_insert_own'),
      ('essay_course_access','admin_read_essay_access'),
      ('essay_submissions','select_own_essay_submissions'),
      ('essay_submissions','insert_own_essay_submissions'),
      ('essay_corrections','select_own_essay_corrections')
    ) AS wanted(tablename, policyname)
      ON wanted.tablename = p.tablename AND wanted.policyname = p.policyname
    WHERE p.schemaname = 'public'
  LOOP
    q := r.qual;
    wc := r.with_check;
    IF q IS NOT NULL THEN
      q := replace(replace(q, 'auth.uid()', '(select auth.uid())'), 'auth.jwt()', '(select auth.jwt())');
    END IF;
    IF wc IS NOT NULL THEN
      wc := replace(replace(wc, 'auth.uid()', '(select auth.uid())'), 'auth.jwt()', '(select auth.jwt())');
    END IF;

    IF r.cmd = 'INSERT' THEN
      EXECUTE format('ALTER POLICY %I ON public.%I WITH CHECK (%s)', r.policyname, r.tablename, wc);
    ELSIF r.cmd IN ('SELECT','DELETE') THEN
      EXECUTE format('ALTER POLICY %I ON public.%I USING (%s)', r.policyname, r.tablename, q);
    ELSE
      IF q IS NOT NULL AND wc IS NOT NULL THEN
        EXECUTE format('ALTER POLICY %I ON public.%I USING (%s) WITH CHECK (%s)', r.policyname, r.tablename, q, wc);
      ELSIF q IS NOT NULL THEN
        EXECUTE format('ALTER POLICY %I ON public.%I USING (%s)', r.policyname, r.tablename, q);
      ELSIF wc IS NOT NULL THEN
        EXECUTE format('ALTER POLICY %I ON public.%I WITH CHECK (%s)', r.policyname, r.tablename, wc);
      END IF;
    END IF;
  END LOOP;
END $$;

ALTER FUNCTION public.has_essay_course_access() SECURITY INVOKER;
ALTER FUNCTION public.is_essay_reviewer() SECURITY INVOKER;

REVOKE ALL ON FUNCTION public.redeem_essay_course_access(text) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_essay_course_access(text) TO service_role;

UPDATE public.sharing_consents
SET consent_status = 'declined',
    consent_scope = 'none',
    consent_revoked_at = COALESCE(consent_revoked_at, now()),
    guardian_consent_given = false,
    guardian_consent_given_at = null,
    updated_at = now(),
    privacy_policy_version = '1.1'
WHERE requires_guardian_consent = true
  AND guardian_consent_given = false
  AND consent_status = 'accepted';
