begin;
alter table public.universities add column if not exists country_code text not null default 'BR';
update public.universities set country_code = 'BR' where country_code is null or country_code = '';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'universities_country_code_check') then
    alter table public.universities add constraint universities_country_code_check check (country_code in ('BR','US'));
  end if;
end $$;
create index if not exists universities_country_code_idx on public.universities (country_code);

insert into public.universities (university_id,name,course,location,format,positioning,program_differentiators,admissions,values,high_fit_student,low_fit_student,match_rationale,primary_source_url,image_url,country_code) values
('US_UPENN_WHARTON','University of Pennsylvania — Wharton','Bachelor of Science in Economics','Philadelphia, Pennsylvania, EUA','Presencial, integral, 4 anos','Business school de elite com forte base quantitativa, finanças, liderança, inovação e integração entre negócios e artes liberais.','Currículo flexível com fundamentos de negócios, economia, cálculo, estatística e escrita crítica; concentrações em áreas como finanças, analytics, empreendedorismo e gestão; acesso interdisciplinar às demais escolas da Penn.','O candidato se inscreve diretamente para Wharton pela candidatura de graduação da University of Pennsylvania. A avaliação é holística e considera rigor acadêmico, trajetória, redações, atividades e contribuição potencial à comunidade.','Rigor, liderança, impacto, inovação, perspectiva global, flexibilidade intelectual, colaboração e excelência quantitativa.','Aluno academicamente muito forte, quantitativo, ambicioso, articulado, global e com evidências consistentes de liderança, iniciativa e impacto.','Aluno que evita matemática, alta exigência, competição, exposição de ideias ou uma formação que mistura negócios com disciplinas de artes e ciências.','O perfil combina rigor quantitativo e de escrita com liderança, amplitude intelectual, atuação global, finanças e aplicação de negócios a problemas reais.','https://undergrad.wharton.upenn.edu/',null,'US'),
('US_MIT_SLOAN','Massachusetts Institute of Technology — MIT Sloan','BS in Management, Business Analytics ou Finance','Cambridge, Massachusetts, EUA','Presencial, integral, 4 anos','Formação de negócios profundamente quantitativa e tecnológica, integrada ao ecossistema de ciência, engenharia, inovação e empreendedorismo do MIT.','Três majors de Course 15; fundamentos em probabilidade, estatística, microeconomia, contabilidade, comunicação e comportamento organizacional; alta flexibilidade e conexão com laboratórios e startups do MIT.','O candidato se inscreve para o MIT, não diretamente para Sloan. Após ingressar no instituto, escolhe o major normalmente no segundo ano; a seleção do MIT é holística e valoriza preparo acadêmico, colaboração, iniciativa e aderência à missão.','Rigor analítico, ciência, tecnologia, curiosidade, colaboração, experimentação, execução, empreendedorismo e resolução de problemas complexos.','Aluno excepcional em matemática e análise, curioso, construtor, colaborativo e interessado em tecnologia, dados, finanças, inovação ou startups.','Aluno que evita matemática avançada, programação, ciência, problemas abertos ou um ambiente acadêmico de intensidade muito alta.','MIT Sloan exige forte raciocínio quantitativo e oferece negócios dentro de um ecossistema tecnológico, experimental e empreendedor singular.','https://mitsloan.mit.edu/programs/undergraduate',null,'US'),
('US_BERKELEY_HAAS','University of California, Berkeley — Haas','Spieker Undergraduate Business Program','Berkeley, California, EUA','Presencial, integral, 4 anos','Business pública de elite com cultura inovadora, empreendedora, socialmente consciente e ligada ao ecossistema tecnológico da Bay Area.','Programa Spieker de quatro anos; integração com Berkeley; forte presença de inovação, liderança, empreendedorismo, dados e perspectivas globais; princípios de liderança próprios da Haas.','Alunos do ensino médio podem se candidatar diretamente ao Spieker. Haas informa que avalia holisticamente notas e rigor das disciplinas, redações, atividades e prêmios, além de aderência aos princípios de liderança da escola.','Questionar o status quo, confiança sem arrogância, aprendizado contínuo, impacto além de si, inovação e inclusão.','Aluno forte academicamente, curioso, inovador, colaborativo, empreendedor e comprometido com impacto social, tecnologia ou mudança organizacional.','Aluno que prefere estruturas rígidas, evita ambiguidade ou não se identifica com colaboração, inovação e responsabilidade social.','O fit privilegia excelência acadêmica combinada a inovação, iniciativa, propósito, mentalidade global e liderança sem arrogância.','https://haas.berkeley.edu/undergrad/',null,'US'),
('US_MICHIGAN_ROSS','University of Michigan — Ross','Bachelor of Business Administration (BBA)','Ann Arbor, Michigan, EUA','Presencial, integral, 4 anos','BBA de elite orientado a ação, liderança, carreira e aplicação prática, dentro de uma experiência universitária completa e altamente participativa.','REAL — Ross Experiences in Action-Based Learning; projetos com empresas, desafios empreendedores e experiências globais; forte comunidade de cohort e amplo campus da University of Michigan.','O candidato pode selecionar Ross como unidade de admissão no primeiro ano pela Common Application. A candidatura inclui quatro redações e o Ross Admissions Portfolio, além da avaliação geral da University of Michigan.','Aprender fazendo, liderança, colaboração, excelência, impacto, diversidade, comunidade e preparação profissional.','Aluno líder, comunicativo, colaborativo e academicamente forte que deseja projetos reais, forte recrutamento e vida de campus intensa.','Aluno que prefere aprendizado passivo, pouca interação em grupo ou uma experiência urbana sem vida universitária tradicional.','Ross se diferencia por ação prática, liderança, trabalho em equipe, comunidade e preparação direta para carreira.','https://michiganross.umich.edu/undergraduate/bba',null,'US'),
('US_NYU_STERN','New York University — Stern','Bachelor of Science in Business','New York, New York, EUA','Presencial, integral, 4 anos','Business global e urbana, fortemente conectada a finanças, mercados, tecnologia, mídia e oportunidades profissionais em Nova York.','BS em Business STEM-designated; 12 áreas de concentração, trilhas interdisciplinares e base de artes liberais; exposição direta a empresas e organizações de Nova York.','O candidato seleciona um dos programas de graduação de Stern na candidatura à NYU. A avaliação considera histórico acadêmico, redações, atividades e contexto pessoal conforme o processo holístico da universidade.','Ambição, diversidade, perspectiva global, excelência profissional, responsabilidade social, inovação e conexão com o mercado.','Aluno independente, global, orientado a carreira, finanças ou tecnologia, que valoriza networking, ritmo urbano e acesso frequente a empresas.','Aluno que busca campus isolado e tradicional, ritmo mais lento ou pouca exposição a competição, networking e vida urbana.','Stern favorece perfis globais e independentes que buscam finanças, mercado, tecnologia e aprendizagem conectada a Nova York.','https://www.stern.nyu.edu/programs-admissions/undergraduate',null,'US'),
('US_UT_MCCOMBS','University of Texas at Austin — McCombs','Bachelor of Business Administration (BBA)','Austin, Texas, EUA','Presencial, integral, 4 anos','Business pública de grande escala, forte em finanças, analytics, tecnologia, empreendedorismo e carreira, conectada ao ecossistema de Austin.','Diversos majors, incluindo Finance, Business Analytics, MIS, Marketing e International Business; Canfield Business Honors; vida estudantil ampla e forte relação com empresas.','O candidato se inscreve para UT Austin e escolhe Business como primeira opção. McCombs informa que não exige candidatura adicional, exceto para Honors, admite apenas no outono e registrou taxa de aceitação de 9% no BBA em 2025.','Inovação, espírito empreendedor, análise, ética, liderança, impacto, diversidade e desenvolvimento profissional.','Aluno pragmático, analítico, empreendedor e orientado a carreira que busca campus grande, tecnologia, finanças e oportunidades em Austin.','Aluno que prefere ambiente muito pequeno, pouco estruturado ou sem foco em carreira, análise quantitativa e vida de campus.','McCombs combina escala, experiência universitária, tecnologia, analytics, finanças, empreendedorismo e forte empregabilidade.','https://www.mccombs.utexas.edu/undergraduate-programs/bba/',null,'US'),
('US_CMU_TEPPER','Carnegie Mellon University — Tepper','BS in Business Administration','Pittsburgh, Pennsylvania, EUA','Presencial, integral, 4 anos','Business quantitativa e tecnológica, com forte integração a computação, inteligência artificial, analytics, economia e resolução de problemas.','Core em negócios, economia, matemática, comunicação e artes liberais; concentração funcional e minor obrigatório fora de Tepper; acesso ao ecossistema de computação, robótica e engenharia da CMU.','O candidato se inscreve para Carnegie Mellon escolhendo Tepper. A preparação recomendada inclui quatro anos de matemática, preferencialmente cálculo, além de formação sólida em ciências, inglês e idioma estrangeiro.','Rigor analítico, inovação, tecnologia, liderança, colaboração, aplicação prática, criatividade e impacto responsável.','Aluno muito quantitativo, interessado em tecnologia, IA, dados e negócios, que gosta de projetos complexos e integração entre áreas.','Aluno que evita matemática, tecnologia ou programação e prefere uma formação de negócios pouco analítica.','Tepper é especialmente aderente a perfis que combinam negócios, matemática, analytics, tecnologia e solução aplicada de problemas.','https://www.cmu.edu/tepper/programs/undergraduate-programs/business-administration',null,'US'),
('US_CORNELL_DYSON','Cornell University — Dyson','BS in Applied Economics and Management','Ithaca, New York, EUA','Presencial, integral, 4 anos','Formação rigorosa em economia aplicada e gestão, com forte base quantitativa, finanças, ética, sustentabilidade e solução de desafios sociais.','Core de micro e macroeconomia, contabilidade e gestão; econometria e análise quantitativa; concentrações; Grand Challenges e experiências de service learning; integração com Cornell.','O candidato se inscreve para o programa de Applied Economics and Management da Cornell SC Johnson College of Business. A seleção da Cornell é holística e exige forte preparação acadêmica e aderência ao propósito do curso.','Rigor, ética, sustentabilidade, impacto, economia aplicada, colaboração, visão global, serviço e excelência profissional.','Aluno academicamente forte, quantitativo e global que quer unir economia, negócios, finanças e impacto social ou ambiental.','Aluno que evita economia, matemática, teoria ou temas de ética, sustentabilidade e impacto.','Dyson combina economia e gestão de alta exigência com aplicação prática, finanças, ética e propósito.','https://business.cornell.edu/programs/bs-aem/',null,'US'),
('US_INDIANA_KELLEY','Indiana University Bloomington — Kelley','Bachelor of Science in Business','Bloomington, Indiana, EUA','Presencial, integral, 4 anos','Business de grande escala com currículo prático, ampla escolha de majors, carreira estruturada, networking e experiência universitária tradicional.','20 majors e co-majors; currículo baseado em experiência; Integrated Core; forte preparação profissional, organizações estudantis e grande rede de alumni.','O estudante se candidata à IU Bloomington. Candidatos podem receber admissão direta a Kelley; quem entra como pre-business pode buscar standard admission após o primeiro ano ao cumprir os critérios acadêmicos e de candidatura vigentes.','Experiência prática, profissionalismo, colaboração, desenvolvimento de carreira, iniciativa, diversidade de caminhos e comunidade.','Aluno sociável, orientado a carreira e networking, que busca muitas opções acadêmicas, vida de campus e preparação profissional estruturada.','Aluno que prefere turma muito pequena, experiência urbana ou currículo altamente experimental e pouco estruturado.','Kelley se destaca para perfis que valorizam experiência, empregabilidade, amplitude de majors, networking e campus tradicional.','https://kelley.iu.edu/undergraduate/index.html',null,'US'),
('US_UNC_KENAN','University of North Carolina at Chapel Hill — Kenan-Flagler','Bachelor of Science in Business Administration','Chapel Hill, North Carolina, EUA','Presencial, integral; ingresso no major após etapa universitária ou via pathway garantido','Business rigorosa, colaborativa e orientada a liderança, estratégia, resolução de problemas e experiência global dentro de um campus público tradicional.','Currículo interdisciplinar com 11 disciplinas de core, eletivas de negócios e fora da área; forte rede de alumni; oportunidades globais, liderança e carreira.','Parte dos candidatos de ensino médio pode receber o pathway Future Business Admits, que garante entrada no programa no segundo ano após pré-requisitos. Os demais podem se candidatar ao Undergraduate Business Program depois de iniciar a graduação na UNC.','Liderança, colaboração, integridade, excelência, comunidade, pensamento estratégico, serviço e perspectiva global.','Aluno completo, líder e colaborativo que valoriza campus, comunidade, estratégia, carreira e oportunidades internacionais.','Aluno que rejeita trabalho em equipe, vida de campus ou a possibilidade de precisar passar por uma etapa adicional para entrar no major.','Kenan-Flagler combina rigor, liderança, solução de problemas, forte comunidade, experiência global e campus tradicional.','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/',null,'US'),
('US_USC_MARSHALL','University of Southern California — Marshall','BS in Business Administration','Los Angeles, California, EUA','Presencial, integral, 4 anos','Business global, prática e empreendedora, conectada a Los Angeles, tecnologia, mídia, inovação, networking e carreiras internacionais.','BS em Business Administration com designação STEM; ênfases em empreendedorismo, marketing, business analytics, comunicação e real estate finance; opções interdisciplinares com engenharia e cinema.','O candidato se inscreve para USC escolhendo um programa de graduação de Marshall. A avaliação da USC é holística e considera desempenho acadêmico, redações, atividades, contexto e potencial de contribuição.','Inovação, empreendedorismo, diversidade, perspectiva global, colaboração, ética, comunicação e transformação de ideias em resultados.','Aluno comunicativo, global, empreendedor e orientado a networking que busca negócios ligados a tecnologia, mídia, criatividade ou mercados internacionais.','Aluno que prefere pouca exposição social, ambiente isolado, baixa conexão com mercado ou formação muito teórica.','Marshall favorece perfis globais, criativos e empreendedores que querem aplicação prática, interdisciplinaridade e conexão com Los Angeles.','https://www.marshall.usc.edu/programs/undergraduate-programs',null,'US')
on conflict (university_id) do update set name=excluded.name,course=excluded.course,location=excluded.location,format=excluded.format,positioning=excluded.positioning,program_differentiators=excluded.program_differentiators,admissions=excluded.admissions,values=excluded.values,high_fit_student=excluded.high_fit_student,low_fit_student=excluded.low_fit_student,match_rationale=excluded.match_rationale,primary_source_url=excluded.primary_source_url,image_url=excluded.image_url,country_code=excluded.country_code;

insert into public.university_dimension_weights (university_id,dimension_id,weight) values
('US_UPENN_WHARTON','academic_perf',100),
('US_UPENN_WHARTON','achievement_selectivity',94),
('US_UPENN_WHARTON','analytical_data',91),
('US_UPENN_WHARTON','autonomy_selfdirection',90),
('US_UPENN_WHARTON','brand_prestige',100),
('US_UPENN_WHARTON','conflict_handling',89),
('US_UPENN_WHARTON','corporate_management',92),
('US_UPENN_WHARTON','critical_thinking',94),
('US_UPENN_WHARTON','curiosity_learning',94),
('US_UPENN_WHARTON','decision_uncertainty',90),
('US_UPENN_WHARTON','english_level',100),
('US_UPENN_WHARTON','entrepreneurial_intent',88),
('US_UPENN_WHARTON','entrepreneurial_proof',90),
('US_UPENN_WHARTON','experimental_learning',87),
('US_UPENN_WHARTON','extracurricular_depth',95),
('US_UPENN_WHARTON','finance_markets',100),
('US_UPENN_WHARTON','global_mindset',99),
('US_UPENN_WHARTON','initiative_history',94),
('US_UPENN_WHARTON','leadership_evidence',97),
('US_UPENN_WHARTON','market_employability',100),
('US_UPENN_WHARTON','math_quant',97),
('US_UPENN_WHARTON','mobility_willingness',100),
('US_UPENN_WHARTON','networking_value',99),
('US_UPENN_WHARTON','oral_pitch',91),
('US_UPENN_WHARTON','portfolio_depth',94),
('US_UPENN_WHARTON','practical_learning',91),
('US_UPENN_WHARTON','problem_solving',95),
('US_UPENN_WHARTON','project_execution',93),
('US_UPENN_WHARTON','purpose_impact',93),
('US_UPENN_WHARTON','resilience_pressure',94),
('US_UPENN_WHARTON','rigor_depth',100),
('US_UPENN_WHARTON','startup_founder_fit',87),
('US_UPENN_WHARTON','student_life_traditional',92),
('US_UPENN_WHARTON','teamwork_collab',94),
('US_UPENN_WHARTON','tech_ai_orientation',91),
('US_UPENN_WHARTON','theory_comfort',96),
('US_UPENN_WHARTON','time_discipline',95),
('US_UPENN_WHARTON','work_experience',90),
('US_UPENN_WHARTON','writing_argument',97),
('US_MIT_SLOAN','academic_perf',100),
('US_MIT_SLOAN','achievement_selectivity',94),
('US_MIT_SLOAN','analytical_data',100),
('US_MIT_SLOAN','autonomy_selfdirection',90),
('US_MIT_SLOAN','brand_prestige',100),
('US_MIT_SLOAN','conflict_handling',89),
('US_MIT_SLOAN','corporate_management',92),
('US_MIT_SLOAN','critical_thinking',94),
('US_MIT_SLOAN','curiosity_learning',100),
('US_MIT_SLOAN','decision_uncertainty',96),
('US_MIT_SLOAN','english_level',100),
('US_MIT_SLOAN','entrepreneurial_intent',96),
('US_MIT_SLOAN','entrepreneurial_proof',90),
('US_MIT_SLOAN','experimental_learning',97),
('US_MIT_SLOAN','extracurricular_depth',95),
('US_MIT_SLOAN','finance_markets',90),
('US_MIT_SLOAN','global_mindset',97),
('US_MIT_SLOAN','initiative_history',94),
('US_MIT_SLOAN','leadership_evidence',94),
('US_MIT_SLOAN','market_employability',96),
('US_MIT_SLOAN','math_quant',100),
('US_MIT_SLOAN','mobility_willingness',100),
('US_MIT_SLOAN','networking_value',95),
('US_MIT_SLOAN','oral_pitch',91),
('US_MIT_SLOAN','portfolio_depth',94),
('US_MIT_SLOAN','practical_learning',91),
('US_MIT_SLOAN','problem_solving',100),
('US_MIT_SLOAN','project_execution',93),
('US_MIT_SLOAN','purpose_impact',88),
('US_MIT_SLOAN','resilience_pressure',94),
('US_MIT_SLOAN','rigor_depth',100),
('US_MIT_SLOAN','startup_founder_fit',97),
('US_MIT_SLOAN','student_life_traditional',82),
('US_MIT_SLOAN','teamwork_collab',94),
('US_MIT_SLOAN','tech_ai_orientation',100),
('US_MIT_SLOAN','theory_comfort',98),
('US_MIT_SLOAN','time_discipline',95),
('US_MIT_SLOAN','work_experience',90),
('US_MIT_SLOAN','writing_argument',88),
('US_BERKELEY_HAAS','academic_perf',98),
('US_BERKELEY_HAAS','achievement_selectivity',94),
('US_BERKELEY_HAAS','analytical_data',91),
('US_BERKELEY_HAAS','autonomy_selfdirection',90),
('US_BERKELEY_HAAS','brand_prestige',99),
('US_BERKELEY_HAAS','conflict_handling',89),
('US_BERKELEY_HAAS','corporate_management',92),
('US_BERKELEY_HAAS','critical_thinking',99),
('US_BERKELEY_HAAS','curiosity_learning',94),
('US_BERKELEY_HAAS','decision_uncertainty',90),
('US_BERKELEY_HAAS','english_level',100),
('US_BERKELEY_HAAS','entrepreneurial_intent',97),
('US_BERKELEY_HAAS','entrepreneurial_proof',90),
('US_BERKELEY_HAAS','experimental_learning',95),
('US_BERKELEY_HAAS','extracurricular_depth',95),
('US_BERKELEY_HAAS','finance_markets',90),
('US_BERKELEY_HAAS','global_mindset',98),
('US_BERKELEY_HAAS','initiative_history',97),
('US_BERKELEY_HAAS','leadership_evidence',97),
('US_BERKELEY_HAAS','market_employability',96),
('US_BERKELEY_HAAS','math_quant',91),
('US_BERKELEY_HAAS','mobility_willingness',100),
('US_BERKELEY_HAAS','networking_value',95),
('US_BERKELEY_HAAS','oral_pitch',91),
('US_BERKELEY_HAAS','portfolio_depth',94),
('US_BERKELEY_HAAS','practical_learning',91),
('US_BERKELEY_HAAS','problem_solving',95),
('US_BERKELEY_HAAS','project_execution',93),
('US_BERKELEY_HAAS','purpose_impact',98),
('US_BERKELEY_HAAS','resilience_pressure',94),
('US_BERKELEY_HAAS','rigor_depth',95),
('US_BERKELEY_HAAS','startup_founder_fit',97),
('US_BERKELEY_HAAS','student_life_traditional',92),
('US_BERKELEY_HAAS','teamwork_collab',94),
('US_BERKELEY_HAAS','tech_ai_orientation',97),
('US_BERKELEY_HAAS','theory_comfort',91),
('US_BERKELEY_HAAS','time_discipline',95),
('US_BERKELEY_HAAS','work_experience',90),
('US_BERKELEY_HAAS','writing_argument',93),
('US_MICHIGAN_ROSS','academic_perf',97),
('US_MICHIGAN_ROSS','achievement_selectivity',94),
('US_MICHIGAN_ROSS','analytical_data',91),
('US_MICHIGAN_ROSS','autonomy_selfdirection',90),
('US_MICHIGAN_ROSS','brand_prestige',94),
('US_MICHIGAN_ROSS','conflict_handling',89),
('US_MICHIGAN_ROSS','corporate_management',98),
('US_MICHIGAN_ROSS','critical_thinking',94),
('US_MICHIGAN_ROSS','curiosity_learning',94),
('US_MICHIGAN_ROSS','decision_uncertainty',90),
('US_MICHIGAN_ROSS','english_level',100),
('US_MICHIGAN_ROSS','entrepreneurial_intent',88),
('US_MICHIGAN_ROSS','entrepreneurial_proof',90),
('US_MICHIGAN_ROSS','experimental_learning',87),
('US_MICHIGAN_ROSS','extracurricular_depth',95),
('US_MICHIGAN_ROSS','finance_markets',90),
('US_MICHIGAN_ROSS','global_mindset',96),
('US_MICHIGAN_ROSS','initiative_history',94),
('US_MICHIGAN_ROSS','leadership_evidence',98),
('US_MICHIGAN_ROSS','market_employability',99),
('US_MICHIGAN_ROSS','math_quant',91),
('US_MICHIGAN_ROSS','mobility_willingness',100),
('US_MICHIGAN_ROSS','networking_value',95),
('US_MICHIGAN_ROSS','oral_pitch',97),
('US_MICHIGAN_ROSS','portfolio_depth',98),
('US_MICHIGAN_ROSS','practical_learning',100),
('US_MICHIGAN_ROSS','problem_solving',95),
('US_MICHIGAN_ROSS','project_execution',100),
('US_MICHIGAN_ROSS','purpose_impact',88),
('US_MICHIGAN_ROSS','resilience_pressure',94),
('US_MICHIGAN_ROSS','rigor_depth',95),
('US_MICHIGAN_ROSS','startup_founder_fit',87),
('US_MICHIGAN_ROSS','student_life_traditional',100),
('US_MICHIGAN_ROSS','teamwork_collab',99),
('US_MICHIGAN_ROSS','tech_ai_orientation',91),
('US_MICHIGAN_ROSS','theory_comfort',91),
('US_MICHIGAN_ROSS','time_discipline',95),
('US_MICHIGAN_ROSS','work_experience',97),
('US_MICHIGAN_ROSS','writing_argument',93),
('US_NYU_STERN','academic_perf',94),
('US_NYU_STERN','achievement_selectivity',94),
('US_NYU_STERN','analytical_data',91),
('US_NYU_STERN','autonomy_selfdirection',98),
('US_NYU_STERN','brand_prestige',99),
('US_NYU_STERN','conflict_handling',89),
('US_NYU_STERN','corporate_management',99),
('US_NYU_STERN','critical_thinking',94),
('US_NYU_STERN','curiosity_learning',94),
('US_NYU_STERN','decision_uncertainty',90),
('US_NYU_STERN','english_level',100),
('US_NYU_STERN','entrepreneurial_intent',88),
('US_NYU_STERN','entrepreneurial_proof',90),
('US_NYU_STERN','experimental_learning',87),
('US_NYU_STERN','extracurricular_depth',95),
('US_NYU_STERN','finance_markets',100),
('US_NYU_STERN','global_mindset',100),
('US_NYU_STERN','initiative_history',94),
('US_NYU_STERN','leadership_evidence',94),
('US_NYU_STERN','market_employability',100),
('US_NYU_STERN','math_quant',91),
('US_NYU_STERN','mobility_willingness',100),
('US_NYU_STERN','networking_value',100),
('US_NYU_STERN','oral_pitch',91),
('US_NYU_STERN','portfolio_depth',94),
('US_NYU_STERN','practical_learning',95),
('US_NYU_STERN','problem_solving',95),
('US_NYU_STERN','project_execution',93),
('US_NYU_STERN','purpose_impact',88),
('US_NYU_STERN','resilience_pressure',98),
('US_NYU_STERN','rigor_depth',95),
('US_NYU_STERN','startup_founder_fit',87),
('US_NYU_STERN','student_life_traditional',62),
('US_NYU_STERN','teamwork_collab',94),
('US_NYU_STERN','tech_ai_orientation',96),
('US_NYU_STERN','theory_comfort',91),
('US_NYU_STERN','time_discipline',95),
('US_NYU_STERN','work_experience',98),
('US_NYU_STERN','writing_argument',93),
('US_UT_MCCOMBS','academic_perf',96),
('US_UT_MCCOMBS','achievement_selectivity',94),
('US_UT_MCCOMBS','analytical_data',97),
('US_UT_MCCOMBS','autonomy_selfdirection',90),
('US_UT_MCCOMBS','brand_prestige',97),
('US_UT_MCCOMBS','conflict_handling',89),
('US_UT_MCCOMBS','corporate_management',97),
('US_UT_MCCOMBS','critical_thinking',94),
('US_UT_MCCOMBS','curiosity_learning',94),
('US_UT_MCCOMBS','decision_uncertainty',90),
('US_UT_MCCOMBS','english_level',100),
('US_UT_MCCOMBS','entrepreneurial_intent',95),
('US_UT_MCCOMBS','entrepreneurial_proof',90),
('US_UT_MCCOMBS','experimental_learning',87),
('US_UT_MCCOMBS','extracurricular_depth',95),
('US_UT_MCCOMBS','finance_markets',98),
('US_UT_MCCOMBS','global_mindset',97),
('US_UT_MCCOMBS','initiative_history',94),
('US_UT_MCCOMBS','leadership_evidence',94),
('US_UT_MCCOMBS','market_employability',98),
('US_UT_MCCOMBS','math_quant',91),
('US_UT_MCCOMBS','mobility_willingness',100),
('US_UT_MCCOMBS','networking_value',97),
('US_UT_MCCOMBS','oral_pitch',91),
('US_UT_MCCOMBS','portfolio_depth',94),
('US_UT_MCCOMBS','practical_learning',96),
('US_UT_MCCOMBS','problem_solving',95),
('US_UT_MCCOMBS','project_execution',93),
('US_UT_MCCOMBS','purpose_impact',88),
('US_UT_MCCOMBS','resilience_pressure',94),
('US_UT_MCCOMBS','rigor_depth',95),
('US_UT_MCCOMBS','startup_founder_fit',95),
('US_UT_MCCOMBS','student_life_traditional',100),
('US_UT_MCCOMBS','teamwork_collab',94),
('US_UT_MCCOMBS','tech_ai_orientation',97),
('US_UT_MCCOMBS','theory_comfort',91),
('US_UT_MCCOMBS','time_discipline',95),
('US_UT_MCCOMBS','work_experience',90),
('US_UT_MCCOMBS','writing_argument',93),
('US_CMU_TEPPER','academic_perf',99),
('US_CMU_TEPPER','achievement_selectivity',94),
('US_CMU_TEPPER','analytical_data',100),
('US_CMU_TEPPER','autonomy_selfdirection',90),
('US_CMU_TEPPER','brand_prestige',94),
('US_CMU_TEPPER','conflict_handling',89),
('US_CMU_TEPPER','corporate_management',92),
('US_CMU_TEPPER','critical_thinking',99),
('US_CMU_TEPPER','curiosity_learning',94),
('US_CMU_TEPPER','decision_uncertainty',90),
('US_CMU_TEPPER','english_level',100),
('US_CMU_TEPPER','entrepreneurial_intent',93),
('US_CMU_TEPPER','entrepreneurial_proof',90),
('US_CMU_TEPPER','experimental_learning',96),
('US_CMU_TEPPER','extracurricular_depth',95),
('US_CMU_TEPPER','finance_markets',90),
('US_CMU_TEPPER','global_mindset',97),
('US_CMU_TEPPER','initiative_history',94),
('US_CMU_TEPPER','leadership_evidence',94),
('US_CMU_TEPPER','market_employability',96),
('US_CMU_TEPPER','math_quant',100),
('US_CMU_TEPPER','mobility_willingness',100),
('US_CMU_TEPPER','networking_value',95),
('US_CMU_TEPPER','oral_pitch',91),
('US_CMU_TEPPER','portfolio_depth',94),
('US_CMU_TEPPER','practical_learning',91),
('US_CMU_TEPPER','problem_solving',100),
('US_CMU_TEPPER','project_execution',97),
('US_CMU_TEPPER','purpose_impact',88),
('US_CMU_TEPPER','resilience_pressure',94),
('US_CMU_TEPPER','rigor_depth',99),
('US_CMU_TEPPER','startup_founder_fit',87),
('US_CMU_TEPPER','student_life_traditional',88),
('US_CMU_TEPPER','teamwork_collab',94),
('US_CMU_TEPPER','tech_ai_orientation',100),
('US_CMU_TEPPER','theory_comfort',97),
('US_CMU_TEPPER','time_discipline',95),
('US_CMU_TEPPER','work_experience',90),
('US_CMU_TEPPER','writing_argument',90),
('US_CORNELL_DYSON','academic_perf',99),
('US_CORNELL_DYSON','achievement_selectivity',94),
('US_CORNELL_DYSON','analytical_data',98),
('US_CORNELL_DYSON','autonomy_selfdirection',90),
('US_CORNELL_DYSON','brand_prestige',99),
('US_CORNELL_DYSON','conflict_handling',89),
('US_CORNELL_DYSON','corporate_management',92),
('US_CORNELL_DYSON','critical_thinking',98),
('US_CORNELL_DYSON','curiosity_learning',94),
('US_CORNELL_DYSON','decision_uncertainty',90),
('US_CORNELL_DYSON','english_level',100),
('US_CORNELL_DYSON','entrepreneurial_intent',88),
('US_CORNELL_DYSON','entrepreneurial_proof',90),
('US_CORNELL_DYSON','experimental_learning',87),
('US_CORNELL_DYSON','extracurricular_depth',95),
('US_CORNELL_DYSON','finance_markets',97),
('US_CORNELL_DYSON','global_mindset',98),
('US_CORNELL_DYSON','initiative_history',94),
('US_CORNELL_DYSON','leadership_evidence',94),
('US_CORNELL_DYSON','market_employability',98),
('US_CORNELL_DYSON','math_quant',98),
('US_CORNELL_DYSON','mobility_willingness',100),
('US_CORNELL_DYSON','networking_value',95),
('US_CORNELL_DYSON','oral_pitch',91),
('US_CORNELL_DYSON','portfolio_depth',94),
('US_CORNELL_DYSON','practical_learning',95),
('US_CORNELL_DYSON','problem_solving',95),
('US_CORNELL_DYSON','project_execution',93),
('US_CORNELL_DYSON','purpose_impact',100),
('US_CORNELL_DYSON','resilience_pressure',94),
('US_CORNELL_DYSON','rigor_depth',99),
('US_CORNELL_DYSON','startup_founder_fit',87),
('US_CORNELL_DYSON','student_life_traditional',98),
('US_CORNELL_DYSON','teamwork_collab',94),
('US_CORNELL_DYSON','tech_ai_orientation',91),
('US_CORNELL_DYSON','theory_comfort',98),
('US_CORNELL_DYSON','time_discipline',95),
('US_CORNELL_DYSON','work_experience',90),
('US_CORNELL_DYSON','writing_argument',93),
('US_INDIANA_KELLEY','academic_perf',91),
('US_INDIANA_KELLEY','achievement_selectivity',94),
('US_INDIANA_KELLEY','analytical_data',91),
('US_INDIANA_KELLEY','autonomy_selfdirection',82),
('US_INDIANA_KELLEY','brand_prestige',94),
('US_INDIANA_KELLEY','conflict_handling',89),
('US_INDIANA_KELLEY','corporate_management',97),
('US_INDIANA_KELLEY','critical_thinking',94),
('US_INDIANA_KELLEY','curiosity_learning',94),
('US_INDIANA_KELLEY','decision_uncertainty',90),
('US_INDIANA_KELLEY','english_level',100),
('US_INDIANA_KELLEY','entrepreneurial_intent',88),
('US_INDIANA_KELLEY','entrepreneurial_proof',90),
('US_INDIANA_KELLEY','experimental_learning',82),
('US_INDIANA_KELLEY','extracurricular_depth',95),
('US_INDIANA_KELLEY','finance_markets',96),
('US_INDIANA_KELLEY','global_mindset',97),
('US_INDIANA_KELLEY','initiative_history',94),
('US_INDIANA_KELLEY','leadership_evidence',94),
('US_INDIANA_KELLEY','market_employability',98),
('US_INDIANA_KELLEY','math_quant',91),
('US_INDIANA_KELLEY','mobility_willingness',100),
('US_INDIANA_KELLEY','networking_value',98),
('US_INDIANA_KELLEY','oral_pitch',95),
('US_INDIANA_KELLEY','portfolio_depth',94),
('US_INDIANA_KELLEY','practical_learning',98),
('US_INDIANA_KELLEY','problem_solving',95),
('US_INDIANA_KELLEY','project_execution',93),
('US_INDIANA_KELLEY','purpose_impact',88),
('US_INDIANA_KELLEY','resilience_pressure',94),
('US_INDIANA_KELLEY','rigor_depth',95),
('US_INDIANA_KELLEY','startup_founder_fit',87),
('US_INDIANA_KELLEY','student_life_traditional',100),
('US_INDIANA_KELLEY','teamwork_collab',97),
('US_INDIANA_KELLEY','tech_ai_orientation',91),
('US_INDIANA_KELLEY','theory_comfort',91),
('US_INDIANA_KELLEY','time_discipline',95),
('US_INDIANA_KELLEY','work_experience',96),
('US_INDIANA_KELLEY','writing_argument',93),
('US_UNC_KENAN','academic_perf',95),
('US_UNC_KENAN','achievement_selectivity',94),
('US_UNC_KENAN','analytical_data',91),
('US_UNC_KENAN','autonomy_selfdirection',90),
('US_UNC_KENAN','brand_prestige',94),
('US_UNC_KENAN','conflict_handling',89),
('US_UNC_KENAN','corporate_management',92),
('US_UNC_KENAN','critical_thinking',97),
('US_UNC_KENAN','curiosity_learning',94),
('US_UNC_KENAN','decision_uncertainty',90),
('US_UNC_KENAN','english_level',100),
('US_UNC_KENAN','entrepreneurial_intent',88),
('US_UNC_KENAN','entrepreneurial_proof',90),
('US_UNC_KENAN','experimental_learning',87),
('US_UNC_KENAN','extracurricular_depth',97),
('US_UNC_KENAN','finance_markets',90),
('US_UNC_KENAN','global_mindset',96),
('US_UNC_KENAN','initiative_history',97),
('US_UNC_KENAN','leadership_evidence',98),
('US_UNC_KENAN','market_employability',97),
('US_UNC_KENAN','math_quant',91),
('US_UNC_KENAN','mobility_willingness',100),
('US_UNC_KENAN','networking_value',95),
('US_UNC_KENAN','oral_pitch',91),
('US_UNC_KENAN','portfolio_depth',94),
('US_UNC_KENAN','practical_learning',96),
('US_UNC_KENAN','problem_solving',97),
('US_UNC_KENAN','project_execution',93),
('US_UNC_KENAN','purpose_impact',94),
('US_UNC_KENAN','resilience_pressure',94),
('US_UNC_KENAN','rigor_depth',95),
('US_UNC_KENAN','startup_founder_fit',87),
('US_UNC_KENAN','student_life_traditional',100),
('US_UNC_KENAN','teamwork_collab',99),
('US_UNC_KENAN','tech_ai_orientation',91),
('US_UNC_KENAN','theory_comfort',91),
('US_UNC_KENAN','time_discipline',95),
('US_UNC_KENAN','work_experience',90),
('US_UNC_KENAN','writing_argument',93),
('US_USC_MARSHALL','academic_perf',94),
('US_USC_MARSHALL','achievement_selectivity',94),
('US_USC_MARSHALL','analytical_data',91),
('US_USC_MARSHALL','autonomy_selfdirection',90),
('US_USC_MARSHALL','brand_prestige',94),
('US_USC_MARSHALL','conflict_handling',89),
('US_USC_MARSHALL','corporate_management',92),
('US_USC_MARSHALL','critical_thinking',94),
('US_USC_MARSHALL','curiosity_learning',94),
('US_USC_MARSHALL','decision_uncertainty',90),
('US_USC_MARSHALL','english_level',100),
('US_USC_MARSHALL','entrepreneurial_intent',98),
('US_USC_MARSHALL','entrepreneurial_proof',90),
('US_USC_MARSHALL','experimental_learning',95),
('US_USC_MARSHALL','extracurricular_depth',95),
('US_USC_MARSHALL','finance_markets',90),
('US_USC_MARSHALL','global_mindset',100),
('US_USC_MARSHALL','initiative_history',94),
('US_USC_MARSHALL','leadership_evidence',96),
('US_USC_MARSHALL','market_employability',98),
('US_USC_MARSHALL','math_quant',91),
('US_USC_MARSHALL','mobility_willingness',100),
('US_USC_MARSHALL','networking_value',100),
('US_USC_MARSHALL','oral_pitch',98),
('US_USC_MARSHALL','portfolio_depth',94),
('US_USC_MARSHALL','practical_learning',98),
('US_USC_MARSHALL','problem_solving',95),
('US_USC_MARSHALL','project_execution',97),
('US_USC_MARSHALL','purpose_impact',88),
('US_USC_MARSHALL','resilience_pressure',94),
('US_USC_MARSHALL','rigor_depth',95),
('US_USC_MARSHALL','startup_founder_fit',97),
('US_USC_MARSHALL','student_life_traditional',96),
('US_USC_MARSHALL','teamwork_collab',94),
('US_USC_MARSHALL','tech_ai_orientation',96),
('US_USC_MARSHALL','theory_comfort',91),
('US_USC_MARSHALL','time_discipline',95),
('US_USC_MARSHALL','work_experience',90),
('US_USC_MARSHALL','writing_argument',94)
on conflict (university_id,dimension_id) do update set weight=excluded.weight;

insert into public.university_axis_targets (university_id,axis_id,target) values
('US_UPENN_WHARTON','axis_01_pratica_vs_teoria',68),
('US_UPENN_WHARTON','axis_02_corporativo_vs_founder',42),
('US_UPENN_WHARTON','axis_03_local_vs_global',98),
('US_UPENN_WHARTON','axis_04_estrutura_vs_autonomia',72),
('US_UPENN_WHARTON','axis_05_individual_vs_colaborativo',91),
('US_UPENN_WHARTON','axis_06_tradicional_vs_experimental',56),
('US_UPENN_WHARTON','axis_07_prova_vs_holistico',94),
('US_UPENN_WHARTON','axis_08_tecnico_vs_proposito',70),
('US_UPENN_WHARTON','axis_09_baixa_exposicao_vs_pitch',89),
('US_UPENN_WHARTON','axis_10_baixa_ia_vs_ia_tech',89),
('US_UPENN_WHARTON','axis_11_risco_baixo_vs_risco_alto',72),
('US_UPENN_WHARTON','axis_12_financas_baixa_vs_alta',100),
('US_MIT_SLOAN','axis_01_pratica_vs_teoria',80),
('US_MIT_SLOAN','axis_02_corporativo_vs_founder',76),
('US_MIT_SLOAN','axis_03_local_vs_global',98),
('US_MIT_SLOAN','axis_04_estrutura_vs_autonomia',90),
('US_MIT_SLOAN','axis_05_individual_vs_colaborativo',91),
('US_MIT_SLOAN','axis_06_tradicional_vs_experimental',94),
('US_MIT_SLOAN','axis_07_prova_vs_holistico',94),
('US_MIT_SLOAN','axis_08_tecnico_vs_proposito',42),
('US_MIT_SLOAN','axis_09_baixa_exposicao_vs_pitch',89),
('US_MIT_SLOAN','axis_10_baixa_ia_vs_ia_tech',100),
('US_MIT_SLOAN','axis_11_risco_baixo_vs_risco_alto',90),
('US_MIT_SLOAN','axis_12_financas_baixa_vs_alta',92),
('US_BERKELEY_HAAS','axis_01_pratica_vs_teoria',82),
('US_BERKELEY_HAAS','axis_02_corporativo_vs_founder',78),
('US_BERKELEY_HAAS','axis_03_local_vs_global',98),
('US_BERKELEY_HAAS','axis_04_estrutura_vs_autonomia',90),
('US_BERKELEY_HAAS','axis_05_individual_vs_colaborativo',91),
('US_BERKELEY_HAAS','axis_06_tradicional_vs_experimental',92),
('US_BERKELEY_HAAS','axis_07_prova_vs_holistico',94),
('US_BERKELEY_HAAS','axis_08_tecnico_vs_proposito',88),
('US_BERKELEY_HAAS','axis_09_baixa_exposicao_vs_pitch',89),
('US_BERKELEY_HAAS','axis_10_baixa_ia_vs_ia_tech',97),
('US_BERKELEY_HAAS','axis_11_risco_baixo_vs_risco_alto',88),
('US_BERKELEY_HAAS','axis_12_financas_baixa_vs_alta',80),
('US_MICHIGAN_ROSS','axis_01_pratica_vs_teoria',100),
('US_MICHIGAN_ROSS','axis_02_corporativo_vs_founder',48),
('US_MICHIGAN_ROSS','axis_03_local_vs_global',98),
('US_MICHIGAN_ROSS','axis_04_estrutura_vs_autonomia',66),
('US_MICHIGAN_ROSS','axis_05_individual_vs_colaborativo',100),
('US_MICHIGAN_ROSS','axis_06_tradicional_vs_experimental',82),
('US_MICHIGAN_ROSS','axis_07_prova_vs_holistico',94),
('US_MICHIGAN_ROSS','axis_08_tecnico_vs_proposito',62),
('US_MICHIGAN_ROSS','axis_09_baixa_exposicao_vs_pitch',98),
('US_MICHIGAN_ROSS','axis_10_baixa_ia_vs_ia_tech',89),
('US_MICHIGAN_ROSS','axis_11_risco_baixo_vs_risco_alto',72),
('US_MICHIGAN_ROSS','axis_12_financas_baixa_vs_alta',83),
('US_NYU_STERN','axis_01_pratica_vs_teoria',88),
('US_NYU_STERN','axis_02_corporativo_vs_founder',35),
('US_NYU_STERN','axis_03_local_vs_global',98),
('US_NYU_STERN','axis_04_estrutura_vs_autonomia',96),
('US_NYU_STERN','axis_05_individual_vs_colaborativo',91),
('US_NYU_STERN','axis_06_tradicional_vs_experimental',70),
('US_NYU_STERN','axis_07_prova_vs_holistico',94),
('US_NYU_STERN','axis_08_tecnico_vs_proposito',62),
('US_NYU_STERN','axis_09_baixa_exposicao_vs_pitch',96),
('US_NYU_STERN','axis_10_baixa_ia_vs_ia_tech',95),
('US_NYU_STERN','axis_11_risco_baixo_vs_risco_alto',78),
('US_NYU_STERN','axis_12_financas_baixa_vs_alta',100),
('US_UT_MCCOMBS','axis_01_pratica_vs_teoria',90),
('US_UT_MCCOMBS','axis_02_corporativo_vs_founder',65),
('US_UT_MCCOMBS','axis_03_local_vs_global',98),
('US_UT_MCCOMBS','axis_04_estrutura_vs_autonomia',68),
('US_UT_MCCOMBS','axis_05_individual_vs_colaborativo',91),
('US_UT_MCCOMBS','axis_06_tradicional_vs_experimental',75),
('US_UT_MCCOMBS','axis_07_prova_vs_holistico',88),
('US_UT_MCCOMBS','axis_08_tecnico_vs_proposito',62),
('US_UT_MCCOMBS','axis_09_baixa_exposicao_vs_pitch',89),
('US_UT_MCCOMBS','axis_10_baixa_ia_vs_ia_tech',98),
('US_UT_MCCOMBS','axis_11_risco_baixo_vs_risco_alto',82),
('US_UT_MCCOMBS','axis_12_financas_baixa_vs_alta',98),
('US_CMU_TEPPER','axis_01_pratica_vs_teoria',84),
('US_CMU_TEPPER','axis_02_corporativo_vs_founder',62),
('US_CMU_TEPPER','axis_03_local_vs_global',98),
('US_CMU_TEPPER','axis_04_estrutura_vs_autonomia',88),
('US_CMU_TEPPER','axis_05_individual_vs_colaborativo',91),
('US_CMU_TEPPER','axis_06_tradicional_vs_experimental',88),
('US_CMU_TEPPER','axis_07_prova_vs_holistico',94),
('US_CMU_TEPPER','axis_08_tecnico_vs_proposito',38),
('US_CMU_TEPPER','axis_09_baixa_exposicao_vs_pitch',89),
('US_CMU_TEPPER','axis_10_baixa_ia_vs_ia_tech',100),
('US_CMU_TEPPER','axis_11_risco_baixo_vs_risco_alto',84),
('US_CMU_TEPPER','axis_12_financas_baixa_vs_alta',90),
('US_CORNELL_DYSON','axis_01_pratica_vs_teoria',70),
('US_CORNELL_DYSON','axis_02_corporativo_vs_founder',45),
('US_CORNELL_DYSON','axis_03_local_vs_global',98),
('US_CORNELL_DYSON','axis_04_estrutura_vs_autonomia',73),
('US_CORNELL_DYSON','axis_05_individual_vs_colaborativo',91),
('US_CORNELL_DYSON','axis_06_tradicional_vs_experimental',58),
('US_CORNELL_DYSON','axis_07_prova_vs_holistico',94),
('US_CORNELL_DYSON','axis_08_tecnico_vs_proposito',100),
('US_CORNELL_DYSON','axis_09_baixa_exposicao_vs_pitch',89),
('US_CORNELL_DYSON','axis_10_baixa_ia_vs_ia_tech',88),
('US_CORNELL_DYSON','axis_11_risco_baixo_vs_risco_alto',72),
('US_CORNELL_DYSON','axis_12_financas_baixa_vs_alta',96),
('US_INDIANA_KELLEY','axis_01_pratica_vs_teoria',96),
('US_INDIANA_KELLEY','axis_02_corporativo_vs_founder',36),
('US_INDIANA_KELLEY','axis_03_local_vs_global',98),
('US_INDIANA_KELLEY','axis_04_estrutura_vs_autonomia',58),
('US_INDIANA_KELLEY','axis_05_individual_vs_colaborativo',98),
('US_INDIANA_KELLEY','axis_06_tradicional_vs_experimental',48),
('US_INDIANA_KELLEY','axis_07_prova_vs_holistico',78),
('US_INDIANA_KELLEY','axis_08_tecnico_vs_proposito',62),
('US_INDIANA_KELLEY','axis_09_baixa_exposicao_vs_pitch',94),
('US_INDIANA_KELLEY','axis_10_baixa_ia_vs_ia_tech',89),
('US_INDIANA_KELLEY','axis_11_risco_baixo_vs_risco_alto',58),
('US_INDIANA_KELLEY','axis_12_financas_baixa_vs_alta',94),
('US_UNC_KENAN','axis_01_pratica_vs_teoria',90),
('US_UNC_KENAN','axis_02_corporativo_vs_founder',45),
('US_UNC_KENAN','axis_03_local_vs_global',98),
('US_UNC_KENAN','axis_04_estrutura_vs_autonomia',67),
('US_UNC_KENAN','axis_05_individual_vs_colaborativo',100),
('US_UNC_KENAN','axis_06_tradicional_vs_experimental',55),
('US_UNC_KENAN','axis_07_prova_vs_holistico',94),
('US_UNC_KENAN','axis_08_tecnico_vs_proposito',82),
('US_UNC_KENAN','axis_09_baixa_exposicao_vs_pitch',89),
('US_UNC_KENAN','axis_10_baixa_ia_vs_ia_tech',89),
('US_UNC_KENAN','axis_11_risco_baixo_vs_risco_alto',62),
('US_UNC_KENAN','axis_12_financas_baixa_vs_alta',80),
('US_USC_MARSHALL','axis_01_pratica_vs_teoria',96),
('US_USC_MARSHALL','axis_02_corporativo_vs_founder',76),
('US_USC_MARSHALL','axis_03_local_vs_global',98),
('US_USC_MARSHALL','axis_04_estrutura_vs_autonomia',84),
('US_USC_MARSHALL','axis_05_individual_vs_colaborativo',91),
('US_USC_MARSHALL','axis_06_tradicional_vs_experimental',88),
('US_USC_MARSHALL','axis_07_prova_vs_holistico',94),
('US_USC_MARSHALL','axis_08_tecnico_vs_proposito',62),
('US_USC_MARSHALL','axis_09_baixa_exposicao_vs_pitch',100),
('US_USC_MARSHALL','axis_10_baixa_ia_vs_ia_tech',96),
('US_USC_MARSHALL','axis_11_risco_baixo_vs_risco_alto',86),
('US_USC_MARSHALL','axis_12_financas_baixa_vs_alta',84)
on conflict (university_id,axis_id) do update set target=excluded.target;

insert into public.sources (source_id,university_id,source_name,url,usage_note) values
('source_us_upenn_wharton_1','US_UPENN_WHARTON','Programa de graduação Wharton','https://undergrad.wharton.upenn.edu/','Visão institucional, proposta acadêmica, liderança e impacto.'),
('source_us_upenn_wharton_2','US_UPENN_WHARTON','Currículo Wharton','https://undergrad.wharton.upenn.edu/classof2030/first-year-curriculum/','Integração de negócios, economia, cálculo, estatística, escrita e artes liberais.'),
('source_us_upenn_wharton_3','US_UPENN_WHARTON','Admissões Wharton','https://undergrad.wharton.upenn.edu/admissions/','Candidatura para Wharton por meio da University of Pennsylvania.'),
('source_us_mit_sloan_1','US_MIT_SLOAN','Undergraduate MIT Sloan','https://mitsloan.mit.edu/programs/undergraduate/undergraduate-programs','Majors em Management, Business Analytics e Finance.'),
('source_us_mit_sloan_2','US_MIT_SLOAN','Catálogo Course 15','https://catalog.mit.edu/schools/sloan-management/management/','Fundamentos quantitativos, comunicação, economia e áreas funcionais.'),
('source_us_mit_sloan_3','US_MIT_SLOAN','Admissão ao MIT e escolha do major','https://catalog.mit.edu/schools/sloan-management/','Candidatos entram no MIT e escolhem o major posteriormente.'),
('source_us_berkeley_haas_1','US_BERKELEY_HAAS','Undergraduate Berkeley Haas','https://haas.berkeley.edu/undergrad/','Programas, comunidade e proposta do undergraduate.'),
('source_us_berkeley_haas_2','US_BERKELEY_HAAS','Admissões Haas','https://haas.berkeley.edu/undergrad/admissions/','Avaliação holística e princípios de liderança.'),
('source_us_berkeley_haas_3','US_BERKELEY_HAAS','Candidatos do ensino médio','https://haas.berkeley.edu/undergrad/admissions/application-process/high-school-students/','Critérios: notas, redações, atividades e prêmios.'),
('source_us_michigan_ross_1','US_MICHIGAN_ROSS','BBA Michigan Ross','https://michiganross.umich.edu/undergraduate/bba','Aprendizagem baseada em ação e resultados profissionais.'),
('source_us_michigan_ross_2','US_MICHIGAN_ROSS','Currículo BBA Ross','https://michiganross.umich.edu/undergraduate/bba/curriculum','Currículo rigoroso e action-based learning.'),
('source_us_michigan_ross_3','US_MICHIGAN_ROSS','Admissão no primeiro ano','https://michiganross.umich.edu/undergraduate/bba/admissions/first-year-applicants','Common App, redações e Ross Admissions Portfolio.'),
('source_us_nyu_stern_1','US_NYU_STERN','Undergraduate NYU Stern','https://www.stern.nyu.edu/programs-admissions/undergraduate','Programas e experiência undergraduate.'),
('source_us_nyu_stern_2','US_NYU_STERN','BS in Business','https://bulletins.nyu.edu/undergraduate/business/programs/business-bs/','Currículo STEM com negócios e artes liberais.'),
('source_us_nyu_stern_3','US_NYU_STERN','Admissões Stern','https://www.stern.nyu.edu/programs-admissions/undergraduate/why-stern/admissions','Escolha do programa de Stern na candidatura à NYU.'),
('source_us_ut_mccombs_1','US_UT_MCCOMBS','BBA McCombs','https://www.mccombs.utexas.edu/undergraduate-programs/bba/','Programa, carreira, organizações e experiência estudantil.'),
('source_us_ut_mccombs_2','US_UT_MCCOMBS','Admissões e custo BBA','https://www.mccombs.utexas.edu/undergraduate-programs/bba/admissions-and-cost/','Processo, prazo, entrada no outono e estatística de aceitação.'),
('source_us_ut_mccombs_3','US_UT_MCCOMBS','Majors BBA','https://www.mccombs.utexas.edu/undergraduate-programs/bba/academics/majors/','Áreas como Finance, Business Analytics, MIS e Marketing.'),
('source_us_cmu_tepper_1','US_CMU_TEPPER','Business Administration Tepper','https://www.cmu.edu/tepper/programs/undergraduate-programs/business-administration','Objetivos do programa e competências.'),
('source_us_cmu_tepper_2','US_CMU_TEPPER','Currículo Tepper','https://www.cmu.edu/tepper/programs/undergraduate-programs/curriculum','Core, concentração, minor externo e experiências práticas.'),
('source_us_cmu_tepper_3','US_CMU_TEPPER','Admissão Tepper','https://www.cmu.edu/admission/majors-programs/tepper-school-of-business','Preparação acadêmica recomendada para candidatos.'),
('source_us_cornell_dyson_1','US_CORNELL_DYSON','BS Applied Economics and Management','https://business.cornell.edu/programs/bs-aem/','Economia, gestão, análise quantitativa, finanças e Grand Challenges.'),
('source_us_cornell_dyson_2','US_CORNELL_DYSON','Dyson degree requirements','https://business.cornell.edu/admissions/undergraduate/bs-aem/degree-requirements/','Core, concentrações e 120 créditos.'),
('source_us_cornell_dyson_3','US_CORNELL_DYSON','Dyson School','https://business.cornell.edu/dyson/','Ética, sustentabilidade, projetos e service learning.'),
('source_us_indiana_kelley_1','US_INDIANA_KELLEY','Undergraduate Kelley','https://kelley.iu.edu/undergraduate/index.html','Majors, experiência e proposta do programa.'),
('source_us_indiana_kelley_2','US_INDIANA_KELLEY','Acadêmicos Kelley','https://kelley.iu.edu/undergraduate/academics/index.html','Currículo orientado à experiência.'),
('source_us_indiana_kelley_3','US_INDIANA_KELLEY','Admissões Kelley','https://kelley.iu.edu/undergraduate/admissions/index.html','Caminhos de entrada e experiência do candidato.'),
('source_us_unc_kenan_1','US_UNC_KENAN','Undergraduate Business UNC','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/','Programa, rede e caminhos de admissão.'),
('source_us_unc_kenan_2','US_UNC_KENAN','Currículo do major','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/academics/major/','Core, eletivas de negócios e eletivas externas.'),
('source_us_unc_kenan_3','US_UNC_KENAN','High school applicants','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/admissions/high-school-students/','Future Business Admits e entrada posterior no programa.'),
('source_us_usc_marshall_1','US_USC_MARSHALL','Undergraduate USC Marshall','https://www.marshall.usc.edu/programs/undergraduate-programs','Programas, ênfases e proposta acadêmica.'),
('source_us_usc_marshall_2','US_USC_MARSHALL','BS Business Administration','https://www.marshall.usc.edu/programs/undergraduate-programs/undergraduate-degrees/business-administration-program','Fundamentos, especializações e designação STEM.'),
('source_us_usc_marshall_3','US_USC_MARSHALL','Admissões Marshall','https://www.marshall.usc.edu/programs/undergraduate-programs/undergraduate-admissions','Estrutura acadêmica e candidatura undergraduate.')
on conflict (source_id) do update set university_id=excluded.university_id,source_name=excluded.source_name,url=excluded.url,usage_note=excluded.usage_note;

insert into public.official_evidence (evidence_id,university_id,evidence_name,evidence_type,summary,source_url) values
('evidence_us_upenn_wharton_academics','US_UPENN_WHARTON','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://undergrad.wharton.upenn.edu/'),
('evidence_us_upenn_wharton_experience','US_UPENN_WHARTON','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://undergrad.wharton.upenn.edu/classof2030/first-year-curriculum/'),
('evidence_us_upenn_wharton_admissions','US_UPENN_WHARTON','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://undergrad.wharton.upenn.edu/admissions/'),
('evidence_us_mit_sloan_academics','US_MIT_SLOAN','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://mitsloan.mit.edu/programs/undergraduate/undergraduate-programs'),
('evidence_us_mit_sloan_experience','US_MIT_SLOAN','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://catalog.mit.edu/schools/sloan-management/management/'),
('evidence_us_mit_sloan_admissions','US_MIT_SLOAN','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://catalog.mit.edu/schools/sloan-management/'),
('evidence_us_berkeley_haas_academics','US_BERKELEY_HAAS','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://haas.berkeley.edu/undergrad/'),
('evidence_us_berkeley_haas_experience','US_BERKELEY_HAAS','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://haas.berkeley.edu/undergrad/admissions/'),
('evidence_us_berkeley_haas_admissions','US_BERKELEY_HAAS','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://haas.berkeley.edu/undergrad/admissions/application-process/high-school-students/'),
('evidence_us_michigan_ross_academics','US_MICHIGAN_ROSS','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://michiganross.umich.edu/undergraduate/bba'),
('evidence_us_michigan_ross_experience','US_MICHIGAN_ROSS','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://michiganross.umich.edu/undergraduate/bba/curriculum'),
('evidence_us_michigan_ross_admissions','US_MICHIGAN_ROSS','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://michiganross.umich.edu/undergraduate/bba/admissions/first-year-applicants'),
('evidence_us_nyu_stern_academics','US_NYU_STERN','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://www.stern.nyu.edu/programs-admissions/undergraduate'),
('evidence_us_nyu_stern_experience','US_NYU_STERN','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://bulletins.nyu.edu/undergraduate/business/programs/business-bs/'),
('evidence_us_nyu_stern_admissions','US_NYU_STERN','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://www.stern.nyu.edu/programs-admissions/undergraduate/why-stern/admissions'),
('evidence_us_ut_mccombs_academics','US_UT_MCCOMBS','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://www.mccombs.utexas.edu/undergraduate-programs/bba/'),
('evidence_us_ut_mccombs_experience','US_UT_MCCOMBS','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://www.mccombs.utexas.edu/undergraduate-programs/bba/admissions-and-cost/'),
('evidence_us_ut_mccombs_admissions','US_UT_MCCOMBS','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://www.mccombs.utexas.edu/undergraduate-programs/bba/academics/majors/'),
('evidence_us_cmu_tepper_academics','US_CMU_TEPPER','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://www.cmu.edu/tepper/programs/undergraduate-programs/business-administration'),
('evidence_us_cmu_tepper_experience','US_CMU_TEPPER','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://www.cmu.edu/tepper/programs/undergraduate-programs/curriculum'),
('evidence_us_cmu_tepper_admissions','US_CMU_TEPPER','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://www.cmu.edu/admission/majors-programs/tepper-school-of-business'),
('evidence_us_cornell_dyson_academics','US_CORNELL_DYSON','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://business.cornell.edu/programs/bs-aem/'),
('evidence_us_cornell_dyson_experience','US_CORNELL_DYSON','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://business.cornell.edu/admissions/undergraduate/bs-aem/degree-requirements/'),
('evidence_us_cornell_dyson_admissions','US_CORNELL_DYSON','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://business.cornell.edu/dyson/'),
('evidence_us_indiana_kelley_academics','US_INDIANA_KELLEY','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://kelley.iu.edu/undergraduate/index.html'),
('evidence_us_indiana_kelley_experience','US_INDIANA_KELLEY','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://kelley.iu.edu/undergraduate/academics/index.html'),
('evidence_us_indiana_kelley_admissions','US_INDIANA_KELLEY','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://kelley.iu.edu/undergraduate/admissions/index.html'),
('evidence_us_unc_kenan_academics','US_UNC_KENAN','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/'),
('evidence_us_unc_kenan_experience','US_UNC_KENAN','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/academics/major/'),
('evidence_us_unc_kenan_admissions','US_UNC_KENAN','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://www.kenan-flagler.unc.edu/programs/undergraduate-business/admissions/high-school-students/'),
('evidence_us_usc_marshall_academics','US_USC_MARSHALL','Base acadêmica e curricular','Currículo oficial','O currículo e os requisitos oficiais fundamentam o perfil de rigor, conteúdo e estilo de aprendizagem.','https://www.marshall.usc.edu/programs/undergraduate-programs'),
('evidence_us_usc_marshall_experience','US_USC_MARSHALL','Experiência e diferenciais do programa','Proposta institucional','Os diferenciais oficiais fundamentam o perfil cultural, profissional e de aprendizagem prática.','https://www.marshall.usc.edu/programs/undergraduate-programs/undergraduate-degrees/business-administration-program'),
('evidence_us_usc_marshall_admissions','US_USC_MARSHALL','Seleção e perfil valorizado','Processo de admissão','Os critérios e caminhos oficiais de admissão fundamentam as dimensões de evidência, liderança e aderência institucional.','https://www.marshall.usc.edu/programs/undergraduate-programs/undergraduate-admissions')
on conflict (evidence_id) do update set university_id=excluded.university_id,evidence_name=excluded.evidence_name,evidence_type=excluded.evidence_type,summary=excluded.summary,source_url=excluded.source_url;

insert into public.evidence_dimensions (evidence_id,dimension_id) values
('evidence_us_upenn_wharton_academics','academic_perf'),
('evidence_us_upenn_wharton_academics','rigor_depth'),
('evidence_us_upenn_wharton_academics','theory_comfort'),
('evidence_us_upenn_wharton_academics','analytical_data'),
('evidence_us_upenn_wharton_experience','practical_learning'),
('evidence_us_upenn_wharton_experience','project_execution'),
('evidence_us_upenn_wharton_experience','market_employability'),
('evidence_us_upenn_wharton_experience','global_mindset'),
('evidence_us_upenn_wharton_admissions','achievement_selectivity'),
('evidence_us_upenn_wharton_admissions','extracurricular_depth'),
('evidence_us_upenn_wharton_admissions','leadership_evidence'),
('evidence_us_upenn_wharton_admissions','writing_argument'),
('evidence_us_mit_sloan_academics','academic_perf'),
('evidence_us_mit_sloan_academics','rigor_depth'),
('evidence_us_mit_sloan_academics','theory_comfort'),
('evidence_us_mit_sloan_academics','analytical_data'),
('evidence_us_mit_sloan_experience','practical_learning'),
('evidence_us_mit_sloan_experience','project_execution'),
('evidence_us_mit_sloan_experience','market_employability'),
('evidence_us_mit_sloan_experience','global_mindset'),
('evidence_us_mit_sloan_admissions','achievement_selectivity'),
('evidence_us_mit_sloan_admissions','extracurricular_depth'),
('evidence_us_mit_sloan_admissions','leadership_evidence'),
('evidence_us_mit_sloan_admissions','writing_argument'),
('evidence_us_berkeley_haas_academics','academic_perf'),
('evidence_us_berkeley_haas_academics','rigor_depth'),
('evidence_us_berkeley_haas_academics','theory_comfort'),
('evidence_us_berkeley_haas_academics','analytical_data'),
('evidence_us_berkeley_haas_experience','practical_learning'),
('evidence_us_berkeley_haas_experience','project_execution'),
('evidence_us_berkeley_haas_experience','market_employability'),
('evidence_us_berkeley_haas_experience','global_mindset'),
('evidence_us_berkeley_haas_admissions','achievement_selectivity'),
('evidence_us_berkeley_haas_admissions','extracurricular_depth'),
('evidence_us_berkeley_haas_admissions','leadership_evidence'),
('evidence_us_berkeley_haas_admissions','writing_argument'),
('evidence_us_michigan_ross_academics','academic_perf'),
('evidence_us_michigan_ross_academics','rigor_depth'),
('evidence_us_michigan_ross_academics','theory_comfort'),
('evidence_us_michigan_ross_academics','analytical_data'),
('evidence_us_michigan_ross_experience','practical_learning'),
('evidence_us_michigan_ross_experience','project_execution'),
('evidence_us_michigan_ross_experience','market_employability'),
('evidence_us_michigan_ross_experience','global_mindset'),
('evidence_us_michigan_ross_admissions','achievement_selectivity'),
('evidence_us_michigan_ross_admissions','extracurricular_depth'),
('evidence_us_michigan_ross_admissions','leadership_evidence'),
('evidence_us_michigan_ross_admissions','writing_argument'),
('evidence_us_nyu_stern_academics','academic_perf'),
('evidence_us_nyu_stern_academics','rigor_depth'),
('evidence_us_nyu_stern_academics','theory_comfort'),
('evidence_us_nyu_stern_academics','analytical_data'),
('evidence_us_nyu_stern_experience','practical_learning'),
('evidence_us_nyu_stern_experience','project_execution'),
('evidence_us_nyu_stern_experience','market_employability'),
('evidence_us_nyu_stern_experience','global_mindset'),
('evidence_us_nyu_stern_admissions','achievement_selectivity'),
('evidence_us_nyu_stern_admissions','extracurricular_depth'),
('evidence_us_nyu_stern_admissions','leadership_evidence'),
('evidence_us_nyu_stern_admissions','writing_argument'),
('evidence_us_ut_mccombs_academics','academic_perf'),
('evidence_us_ut_mccombs_academics','rigor_depth'),
('evidence_us_ut_mccombs_academics','theory_comfort'),
('evidence_us_ut_mccombs_academics','analytical_data'),
('evidence_us_ut_mccombs_experience','practical_learning'),
('evidence_us_ut_mccombs_experience','project_execution'),
('evidence_us_ut_mccombs_experience','market_employability'),
('evidence_us_ut_mccombs_experience','global_mindset'),
('evidence_us_ut_mccombs_admissions','achievement_selectivity'),
('evidence_us_ut_mccombs_admissions','extracurricular_depth'),
('evidence_us_ut_mccombs_admissions','leadership_evidence'),
('evidence_us_ut_mccombs_admissions','writing_argument'),
('evidence_us_cmu_tepper_academics','academic_perf'),
('evidence_us_cmu_tepper_academics','rigor_depth'),
('evidence_us_cmu_tepper_academics','theory_comfort'),
('evidence_us_cmu_tepper_academics','analytical_data'),
('evidence_us_cmu_tepper_experience','practical_learning'),
('evidence_us_cmu_tepper_experience','project_execution'),
('evidence_us_cmu_tepper_experience','market_employability'),
('evidence_us_cmu_tepper_experience','global_mindset'),
('evidence_us_cmu_tepper_admissions','achievement_selectivity'),
('evidence_us_cmu_tepper_admissions','extracurricular_depth'),
('evidence_us_cmu_tepper_admissions','leadership_evidence'),
('evidence_us_cmu_tepper_admissions','writing_argument'),
('evidence_us_cornell_dyson_academics','academic_perf'),
('evidence_us_cornell_dyson_academics','rigor_depth'),
('evidence_us_cornell_dyson_academics','theory_comfort'),
('evidence_us_cornell_dyson_academics','analytical_data'),
('evidence_us_cornell_dyson_experience','practical_learning'),
('evidence_us_cornell_dyson_experience','project_execution'),
('evidence_us_cornell_dyson_experience','market_employability'),
('evidence_us_cornell_dyson_experience','global_mindset'),
('evidence_us_cornell_dyson_admissions','achievement_selectivity'),
('evidence_us_cornell_dyson_admissions','extracurricular_depth'),
('evidence_us_cornell_dyson_admissions','leadership_evidence'),
('evidence_us_cornell_dyson_admissions','writing_argument'),
('evidence_us_indiana_kelley_academics','academic_perf'),
('evidence_us_indiana_kelley_academics','rigor_depth'),
('evidence_us_indiana_kelley_academics','theory_comfort'),
('evidence_us_indiana_kelley_academics','analytical_data'),
('evidence_us_indiana_kelley_experience','practical_learning'),
('evidence_us_indiana_kelley_experience','project_execution'),
('evidence_us_indiana_kelley_experience','market_employability'),
('evidence_us_indiana_kelley_experience','global_mindset'),
('evidence_us_indiana_kelley_admissions','achievement_selectivity'),
('evidence_us_indiana_kelley_admissions','extracurricular_depth'),
('evidence_us_indiana_kelley_admissions','leadership_evidence'),
('evidence_us_indiana_kelley_admissions','writing_argument'),
('evidence_us_unc_kenan_academics','academic_perf'),
('evidence_us_unc_kenan_academics','rigor_depth'),
('evidence_us_unc_kenan_academics','theory_comfort'),
('evidence_us_unc_kenan_academics','analytical_data'),
('evidence_us_unc_kenan_experience','practical_learning'),
('evidence_us_unc_kenan_experience','project_execution'),
('evidence_us_unc_kenan_experience','market_employability'),
('evidence_us_unc_kenan_experience','global_mindset'),
('evidence_us_unc_kenan_admissions','achievement_selectivity'),
('evidence_us_unc_kenan_admissions','extracurricular_depth'),
('evidence_us_unc_kenan_admissions','leadership_evidence'),
('evidence_us_unc_kenan_admissions','writing_argument'),
('evidence_us_usc_marshall_academics','academic_perf'),
('evidence_us_usc_marshall_academics','rigor_depth'),
('evidence_us_usc_marshall_academics','theory_comfort'),
('evidence_us_usc_marshall_academics','analytical_data'),
('evidence_us_usc_marshall_experience','practical_learning'),
('evidence_us_usc_marshall_experience','project_execution'),
('evidence_us_usc_marshall_experience','market_employability'),
('evidence_us_usc_marshall_experience','global_mindset'),
('evidence_us_usc_marshall_admissions','achievement_selectivity'),
('evidence_us_usc_marshall_admissions','extracurricular_depth'),
('evidence_us_usc_marshall_admissions','leadership_evidence'),
('evidence_us_usc_marshall_admissions','writing_argument')
on conflict (evidence_id,dimension_id) do nothing;
commit;
