import { generateText } from 'ai';
import { google } from '@ai-sdk/google';
import { createClient } from '@supabase/supabase-js';

const json=(res:any,status:number,body:unknown)=>{res.setHeader('Cache-Control','no-store');return res.status(status).json(body)};
const trim=(v:unknown,max=4000)=>String(v??'').slice(0,max);
const clamp=(v:unknown,min=0,max=.99)=>Math.max(min,Math.min(max,Number(v)||0));
const MODEL='openai/gpt-5.6-luna';
const REVIEW_MODEL='google/gemini-3.6-flash';
const SEARCH_MODEL='google/gemini-2.5-flash-lite';
const FALLBACK_MODELS=['google/gemini-3.6-flash','openai/gpt-5.4-mini'];
const DAILY_QUESTION_LIMIT=20;
const FALLBACK_SUPABASE_URL='https://kmognvgnfisdchzffkgh.supabase.co';
const FALLBACK_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6Imttb2dudmduZmlzZGNoemZma2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MzkxNjksImV4cCI6MjEwMjMxNTE2OX0.JarpsXfgv8PplL3Ryvs6iFfEPiv_rnp2Cx5i1I67fCk';

type Msg={role:'user'|'assistant';content:string};
type Skill={area:string;skill_code:string;skill_name:string;scope?:string;diagnostic_tags?:string[];parent_skill_code?:string|null;official_reference?:boolean};
type Practice={id:number;area:string;skill_name:string;difficulty:number;prompt:string;option_a?:string;option_b?:string;option_c?:string;option_d?:string;option_e?:string;correct_option:string;explanation:string;source_basis?:string;source_kind?:string;source_exam_year?:number|null;source_question_number?:number|null;source_exam_label?:string|null;source_caderno?:string|null;source_exam_url?:string|null;source_answer_url?:string|null;source_verified_at?:string|null};

const EXAM_FINGERPRINTS:Record<string,string>={
  enem:'ENEM: 180 questões em dois dias + redação. Classifique por Linguagens, Humanas, Natureza e Matemática e pelas habilidades do banco. Em questões objetivas, priorize leitura contextual, modelagem e aplicação; não invente TRI. Em redação, use as cinco competências do ENEM e proposta de intervenção.',
  fuvest:'FUVEST: vestibular da USP com 1ª fase objetiva e 2ª fase discursiva/redação. Respeite a etapa ativa e o programa vigente; em discursivas, valorize desenvolvimento e justificativa, não apenas resultado final.',
  cmmg:'FCM-MG/CMMG: reconheça Medicina e EFFPO pelo contexto. Medicina usa prova objetiva e redação; EFFPO possui estrutura própria. Nunca misture quantidade de questões, pesos ou critérios entre modalidades. Use a taxonomia cadastrada para a modalidade inferida.',
  insper:'Insper: vestibular com 60 questões objetivas e redação dissertativo-argumentativa. Reconheça Língua Portuguesa, Matemática, Biologia, Física, Química, História, Geografia, Sociologia e os quatro critérios cadastrados de redação. Não exija proposta de intervenção no padrão ENEM.',
  link:'Link School of Business: jornada holística em PREP, SPRINT e entrevista. PREP reúne trajetória acadêmica, vídeo e portfólio. SPRINT combina matemática e business case com entregas escrita e em vídeo; diagnostique estrutura do problema, dados, mercado, unit economics, trade-offs, criatividade, recomendação e comunicação. A entrevista mede motivação, fit e evidências comportamentais.'
};

function cleanEnv(v:unknown){return String(v??'').trim().replace(/^["']|["']$/g,'')}
function config(){
  const raw=cleanEnv(process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL);
  let url='';try{const u=new URL(raw.startsWith('http')?raw:`https://${raw}`);if(/^[a-z0-9-]+\.supabase\.co$/i.test(u.hostname))url=u.origin}catch{}
  const key=cleanEnv(process.env.SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_PUBLISHABLE_KEY);
  return url&&key?{url,key,source:'env'}:{url:FALLBACK_SUPABASE_URL,key:FALLBACK_SUPABASE_ANON_KEY,source:'fallback'};
}
function tokens(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9]+/).filter(x=>x.length>2)}
function parseJson(raw:string){
  const s=raw.trim().replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/```$/,'').trim();
  const a=s.indexOf('{'),b=s.lastIndexOf('}');
  for(const c of [s,a>=0&&b>a?s.slice(a,b+1):'']){if(!c)continue;try{return JSON.parse(c)}catch{}try{return JSON.parse(c.replace(/\\(?!["\\/bfnrtu])/g,'\\\\'))}catch{}}
  throw new Error('invalid-json');
}
function list(v:unknown,n=4){return Array.isArray(v)?v.map(x=>trim(x,220).trim()).filter(Boolean).slice(0,n):[]}
function confidenceLabel(v:number){return v>=.94?'Alta confiança':v>=.80?'Confiança moderada':'Baixa confiança'}
function hard(s:string){return /\b(exceto|incorreta|respectivamente|necessariamente|sempre|nunca|condicional|sem reposi[cç][aã]o|aproxima[cç][aã]o|arredond|contraexemplo|causa|consequ[eê]ncia|gr[aá]fico|tabela|imagem|figura|gabarito|banca|20\d{2})\b/i.test(s)||/[=<>±√^]/.test(s)}
function unexpectedScript(s:string){return /[\u0400-\u052f\u0590-\u08ff\u0900-\u109f\u3040-\u30ff\u3400-\u9fff]/u.test(s)}
async function fetchJson(url:string,headers:Record<string,string>){const r=await fetch(url,{headers,signal:AbortSignal.timeout(9000)});if(!r.ok)return[];return r.json()}

function rankSkills(skills:Skill[],query:string,area:string,currentSkill:string){
  const q=new Set(tokens(query)),a=area.toLowerCase(),cs=currentSkill.toLowerCase();
  return skills.map(s=>{let score=0;const hay=tokens(`${s.area} ${s.skill_code} ${s.skill_name} ${s.scope||''} ${(s.diagnostic_tags||[]).join(' ')}`);if(a&&s.area.toLowerCase().includes(a))score+=10;if(cs&&s.skill_name.toLowerCase().includes(cs))score+=14;for(const t of hay)if(q.has(t))score+=2;return{s,score}}).sort((x,y)=>y.score-x.score).filter((x,i)=>x.score>0||i<20).slice(0,36).map(x=>x.s);
}
function rankPractice(items:Practice[],query:string,area:string,currentSkill:string,difficulties:string[],seen:Set<number>){
  const q=new Set(tokens(query)),a=area.toLowerCase(),cs=currentSkill.toLowerCase(),ds=tokens(difficulties.join(' '));
  return items.map(item=>{let score=0;const hay=tokens(`${item.area} ${item.skill_name} ${item.prompt}`);if(a&&item.area.toLowerCase().includes(a))score+=12;if(cs&&item.skill_name.toLowerCase().includes(cs))score+=18;for(const t of hay)if(q.has(t))score+=2;for(const t of hay)if(ds.includes(t))score+=1.5;if(item.source_kind==='official'||item.source_kind==='official_adapted')score+=1.5;if(seen.has(Number(item.id)))score-=18;return{item,score}}).sort((x,y)=>y.score-x.score||Number(y.item.difficulty||0)-Number(x.item.difficulty||0)).filter((x,i)=>x.score>0||i<12).slice(0,6).map(x=>x.item);
}
function provenance(q:Practice){
  const official=q.source_kind==='official'||q.source_kind==='official_adapted';
  return {kind:q.source_kind||'legacy',label:q.source_exam_label||null,year:q.source_exam_year||null,number:q.source_question_number||null,caderno:q.source_caderno||null,verified:Boolean(q.source_verified_at),examUrl:q.source_exam_url||null,answerUrl:q.source_answer_url||null,official};
}
function sourceList(v:unknown){if(!Array.isArray(v))return[];return v.slice(0,4).map((s:any)=>{try{const u=new URL(String(s?.url||''));return {title:trim(s?.title||u.hostname,140),url:u.toString()}}catch{return null}}).filter(Boolean)}

async function verifyToken(url:string,key:string,token:string){
  const client=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}});
  try{const {data,error}=await client.auth.getClaims(token);const c=(data as any)?.claims;if(!error&&c?.sub)return{userId:String(c.sub),isAdmin:String(c?.app_metadata?.role||'').toLowerCase()==='admin'}}catch{}
  try{const {data,error}=await client.auth.getUser(token);if(!error&&data?.user?.id)return{userId:String(data.user.id),isAdmin:String(data.user.app_metadata?.role||'').toLowerCase()==='admin'}}catch{}
  return{userId:'',isAdmin:false};
}
async function premium(url:string,key:string,token:string,userId:string){
  try{const rows:any[]=await fetchJson(`${url}/rest/v1/premium_subscriptions?select=status,current_period_end&user_id=eq.${encodeURIComponent(userId)}&limit=1`,{apikey:key,Authorization:`Bearer ${token}`,Accept:'application/json'});const r=rows?.[0];return Boolean(r&&['active','trialing'].includes(String(r.status||''))&&(!r.current_period_end||new Date(r.current_period_end).getTime()>Date.now()))}catch{return false}
}

export default async function handler(req:any,res:any){
  if(req.method==='GET')return json(res,200,{ok:true,service:'IA Conectaê v2',model:MODEL,reviewModel:REVIEW_MODEL,searchModel:SEARCH_MODEL,retrieval:'full-active-corpus+skill+area+difficulty+seen-history+provenance',supportedExams:Object.keys(EXAM_FINGERPRINTS),dailyQuestionLimit:DAILY_QUESTION_LIMIT,adminAccess:'unlimited'});
  if(req.method!=='POST')return json(res,405,{error:'Método não permitido.'});
  try{
    const auth=String(req.headers.authorization||'');if(!auth.startsWith('Bearer '))return json(res,401,{error:'Faça login para conversar com a IA Conectaê.'});
    const token=auth.slice(7).trim(),cfg=config(),verified=await verifyToken(cfg.url,cfg.key,token);if(!verified.userId)return json(res,401,{error:'Sua sessão expirou. Entre novamente.'});
    const userId=verified.userId,headers={apikey:cfg.key,Authorization:`Bearer ${token}`};
    const premiumUnlimited=verified.isAdmin?false:await premium(cfg.url,cfg.key,token,userId),unlimited=verified.isAdmin||premiumUnlimited;
    const {messages,context,imageDataUrl}=req.body||{};if(!Array.isArray(messages)||!messages.length)return json(res,400,{error:'Escreva sua dúvida.'});
    const safe:Msg[]=messages.slice(-10).map((m:any)=>({role:m?.role==='assistant'?'assistant':'user',content:trim(m?.content,2400)})).filter((m:Msg)=>m.content.trim());if(!safe.length)return json(res,400,{error:'Escreva sua dúvida.'});
    const image=typeof imageDataUrl==='string';if(image&&!/^data:image\/(jpeg|png|webp);base64,/i.test(imageDataUrl))return json(res,400,{error:'Formato de imagem inválido.'});if(image&&imageDataUrl.length>4_800_000)return json(res,413,{error:'A foto ficou grande demais. Recorte apenas a questão.'});
    const c=context&&typeof context==='object'?context:{},exam=trim(c.exam||'enem',40).toLowerCase(),latest=safe.at(-1)?.content||'';
    let usedToday=0;
    if(!unlimited){try{const minute=new Date(Date.now()-60000).toISOString(),day=new Date(Date.now()-86400000).toISOString();const [a,b]=await Promise.all([fetch(`${cfg.url}/rest/v1/ai_tutor_usage?select=id&user_id=eq.${userId}&created_at=gte.${encodeURIComponent(minute)}`,{headers:{...headers,Prefer:'count=exact'},signal:AbortSignal.timeout(7000)}),fetch(`${cfg.url}/rest/v1/ai_tutor_usage?select=id&user_id=eq.${userId}&created_at=gte.${encodeURIComponent(day)}`,{headers:{...headers,Prefer:'count=exact'},signal:AbortSignal.timeout(7000)})]);const mc=Number(a.headers.get('content-range')?.split('/')?.[1]||0),dc=Number(b.headers.get('content-range')?.split('/')?.[1]||0);usedToday=dc;if(mc>=8)return json(res,429,{error:'Aguarde um minuto antes de enviar mais perguntas.'});if(dc>=DAILY_QUESTION_LIMIT)return json(res,429,{error:`Você atingiu o limite de ${DAILY_QUESTION_LIMIT} perguntas da IA Conectaê hoje.`})}catch{}}

    const [refs,skills,practice,seenRows]:[Skill[],Skill[],Practice[],any[]]=await Promise.all([
      fetchJson(`${cfg.url}/rest/v1/exam_ai_skill_reference?select=area,skill_code,skill_name,scope,diagnostic_tags,parent_skill_code,official_reference&exam_id=eq.${encodeURIComponent(exam)}`,{...headers,Accept:'application/json'}),
      fetchJson(`${cfg.url}/rest/v1/exam_skill_taxonomy?select=area,skill_code,skill_name,diagnostic_tags&exam_id=eq.${encodeURIComponent(exam)}`,{...headers,Accept:'application/json'}),
      fetchJson(`${cfg.url}/rest/v1/exam_practice_questions?select=id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,source_basis,source_kind,source_exam_year,source_question_number,source_exam_label,source_caderno,source_exam_url,source_answer_url,source_verified_at&exam_id=eq.${encodeURIComponent(exam)}&active=is.true&limit=1500`,{...headers,Accept:'application/json'}),
      fetchJson(`${cfg.url}/rest/v1/student_seen_questions?select=question_id&user_id=eq.${encodeURIComponent(userId)}&limit=1500`,{...headers,Accept:'application/json'})
    ]);
    const seen=new Set(seenRows.map(r=>Number(r.question_id))),area=trim(c.currentArea,80),currentSkill=trim(c.currentSkill,150),contextQuestion=trim(c.currentQuestion,2200),difficulties=list(c.recentDifficulties,6);
    const taxonomyRefs:Skill[]=skills.map(s=>({...s,scope:`Habilidade da taxonomia ${exam}: ${s.skill_name}`,official_reference:false}));const pool=[...refs,...taxonomyRefs.filter(t=>!refs.some(r=>r.skill_code===t.skill_code))];
    const candidates=rankSkills(pool,`${latest} ${contextQuestion}`,area,currentSkill),examples=rankPractice(practice,`${latest} ${contextQuestion}`,area,currentSkill,difficulties,seen);
    const corpusStats={active:practice.length,officialOrAdapted:practice.filter(q=>q.source_kind==='official'||q.source_kind==='official_adapted').length,authorial:practice.filter(q=>q.source_kind==='authorial').length,skills:skills.length};
    const student={exam,weeklyHours:trim(c.weeklyHours,12),recentDifficulties:difficulties,recentPerformance:list(c.recentPerformance,6),currentQuestion:contextQuestion,currentSkill,area};
    const examplesSafe=examples.map(q=>({id:q.id,area:q.area,skill:q.skill_name,difficulty:q.difficulty,prompt:q.prompt,options:{A:q.option_a,B:q.option_b,C:q.option_c,D:q.option_d,E:q.option_e},answer:q.correct_option,explanation:q.explanation,provenance:provenance(q)}));

    const system=`Você é a IA Conectaê v2, um tutor de vestibulares brasileiro rigoroso, didático e intelectualmente honesto. Responda em português do Brasil.\n\nOBJETIVO: resolver a dúvida corretamente, detectar a habilidade específica, ensinar o ponto decisivo e sinalizar incerteza real. Nunca finja 100% de precisão.\n\nPROTOCOLO INTERNO: trate sua primeira solução como hipótese. Releia o comando; confira EXCETO/incorreta/sempre/nunca; em exatas valide domínio, sinais, unidades, ordem de grandeza e substituição; em linguagens fundamente no texto; em humanas evite anacronismo e separe correlação de causalidade. Quando possível use um segundo caminho. Não exponha cadeia de raciocínio interna.\n\nFOTO: transcreva mentalmente comando, dados, alternativas, gráfico/tabela. Se faltar qualquer parte necessária, needs_better_image=true e não invente resposta.\n\nPROVA: ${EXAM_FINGERPRINTS[exam]||'Use estritamente a taxonomia cadastrada da prova ativa.'}\n\nPROVENIÊNCIA: itens authorial são apenas questões autorais alinhadas ao estilo. Itens official/official_adapted só podem ser chamados de oficiais/adaptados se a proveniência recebida sustentar isso. Para pedido de questão histórica por ano/número, se o item integral e a referência verificada não estiverem no contexto, marque needs_external_check=true. Nunca invente ano, número ou banca.\n\nRECUPERAÇÃO: use os exemplos recuperados como apoio, mas resolva independentemente antes de aceitar o gabarito. Prefira habilidade exata e exemplos não vistos.\n\nSAÍDA AO ALUNO: comece pela conclusão. Objetiva: “Resposta: X) ...” e depois explicação curta, com contas quando necessárias. Conceitual: resposta direta + explicação. Se a confiança for baixa, diga exatamente o dado faltante.\n\nCONFIANÇA: nunca use 1. 0.94–0.99 somente com dados suficientes e contrachecagem; 0.80–0.93 boa sustentação com pequena incerteza; 0.60–0.79 interpretação plausível/dado parcial; abaixo de 0.60 insuficiente.\n\nCONTEXTO DO ALUNO: ${JSON.stringify(student)}\nHABILIDADES CANDIDATAS: ${JSON.stringify(candidates.map(s=>({area:s.area,skill_code:s.skill_code,skill_name:s.skill_name,parent_skill_code:s.parent_skill_code||null})))}\nEXEMPLOS RECUPERADOS: ${JSON.stringify(examplesSafe)}\n\nRetorne APENAS JSON válido: {"answer":"resposta curta e didática","confidence":0.0,"confidence_reason":"uma frase objetiva","self_check_passed":true,"needs_external_check":false,"answerable":true,"resolved_doubt":true,"needs_better_image":false,"uncertainty_reason":null,"assumptions":[],"learning_focus":{"area":"","skill_code":"","skill_name":"","plan_skill_code":null,"confidence":0.0,"reason":""},"offer_plan":false}`;
    const modelMessages:any[]=safe.map((m,i)=>i===safe.length-1&&m.role==='user'&&image?{role:'user',content:[{type:'text',text:m.content},{type:'image',image:imageDataUrl}]}:{role:m.role,content:m.content});
    let raw='';try{raw=String((await generateText({model:MODEL,system,messages:modelMessages,maxOutputTokens:1700,abortSignal:AbortSignal.timeout(45000),providerOptions:{gateway:{models:FALLBACK_MODELS,user:userId,tags:['feature:education-tutor-v2',`exam:${exam}`]}}} as any)).text||'')}catch(e:any){console.error('tutor v2 primary',e?.message||e)}if(!raw)return json(res,502,{error:'A IA ficou temporariamente indisponível. Tente novamente.'});
    let first:any;try{first=parseJson(raw)}catch{return json(res,502,{error:'A resposta ficou incompleta. Tente novamente.'})}
    let final=first,mode='primary',sources:any[]=[];const baseConf=clamp(first.confidence),explicitLookup=/\b(gabarito|fonte|banca|prova|vestibular|quest[aã]o\s*\d+|20\d{2})\b/i.test(`${latest} ${contextQuestion}`);const shouldSearch=Boolean(first.needs_external_check)||(explicitLookup&&baseConf<.95)||(image&&baseConf<.72);const shouldReview=hard(`${latest} ${contextQuestion}`)||first.self_check_passed===false||baseConf<.84;
    if(shouldSearch){try{const verifySystem='Você é o verificador externo da IA Conectaê. Pesquise apenas o necessário. Prefira fonte oficial da banca, universidade, órgão público ou publicação primária. Refaça a solução e corrija a preliminar se necessário. Nunca invente referência. Só use web_verified=true se houver fonte encontrada que sustente a conclusão. Não exponha cadeia interna. Retorne apenas JSON: {"answer":"resposta final curta","confidence":0.0,"confidence_reason":"uma frase","self_check_passed":true,"answerable":true,"resolved_doubt":true,"needs_better_image":false,"uncertainty_reason":null,"assumptions":[],"web_verified":false}.';const prompt=`Prova: ${exam}\nPergunta: ${latest}\n${contextQuestion?`Enunciado: ${contextQuestion}\n`:''}Preliminar: ${trim(first.answer,2200)}`;const r=await generateText({model:SEARCH_MODEL,system:verifySystem,messages:[{role:'user',content:image?[{type:'text',text:prompt},{type:'image',image:imageDataUrl}]:prompt}],maxOutputTokens:1300,abortSignal:AbortSignal.timeout(45000),tools:{google_search:google.tools.googleSearch({})},providerOptions:{gateway:{user:userId,tags:['feature:education-tutor-v2','external-verification']}}} as any);const p=parseJson(String(r.text||'')),found=sourceList((r as any).sources);if(p?.answer&&p.web_verified===true&&found.length){final={...first,...p};sources=found;mode='search'}}catch(e:any){console.warn('tutor v2 search',e?.message||e)}}
    if(mode==='primary'&&shouldReview){try{const reviewSystem='Você é o revisor adversarial final. Resolva do zero, confira domínio, sinais, unidades, negações, ambiguidade, causalidade e alternativas. Compare com a preliminar. Se faltarem dados, não chute. Não exponha cadeia interna. Retorne apenas JSON: {"answer":"resposta final curta","confidence":0.0,"confidence_reason":"uma frase","self_check_passed":true,"answerable":true,"resolved_doubt":true,"needs_better_image":false,"uncertainty_reason":null,"assumptions":[],"agrees_with_preliminary":true}.';const ptxt=`Pergunta: ${latest}\n${contextQuestion?`Enunciado: ${contextQuestion}\n`:''}Preliminar: ${trim(first.answer,2200)}`;const r=await generateText({model:REVIEW_MODEL,system:reviewSystem,messages:[{role:'user',content:image?[{type:'text',text:ptxt},{type:'image',image:imageDataUrl}]:ptxt}],maxOutputTokens:1300,abortSignal:AbortSignal.timeout(45000),providerOptions:{gateway:{models:['openai/gpt-5.4-mini'],user:userId,tags:['feature:education-tutor-v2','adversarial-review']}}} as any);const p=parseJson(String(r.text||''));if(p?.answer){final={...first,...p,confidence:p.agrees_with_preliminary===false?Math.min(clamp(p.confidence),.79):p.confidence,uncertainty_reason:p.agrees_with_preliminary===false?(p.uncertainty_reason||'A revisão independente divergiu da primeira solução e a resposta foi corrigida.'):p.uncertainty_reason};mode='review'}}catch(e:any){console.warn('tutor v2 review',e?.message||e)}}
    let answer=trim(final.answer,6000).trim();if(!answer)return json(res,502,{error:'A resposta ficou incompleta. Tente novamente.'});if(unexpectedScript(answer)){try{answer=trim((await generateText({model:REVIEW_MODEL,system:'Reescreva em português do Brasil usando apenas alfabeto latino e matemática em texto simples, sem mudar fatos, números ou conclusão.',messages:[{role:'user',content:answer}],maxOutputTokens:800,abortSignal:AbortSignal.timeout(25000)} as any)).text,6000)}catch{}if(unexpectedScript(answer))return json(res,502,{error:'A resposta ficou com caracteres inválidos. Tente novamente.'})}
    const answerable=Boolean(final.answerable??true),selfChecked=Boolean(final.self_check_passed),resolvedDoubt=Boolean(final.resolved_doubt),needsBetterImage=Boolean(final.needs_better_image);let confidence=clamp(final.confidence??first.confidence);if(!answerable||!selfChecked||!resolvedDoubt)confidence=Math.min(confidence,.79);if(needsBetterImage)confidence=Math.min(confidence,.55);
    let focus=final.learning_focus&&typeof final.learning_focus==='object'?final.learning_focus:first.learning_focus;if(focus){const m=candidates.find(s=>s.skill_code===String(focus.skill_code||'')&&s.skill_name===String(focus.skill_name||''));if(!m)focus=null;else{const pc=String(focus.plan_skill_code||m.parent_skill_code||''),plan=skills.find(s=>s.skill_code===pc);focus={area:m.area,skill_code:m.skill_code,skill_name:m.skill_name,plan_skill_code:plan?.skill_code||null,plan_skill_name:plan?.skill_name||null,confidence:clamp(focus.confidence||confidence,0,.99),reason:trim(focus.reason,320),official_reference:Boolean(m.official_reference)}}}
    const offerPlan=Boolean(final.offer_plan??first.offer_plan)&&Boolean(focus)&&Number(focus?.confidence)>=.68&&resolvedDoubt;
    try{await fetch(`${cfg.url}/rest/v1/ai_tutor_usage`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({user_id:userId,exam_id:exam,has_image:image}),signal:AbortSignal.timeout(5000)})}catch{}
    return json(res,200,{answer,educational:true,resolvedDoubt,answerable,confidence,confidenceLabel:confidenceLabel(confidence),confidenceReason:trim(final.confidence_reason??first.confidence_reason,300),uncertaintyReason:trim(final.uncertainty_reason??first.uncertainty_reason,400)||null,assumptions:list(final.assumptions??first.assumptions,4),selfChecked,learningFocus:focus,offerPlan,needsBetterImage,model:mode==='search'?SEARCH_MODEL:mode==='review'?REVIEW_MODEL:MODEL,searchMode:mode,webVerified:mode==='search'&&sources.length>0,sources,costOptimized:true,retrievalGrounded:examples.length>0,retrievedExamples:examples.length,corpusStats,provenanceAware:true,seenQuestionAware:true,adminUnlimited:verified.isAdmin,premiumUnlimited,dailyQuestionLimit:unlimited?null:DAILY_QUESTION_LIMIT,remainingQuestions:unlimited?null:Math.max(0,DAILY_QUESTION_LIMIT-usedToday-1)});
  }catch(error:any){console.error('education-tutor-v2 failed',error);return json(res,500,{error:'A IA encontrou uma falha inesperada. Tente novamente.'})}
}
