import { generateText } from 'ai';
import { google } from '@ai-sdk/google';
import { createClient } from '@supabase/supabase-js';

const MODEL = 'openai/gpt-5.6-luna';
const REVIEW_MODEL = 'google/gemini-3.6-flash';
const SEARCH_MODEL = 'google/gemini-2.5-flash-lite';
const FALLBACK_MODELS = ['google/gemini-3.6-flash', 'openai/gpt-5.4-mini'];
const DAILY_QUESTION_LIMIT = 20;
const FALLBACK_SUPABASE_URL = 'https://kmognvgnfisdchzffkgh.supabase.co';
const FALLBACK_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6Imttb2dudmduZmlzZGNoemZma2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MzkxNjksImV4cCI6MjEwMjMxNTE2OX0.JarpsXfgv8PplL3Ryvs6iFfEPiv_rnp2Cx5i1I67fCk';

type Msg = { role: 'user' | 'assistant'; content: string };
type Skill = { area: string; skill_code: string; skill_name: string; scope?: string; diagnostic_tags?: string[]; parent_skill_code?: string | null; official_reference?: boolean };
type Practice = { id: number; area: string; skill_name: string; difficulty: number; prompt: string; option_a?: string; option_b?: string; option_c?: string; option_d?: string; option_e?: string; correct_option: string; explanation: string; source_basis?: string; source_kind?: string; source_exam_year?: number | null; source_question_number?: number | null; source_exam_label?: string | null; source_caderno?: string | null; source_exam_url?: string | null; source_answer_url?: string | null; source_verified_at?: string | null };

const EXAM_FINGERPRINTS: Record<string, string> = {
  enem: 'ENEM: 180 questões em dois dias + redação. Priorize leitura contextual, modelagem e aplicação; não invente TRI. Em redação, use as cinco competências do ENEM e proposta de intervenção.',
  fuvest: 'FUVEST: vestibular da USP com 1ª fase objetiva e 2ª fase discursiva/redação. Respeite a etapa ativa e valorize desenvolvimento e justificativa nas discursivas.',
  cmmg: 'FCM-MG/CMMG: reconheça Medicina e EFFPO pelo contexto e nunca misture quantidade de questões, pesos ou critérios entre modalidades.',
  insper: 'Insper: 60 questões objetivas e redação dissertativo-argumentativa. Reconheça as disciplinas e os quatro critérios próprios cadastrados. Não confunda a redação do Insper com o padrão ENEM.',
  link: 'Link School of Business: jornada holística em PREP, SPRINT e entrevista. No SPRINT, diagnostique matemática, business case, dados, mercado, trade-offs, recomendação e comunicação.'
};

function json(res: any, status: number, body: unknown) { res.setHeader('Cache-Control', 'no-store'); return res.status(status).json(body); }
function trim(v: unknown, max = 4000) { return String(v ?? '').slice(0, max); }
function clamp(v: unknown, min = 0, max = .99) { return Math.max(min, Math.min(max, Number(v) || 0)); }
function cleanEnv(v: unknown) { return String(v ?? '').trim().replace(/^["']|["']$/g, ''); }
function tokens(s: string) { return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').split(/[^a-z0-9]+/).filter(x => x.length > 2); }
function list(v: unknown, n = 4) { return Array.isArray(v) ? v.map(x => trim(x, 220).trim()).filter(Boolean).slice(0, n) : []; }
function confidenceLabel(v: number) { return v >= .94 ? 'Alta confiança' : v >= .80 ? 'Confiança moderada' : 'Baixa confiança'; }
function hard(s: string) { return /\b(exceto|incorreta|respectivamente|necessariamente|sempre|nunca|condicional|sem reposi[cç][aã]o|aproxima[cç][aã]o|arredond|contraexemplo|causa|consequ[eê]ncia|gr[aá]fico|tabela|imagem|figura|gabarito|banca|20\d{2})\b/i.test(s) || /[=<>±√^]/.test(s); }
function unexpectedScript(s: string) { return /[\u0400-\u052f\u0590-\u08ff\u0900-\u109f\u3040-\u30ff\u3400-\u9fff]/u.test(s); }
function parseJson(raw: string) { const s = raw.trim().replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```$/, '').trim(); const a = s.indexOf('{'), b = s.lastIndexOf('}'); for (const c of [s, a >= 0 && b > a ? s.slice(a, b + 1) : '']) { if (!c) continue; try { return JSON.parse(c); } catch {} try { return JSON.parse(c.replace(/\\(?!["\\/bfnrtu])/g, '\\\\')); } catch {} } throw new Error('invalid-json'); }
function config() { const raw = cleanEnv(process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL); const key = cleanEnv(process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY); try { const u = new URL(raw.startsWith('http') ? raw : `https://${raw}`); if (key && /^[a-z0-9-]+\.supabase\.co$/i.test(u.hostname)) return { url: u.origin, key }; } catch {} return { url: FALLBACK_SUPABASE_URL, key: FALLBACK_SUPABASE_ANON_KEY }; }
async function fetchJson(url: string, headers: Record<string, string>): Promise<any[]> { const r = await fetch(url, { headers, signal: AbortSignal.timeout(9000) }); if (!r.ok) return []; const data = await r.json(); return Array.isArray(data) ? data : []; }
function rankSkills(skills: Skill[], query: string, area: string, currentSkill: string) { const q = new Set(tokens(query)), a = area.toLowerCase(), cs = currentSkill.toLowerCase(); return skills.map(s => { let score = 0; const hay = tokens(`${s.area} ${s.skill_code} ${s.skill_name} ${s.scope || ''} ${(s.diagnostic_tags || []).join(' ')}`); if (a && s.area.toLowerCase().includes(a)) score += 10; if (cs && s.skill_name.toLowerCase().includes(cs)) score += 14; for (const t of hay) if (q.has(t)) score += 2; return { s, score }; }).sort((x, y) => y.score - x.score).filter((x, i) => x.score > 0 || i < 20).slice(0, 36).map(x => x.s); }
function rankPractice(items: Practice[], query: string, area: string, currentSkill: string, difficulties: string[], seen: Set<number>) { const q = new Set(tokens(query)), a = area.toLowerCase(), cs = currentSkill.toLowerCase(), ds = tokens(difficulties.join(' ')); return items.map(item => { let score = 0; const hay = tokens(`${item.area} ${item.skill_name} ${item.prompt}`); if (a && item.area.toLowerCase().includes(a)) score += 12; if (cs && item.skill_name.toLowerCase().includes(cs)) score += 18; for (const t of hay) if (q.has(t)) score += 2; for (const t of hay) if (ds.includes(t)) score += 1.5; if (item.source_kind === 'official' || item.source_kind === 'official_adapted') score += 1.5; if (seen.has(Number(item.id))) score -= 18; return { item, score }; }).sort((x, y) => y.score - x.score || Number(y.item.difficulty || 0) - Number(x.item.difficulty || 0)).filter((x, i) => x.score > 0 || i < 12).slice(0, 6).map(x => x.item); }
function provenance(q: Practice) { return { kind: q.source_kind || 'legacy', label: q.source_exam_label || null, year: q.source_exam_year || null, number: q.source_question_number || null, caderno: q.source_caderno || null, verified: Boolean(q.source_verified_at), examUrl: q.source_exam_url || null, answerUrl: q.source_answer_url || null, official: q.source_kind === 'official' || q.source_kind === 'official_adapted' }; }
function sourceList(v: unknown) { if (!Array.isArray(v)) return []; return v.slice(0, 4).map((s: any) => { try { const u = new URL(String(s?.url || '')); return { title: trim(s?.title || u.hostname, 140), url: u.toString() }; } catch { return null; } }).filter(Boolean); }
async function verifyToken(url: string, key: string, token: string) { const client = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false } }); try { const { data, error } = await client.auth.getClaims(token); const c = (data as any)?.claims; if (!error && c?.sub) return { userId: String(c.sub), isAdmin: String(c?.app_metadata?.role || '').toLowerCase() === 'admin' }; } catch {} try { const { data, error } = await client.auth.getUser(token); if (!error && data?.user?.id) return { userId: String(data.user.id), isAdmin: String(data.user.app_metadata?.role || '').toLowerCase() === 'admin' }; } catch {} return { userId: '', isAdmin: false }; }
async function premium(url: string, key: string, token: string, userId: string) { try { const rows = await fetchJson(`${url}/rest/v1/premium_subscriptions?select=status,current_period_end&user_id=eq.${encodeURIComponent(userId)}&limit=1`, { apikey: key, Authorization: `Bearer ${token}`, Accept: 'application/json' }); const r = rows[0]; return Boolean(r && ['active', 'trialing'].includes(String(r.status || '')) && (!r.current_period_end || new Date(r.current_period_end).getTime() > Date.now())); } catch { return false; } }

export default async function handler(req: any, res: any) {
  if (req.method === 'GET') return json(res, 200, { ok: true, service: 'IA Conectaê v2', model: MODEL, reviewModel: REVIEW_MODEL, searchModel: SEARCH_MODEL, retrieval: 'full-active-corpus+skill+area+difficulty+seen-history+provenance', supportedExams: Object.keys(EXAM_FINGERPRINTS), dailyQuestionLimit: DAILY_QUESTION_LIMIT, adminAccess: 'unlimited' });
  if (req.method !== 'POST') return json(res, 405, { error: 'Método não permitido.' });
  try {
    const auth = String(req.headers.authorization || ''); if (!auth.startsWith('Bearer ')) return json(res, 401, { error: 'Faça login para conversar com a IA Conectaê.' });
    const token = auth.slice(7).trim(), cfg = config(), verified = await verifyToken(cfg.url, cfg.key, token); if (!verified.userId) return json(res, 401, { error: 'Sua sessão expirou. Entre novamente.' });
    const userId = verified.userId, headers = { apikey: cfg.key, Authorization: `Bearer ${token}` }, premiumUnlimited = verified.isAdmin ? false : await premium(cfg.url, cfg.key, token, userId), unlimited = verified.isAdmin || premiumUnlimited;
    const body = req.body || {}, rawMessages = body.messages, context = body.context && typeof body.context === 'object' ? body.context : {}, imageDataUrl = body.imageDataUrl;
    if (!Array.isArray(rawMessages) || !rawMessages.length) return json(res, 400, { error: 'Escreva sua dúvida.' });
    const safe: Msg[] = rawMessages.slice(-10).map((m: any): Msg => ({ role: m?.role === 'assistant' ? 'assistant' : 'user', content: trim(m?.content, 2400) })).filter((m: Msg) => m.content.trim().length > 0);
    if (!safe.length) return json(res, 400, { error: 'Escreva sua dúvida.' });
    const image = typeof imageDataUrl === 'string'; if (image && !/^data:image\/(jpeg|png|webp);base64,/i.test(imageDataUrl)) return json(res, 400, { error: 'Formato de imagem inválido.' }); if (image && imageDataUrl.length > 4_800_000) return json(res, 413, { error: 'A foto ficou grande demais. Recorte apenas a questão.' });
    const exam = trim(context.exam || 'enem', 40).toLowerCase(), latest = safe[safe.length - 1]?.content || ''; let usedToday = 0;
    if (!unlimited) { try { const minute = new Date(Date.now() - 60_000).toISOString(), day = new Date(Date.now() - 86_400_000).toISOString(); const [a, b] = await Promise.all([fetch(`${cfg.url}/rest/v1/ai_tutor_usage?select=id&user_id=eq.${userId}&created_at=gte.${encodeURIComponent(minute)}`, { headers: { ...headers, Prefer: 'count=exact' }, signal: AbortSignal.timeout(7000) }), fetch(`${cfg.url}/rest/v1/ai_tutor_usage?select=id&user_id=eq.${userId}&created_at=gte.${encodeURIComponent(day)}`, { headers: { ...headers, Prefer: 'count=exact' }, signal: AbortSignal.timeout(7000) })]); const mc = Number(a.headers.get('content-range')?.split('/')?.[1] || 0), dc = Number(b.headers.get('content-range')?.split('/')?.[1] || 0); usedToday = dc; if (mc >= 8) return json(res, 429, { error: 'Aguarde um minuto antes de enviar mais perguntas.' }); if (dc >= DAILY_QUESTION_LIMIT) return json(res, 429, { error: `Você atingiu o limite de ${DAILY_QUESTION_LIMIT} perguntas da IA Conectaê hoje.` }); } catch {} }
    const [refsRaw, skillsRaw, practiceRaw, seenRows] = await Promise.all([fetchJson(`${cfg.url}/rest/v1/exam_ai_skill_reference?select=area,skill_code,skill_name,scope,diagnostic_tags,parent_skill_code,official_reference&exam_id=eq.${encodeURIComponent(exam)}`, { ...headers, Accept: 'application/json' }), fetchJson(`${cfg.url}/rest/v1/exam_skill_taxonomy?select=area,skill_code,skill_name,diagnostic_tags&exam_id=eq.${encodeURIComponent(exam)}`, { ...headers, Accept: 'application/json' }), fetchJson(`${cfg.url}/rest/v1/exam_practice_questions?select=id,area,skill_name,difficulty,prompt,option_a,option_b,option_c,option_d,option_e,correct_option,explanation,source_basis,source_kind,source_exam_year,source_question_number,source_exam_label,source_caderno,source_exam_url,source_answer_url,source_verified_at&exam_id=eq.${encodeURIComponent(exam)}&active=is.true&limit=1500`, { ...headers, Accept: 'application/json' }), fetchJson(`${cfg.url}/rest/v1/student_seen_questions?select=question_id&user_id=eq.${encodeURIComponent(userId)}&limit=1500`, { ...headers, Accept: 'application/json' })]);
    const refs = refsRaw as Skill[], skills = skillsRaw as Skill[], practice = practiceRaw as Practice[], seen = new Set<number>(seenRows.map((r: any) => Number(r.question_id))), area = trim(context.currentArea, 80), currentSkill = trim(context.currentSkill, 150), contextQuestion = trim(context.currentQuestion, 2200), difficulties = list(context.recentDifficulties, 6);
    const taxonomyRefs: Skill[] = skills.map(s => ({ ...s, scope: `Habilidade da taxonomia ${exam}: ${s.skill_name}`, official_reference: false })); const pool = [...refs, ...taxonomyRefs.filter(t => !refs.some(r => r.skill_code === t.skill_code))], candidates = rankSkills(pool, `${latest} ${contextQuestion}`, area, currentSkill), examples = rankPractice(practice, `${latest} ${contextQuestion}`, area, currentSkill, difficulties, seen), corpusStats = { active: practice.length, officialOrAdapted: practice.filter(q => q.source_kind === 'official' || q.source_kind === 'official_adapted').length, authorial: practice.filter(q => q.source_kind === 'authorial').length, skills: skills.length }, student = { exam, weeklyHours: trim(context.weeklyHours, 12), recentDifficulties: difficulties, recentPerformance: list(context.recentPerformance, 6), currentQuestion: contextQuestion, currentSkill, area }, examplesSafe = examples.map(q => ({ id: q.id, area: q.area, skill: q.skill_name, difficulty: q.difficulty, prompt: q.prompt, options: { A: q.option_a, B: q.option_b, C: q.option_c, D: q.option_d, E: q.option_e }, answer: q.correct_option, explanation: q.explanation, provenance: provenance(q) }));
    const system = `Você é a IA Conectaê v2, tutor de vestibulares brasileiro rigoroso, didático e intelectualmente honesto. Responda em português do Brasil. Nunca finja 100% de precisão. Releia o comando e confira EXCETO/incorreta/sempre/nunca, domínio, sinais, unidades, causalidade e alternativas. Não exponha cadeia interna. FOTO: se faltar informação necessária, needs_better_image=true e não invente. PROVA: ${EXAM_FINGERPRINTS[exam] || 'Use estritamente a taxonomia cadastrada da prova ativa.'} PROVENIÊNCIA: authorial é autoral; official/official_adapted só é oficial/adaptada se a procedência recebida sustentar. Nunca invente ano, número ou banca. CONTEXTO DO ALUNO: ${JSON.stringify(student)} HABILIDADES CANDIDATAS: ${JSON.stringify(candidates.map(s => ({ area: s.area, skill_code: s.skill_code, skill_name: s.skill_name, parent_skill_code: s.parent_skill_code || null })))} EXEMPLOS RECUPERADOS: ${JSON.stringify(examplesSafe)} Retorne APENAS JSON válido: {"answer":"resposta curta e didática","confidence":0.0,"confidence_reason":"uma frase objetiva","self_check_passed":true,"needs_external_check":false,"answerable":true,"resolved_doubt":true,"needs_better_image":false,"uncertainty_reason":null,"assumptions":[],"learning_focus":{"area":"","skill_code":"","skill_name":"","plan_skill_code":null,"confidence":0.0,"reason":""},"offer_plan":false}`;
    const modelMessages: any[] = safe.map((m, i) => i === safe.length - 1 && m.role === 'user' && image ? { role: 'user', content: [{ type: 'text', text: m.content }, { type: 'image', image: imageDataUrl }] } : { role: m.role, content: m.content });
    let raw = ''; try { raw = String((await generateText({ model: MODEL, system, messages: modelMessages, maxOutputTokens: 1700, abortSignal: AbortSignal.timeout(45_000), providerOptions: { gateway: { models: FALLBACK_MODELS, user: userId, tags: ['feature:education-tutor-v2', `exam:${exam}`] } } } as any)).text || ''); } catch (e: any) { console.error('tutor v2 primary', e?.message || e); } if (!raw) return json(res, 502, { error: 'A IA ficou temporariamente indisponível. Tente novamente.' });
    let first: any; try { first = parseJson(raw); } catch { return json(res, 502, { error: 'A resposta ficou incompleta. Tente novamente.' }); }
    let final: any = first, mode: 'primary' | 'search' | 'review' = 'primary', sources: any[] = []; const baseConf = clamp(first.confidence), explicitLookup = /\b(gabarito|fonte|banca|prova|vestibular|quest[aã]o\s*\d+|20\d{2})\b/i.test(`${latest} ${contextQuestion}`), shouldSearch = Boolean(first.needs_external_check) || (explicitLookup && baseConf < .95) || (image && baseConf < .72), shouldReview = hard(`${latest} ${contextQuestion}`) || first.self_check_passed === false || baseConf < .84;
    if (shouldSearch) { try { const r = await generateText({ model: SEARCH_MODEL, system: 'Você é o verificador externo. Prefira fonte oficial. web_verified=true apenas com fonte que sustente a conclusão. Não exponha cadeia interna. Retorne JSON com answer, confidence, confidence_reason, self_check_passed, answerable, resolved_doubt, needs_better_image, uncertainty_reason, assumptions e web_verified.', messages: [{ role: 'user', content: image ? [{ type: 'text', text: `Prova: ${exam}\nPergunta: ${latest}\nEnunciado: ${contextQuestion}\nPreliminar: ${trim(first.answer, 2200)}` }, { type: 'image', image: imageDataUrl }] : `Prova: ${exam}\nPergunta: ${latest}\nEnunciado: ${contextQuestion}\nPreliminar: ${trim(first.answer, 2200)}` }], maxOutputTokens: 1300, abortSignal: AbortSignal.timeout(45_000), tools: { google_search: google.tools.googleSearch({}) }, providerOptions: { gateway: { user: userId, tags: ['feature:education-tutor-v2', 'external-verification'] } } } as any); const parsed: any = parseJson(String(r.text || '')), found = sourceList((r as any).sources); if (parsed?.answer && parsed.web_verified===true && found.length) { final = { ...first, ...parsed }; sources = found; mode = 'search'; } } catch (e: any) { console.warn('tutor v2 search', e?.message || e); } }
    if (mode === 'primary' && shouldReview) { try { const r = await generateText({ model: REVIEW_MODEL, system: 'Você é o revisor adversarial final. Resolva do zero e compare com a preliminar. Não exponha cadeia interna. Retorne JSON com answer, confidence, confidence_reason, self_check_passed, answerable, resolved_doubt, needs_better_image, uncertainty_reason, assumptions e agrees_with_preliminary.', messages: [{ role: 'user', content: image ? [{ type: 'text', text: `Pergunta: ${latest}\nEnunciado: ${contextQuestion}\nPreliminar: ${trim(first.answer, 2200)}` }, { type: 'image', image: imageDataUrl }] : `Pergunta: ${latest}\nEnunciado: ${contextQuestion}\nPreliminar: ${trim(first.answer, 2200)}` }], maxOutputTokens: 1300, abortSignal: AbortSignal.timeout(45_000), providerOptions: { gateway: { models: ['openai/gpt-5.4-mini'], user: userId, tags: ['feature:education-tutor-v2', 'adversarial-review'] } } } as any); const parsed: any = parseJson(String(r.text || '')); if (parsed?.answer) { final = { ...first, ...parsed }; if (parsed.agrees_with_preliminary === false) { final.confidence = Math.min(clamp(parsed.confidence), .79); final.uncertainty_reason = parsed.uncertainty_reason || 'A revisão independente divergiu da primeira solução e a resposta foi corrigida.'; } mode = 'review'; } } catch (e: any) { console.warn('tutor v2 review', e?.message || e); } }
    let answer = trim(final.answer, 6000).trim(); if (!answer) return json(res, 502, { error: 'A resposta ficou incompleta. Tente novamente.' }); if (unexpectedScript(answer)) { try { answer = trim((await generateText({ model: REVIEW_MODEL, system: 'Reescreva em português do Brasil usando apenas alfabeto latino e matemática em texto simples, sem mudar fatos, números ou conclusão.', messages: [{ role: 'user', content: answer }], maxOutputTokens: 800, abortSignal: AbortSignal.timeout(25_000) } as any)).text, 6000); } catch {} if (unexpectedScript(answer)) return json(res, 502, { error: 'A resposta ficou com caracteres inválidos. Tente novamente.' }); }
    const answerable = Boolean(final.answerable ?? true), selfChecked = Boolean(final.self_check_passed), resolvedDoubt = Boolean(final.resolved_doubt), needsBetterImage = Boolean(final.needs_better_image); let confidence = clamp(final.confidence ?? first.confidence); if (!answerable || !selfChecked || !resolvedDoubt) confidence = Math.min(confidence, .79); if (needsBetterImage) confidence = Math.min(confidence, .55); let focus: any = final.learning_focus && typeof final.learning_focus === 'object' ? final.learning_focus : first.learning_focus; if (focus) { const m = candidates.find(s => s.skill_code === String(focus.skill_code || '') && s.skill_name === String(focus.skill_name || '')); if (!m) focus = null; else { const pc = String(focus.plan_skill_code || m.parent_skill_code || ''), plan = skills.find(s => s.skill_code === pc); focus = { area: m.area, skill_code: m.skill_code, skill_name: m.skill_name, plan_skill_code: plan?.skill_code || null, plan_skill_name: plan?.skill_name || null, confidence: clamp(focus.confidence || confidence), reason: trim(focus.reason, 320), official_reference: Boolean(m.official_reference) }; } } const offerPlan = Boolean(final.offer_plan ?? first.offer_plan) && Boolean(focus) && Number(focus?.confidence) >= .68 && resolvedDoubt;
    try { await fetch(`${cfg.url}/rest/v1/ai_tutor_usage`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json', Prefer: 'return=minimal' }, body: JSON.stringify({ user_id: userId, exam_id: exam, has_image: image }), signal: AbortSignal.timeout(5000) }); } catch {}
    return json(res, 200, { answer, educational: true, resolvedDoubt, answerable, confidence, confidenceLabel: confidenceLabel(confidence), confidenceReason: trim(final.confidence_reason ?? first.confidence_reason, 300), uncertaintyReason: trim(final.uncertainty_reason ?? first.uncertainty_reason, 400) || null, assumptions: list(final.assumptions ?? first.assumptions, 4), selfChecked, learningFocus: focus, offerPlan, needsBetterImage, model: mode === 'search' ? SEARCH_MODEL : mode === 'review' ? REVIEW_MODEL : MODEL, searchMode: mode, webVerified: mode === 'search' && sources.length > 0, sources, costOptimized: true, retrievalGrounded: examples.length > 0, retrievedExamples: examples.length, corpusStats, provenanceAware: true, seenQuestionAware: true, adminUnlimited: verified.isAdmin, premiumUnlimited, dailyQuestionLimit: unlimited ? null : DAILY_QUESTION_LIMIT, remainingQuestions: unlimited ? null : Math.max(0, DAILY_QUESTION_LIMIT - usedToday - 1) });
  } catch (error: any) { console.error('education-tutor-v2 failed', error); return json(res, 500, { error: 'A IA encontrou uma falha inesperada. Tente novamente.' }); }
}
