export type Sas5Day1Item={q:number;answer:'A'|'B'|'C'|'D'|'E';area:string;focus:string;confidence:'high'|'medium'};

export const SAS5_DAY1_2026: Sas5Day1Item[]=[
[1,'D','Linguagens','sátira ao avanço científico; validação subjetiva e experimento precário','high'],
[2,'D','Linguagens','poema em inglês; perish utterly indica extinção absoluta','high'],
[3,'A','Linguagens','imigração; hibridização cultural entre referências cubanas e americanas','high'],
[4,'C','Linguagens','imigração; quebra da idealização dos EUA pelo choque com a realidade','high'],
[5,'B','Linguagens','mapeamento genético de câncer em gatos como apoio potencial à oncologia humana','high'],
[6,'B','Linguagens','texto de divulgação sobre vídeos acelerados; dados e método conferem credibilidade','medium'],
[7,'B','Linguagens','divulgação científica; mobilização de evidências acadêmicas sobre cognição','medium'],
[8,'C','Linguagens','tecnologia de vídeo; controle do ritmo de exibição do conteúdo','medium'],
[9,'C','Linguagens','vídeos acelerados; aumento da carga cognitiva na recepção','medium'],
[10,'E','Linguagens','questionamento retórico introduz contraposição sobre desvantagens','medium'],
[11,'C','Linguagens','campanha contra ghosting em consultas; responsabilidade com compromissos','high'],
[12,'D','Linguagens','romance português; precariedade de infraestrutura e deslocamento no interior','high'],
[13,'B','Linguagens','função emotiva; expressão de desejo simbólico do eu lírico','high'],
[14,'C','Linguagens','jogo indígena Ikindene; movimento corporal articulado a sentidos culturais','high'],
[15,'A','Linguagens','rabeca; morfologia condicionada a tradições e condições materiais de produção','high'],
[16,'C','Linguagens','coesão referencial; neste seleto grupo retoma obras que alcançam status de clássico','high'],
[17,'D','Linguagens','romance indígena; analogia torna compreensível um conceito abstrato','high'],
[18,'D','Linguagens','pobreza menstrual; reprodução de desigualdades socioestruturais','high'],
[19,'E','Linguagens','memória da mãe; saudosismo ligado à lembrança e à perda','high'],
[20,'B','Linguagens','vanguardas; composição de imagens ilógicas associada ao Surrealismo','high'],
[21,'D','Linguagens','IA e autoria; distância entre geração automática e legitimidade social da autoria','high'],
[22,'D','Linguagens','futebol de várzea; pressão do interesse econômico nas mudanças espaciais','high'],
[23,'D','Linguagens','Tarsila e moda; hibridismo estético do projeto modernista','high'],
[24,'B','Linguagens','artigo sobre cinema; perguntas retóricas provocam reflexão do leitor','high'],
[25,'B','Linguagens','HQ de Machado; imagens expressivas intensificam a narrativa verbal','high'],
[26,'D','Linguagens','sotaque; diversidade linguística como marca identitária','high'],
[27,'D','Linguagens','poesia; construção de sentido existencial a partir da experiência cotidiana','high'],
[28,'C','Linguagens','Van Gogh; transposição de impressões subjetivas para a pintura','high'],
[29,'E','Linguagens','entrevista com Miró da Muribeca; oralidade e práticas de circulação literária','high'],
[30,'A','Linguagens','Auto da Compadecida; modo de falar representativo de contexto regional específico','high'],
[31,'A','Linguagens','branqueamento de corais; função referencial informa impactos ambientais','high'],
[32,'E','Linguagens','armazenamento em vidro; reduzir vulnerabilidade de registros à volatilidade digital','high'],
[33,'C','Linguagens','metáfora da indigestão de buraco negro aproxima ciência do cotidiano','high'],
[34,'B','Linguagens','campanha Rompa o Ciclo; protagonismo da mulher no enfrentamento da violência','high'],
[35,'C','Linguagens','Cubismo; ruptura com paradigma de representação naturalista','high'],
[36,'B','Linguagens','poema de Bandeira; aceitação da finitude da vida','high'],
[37,'B','Linguagens','verificação etária; conciliar identificação com preservação da privacidade','high'],
[38,'C','Linguagens','manual literário; subversão da finalidade utilitária do gênero para fins estéticos','high'],
[39,'C','Linguagens','norma curta; conjunto prescritivista de regras artificiais','high'],
[40,'B','Linguagens','atividade física; construção de redes de sociabilidade como benefício psicológico','high'],
[41,'D','Linguagens','antibióticos; conscientização sobre uso responsável de medicamentos','high'],
[42,'C','Linguagens','narrativa; religiosidade como fonte de amparo','high'],
[43,'A','Linguagens','infância pobre; amadurecimento antecipado por condições econômicas','high'],
[44,'A','Linguagens','vinte minutos; repetição gera humor e impulsiona a narrativa','high'],
[45,'E','Linguagens','artigo de opinião; discurso direto exemplifica variedade de textos e situações editoriais','high'],
[46,'D','Humanas','Ostalgie; produção de memória com narrativas contrastantes sobre a RDA','high'],
[47,'B','Humanas','protestos no Nepal; desigualdade de oportunidades','high'],
[48,'D','Humanas','africanos em Pernambuco; adaptação cultural preservando memórias e práticas','high'],
[49,'B','Humanas','Galileu; verdade alcançada pela experimentação','high'],
[50,'E','Humanas','substituição mineral por fluidos e calor; formação de rochas metamórficas','high'],
[51,'B','Humanas','Muro de Berlim; conservação da cultura material como patrimônio','high'],
[52,'C','Humanas','drones russos no espaço polonês; tensionamento de fronteiras regionais','high'],
[53,'C','Humanas','Locke; memória como condição para apreensão da realidade','high'],
[54,'A','Humanas','fast fashion e produção fragmentada; otimização de cadeias de suprimentos','high'],
[55,'A','Humanas','Bauman; facilidade de contato reduz investimento afetivo nos vínculos','high'],
[56,'E','Humanas','Conferência de Berlim; exploração econômica dos territórios africanos','high'],
[57,'B','Humanas','Haraway e Antropoceno; consciência de pertencimento entre terráqueos','high'],
[58,'D','Humanas','soberania digital; subordinação do controle informacional a grandes corporações','high'],
[59,'A','Humanas','plataformização; dispersão espacial da força de trabalho','high'],
[60,'B','Humanas','protestos indígenas no Tapajós; interrupção do avanço de atividade econômica','high'],
[61,'B','Humanas','Platão; justiça e bem comum pela função adequada de cada grupo','high'],
[62,'C','Humanas','Mercosul-UE; cooperação multilateral versus demanda setorial protecionista','high'],
[63,'B','Humanas','demarcação indígena; reconhecimento legal de direitos fundiários originários','high'],
[64,'A','Humanas','Aristóteles; formação do caráter virtuoso por hábitos e leis','high'],
[65,'D','Humanas','Tupi e Tapuia; classificação social colonial reducionista','high'],
[66,'C','Humanas','queijo artesanal mineiro; reafirmação de identidade regional','high'],
[67,'E','Humanas','passagem de fauna em rodovia; manutenção da biodiversidade local','high'],
[68,'B','Humanas','urbanismo social; redefinição da participação pública com coautoria comunitária','high'],
[69,'E','Humanas','toponímia e gênero; democratização da representatividade pública','high'],
[70,'B','Humanas','Lei de Migração e apatridia; promoção de direitos básicos','high'],
[71,'C','Humanas','abolição no Ceará; fragilidade da tese de escassez de mão de obra sem escravidão','high'],
[72,'B','Humanas','terraços de arroz; transformação antrópica do relevo acidentado','high'],
[73,'E','Humanas','Locke versus Wittgenstein; significado como utilização social das palavras','high'],
[74,'A','Humanas','paisagem no Vietnã; integração cotidiana da natureza na experiência do lugar','high'],
[75,'E','Humanas','desembarque de Dona Leopoldina; legitimação política por ancestralidade dinástica','high'],
[76,'C','Humanas','Feira de São Cristóvão; reconstrução de redes de sociabilidade comunitária','high'],
[77,'B','Humanas','enchentes urbanas; recuperação de várzeas fluviais','high'],
[78,'B','Humanas','Carta-testamento de Vargas; construção do líder carismático','high'],
[79,'C','Humanas','agroecologia e cozinha comunitária; autonomia da produção coletiva','high'],
[80,'C','Humanas','Rousseau; proteção e participação asseguradas pela vontade geral','high'],
[81,'A','Humanas','Estado Novo e samba; regulamentação estatal de manifestações culturais','high'],
[82,'C','Humanas','competências genéricas; substituição ampliada de trabalhadores','high'],
[83,'B','Humanas','imprensa insurgente na Nova Espanha; divulgação de ideais contestatórios','high'],
[84,'B','Humanas','filosofia medieval; conciliação entre análise racional e convicção interior','high'],
[85,'C','Humanas','Goffman; reconhecimento inicial por impressões superficiais','high'],
[86,'C','Humanas','Locke; justiça civil por mediação imparcial das divergências segundo leis','high'],
[87,'A','Humanas','engorda de praias; manutenção da funcionalidade econômica da orla','high'],
[88,'E','Humanas','capitalismo industrial; disciplina produtiva do tempo como norma moral','high'],
[89,'B','Humanas','mapa do Programa de Integração Nacional; construção ideológica do espaço amazônico','high'],
[90,'C','Humanas','distinção de classe; prestígio diferencial dos símbolos do cotidiano','high'],
].map(([q,answer,area,focus,confidence])=>({q:q as number,answer:answer as Sas5Day1Item['answer'],area:area as string,focus:focus as string,confidence:confidence as Sas5Day1Item['confidence']}));

export const SAS5_DAY1_2026_META={
  label:'5º Simulado SAS ENEM 2026 - 3º ano - 1º dia - Caderno 2 Amarelo',
  source:'PDF enviado pelo usuário em 13/09/2026',
  status:'gabarito analítico produzido pela IA, não gabarito oficial do SAS',
  note:'O PDF fornecido não contém a página impressa 6, que traz o texto-base das questões 6 a 10; por isso essas cinco respostas ficam marcadas com confiança média até confronto com o gabarito oficial ou a página ausente.',
};

export function sas5Day1Question(q:number){return SAS5_DAY1_2026.find(item=>item.q===q)||null;}
export function sas5Day1Key(){return SAS5_DAY1_2026.map(item=>`${item.q}${item.answer}`).join(' ');}
